---
permalink: wombat/reference_wombat_set_snapvolume_mediascanenabled.html
sidebar: sidebar
keywords: 
summary: 'The set snapVolume mediaScanEnabled command runs a media scan on the drives used for a snapshot volume.'
---
= Set snapshot volume media scan
:icons: font
:imagesdir: ./media/

[.lead]
The `set snapVolume mediaScanEnabled` command runs a media scan on the drives used for a snapshot volume.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

Optionally, you also can perform a redundancy check on the data.

== Syntax

----
set snapVolume ["snapVolumeName"]
mediaScanEnabled=(TRUE | FALSE)
[redundancyCheckEnabled=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`snapVolume`
a|
The name of the snapshot volume for which you are setting properties. Enclose the snapshot volume identifier in double quotation marks (" ") inside of square brackets ([ ]).
a|
`mediaScanEnabled`
a|
The setting to turn on or turn off media scan for the snapshot volume. To turn on media scan, set this parameter to `TRUE`. To turn off media scan, set this parameter to `FALSE`. (If media scan is disabled at the storage array level, this parameter has no effect.)
a|
`redundancyCheckEnabled`
a|
The setting to turn on or turn off redundancy checking during a media scan. To turn on redundancy checking, set this parameter to `TRUE` . To turn off redundancy checking, set this parameter to `FALSE`.

|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

7.83
