---
permalink: wombat/reference_wombat_start_drive_erase.html
sidebar: sidebar
keywords: 
summary: 'The start drive erase command erases all of the data from one or more drives.'
---
= Start drive erase
:icons: font
:imagesdir: ./media/

[.lead]
The `start drive erase` command erases all of the data from one or more drives.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 array. It does operate on E2700 and E5600storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

Run this command only if you want to permanently remove all data on a drive. If the drive is secure-enabled, the `start drive erase` command option performs a cryptographic erase and resets the drive's security attributes back to secure-capable.

[NOTE]
====
The erase operation cannot be undone. Make sure you select the correct drive when using this command.
====

== Syntax

----
start drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\] erase
----

== Parameters

|===
| Parameter| Description
a|
`drive` or `drives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

[NOTE]
====
The drives list cannot contain all of the drives in the storage array, or the command will be rejected.
====

|===

== Minimum firmware level

11.70.1
