---
permalink: wombat/reference_wombat_set_snmptrapdestination_trapreceiverip.html
sidebar: sidebar
keywords: 
summary: 'The set snmpTrapDestination trapReceiverIP command turns on or turns off sending authentication failure messages for an SNMP trap destination. Failure occurs when the SNMP agent received a message from an SNMP manager, but the message contained an invalid community name or user name.'
---
= Update SNMP trap destination
:icons: font
:imagesdir: ./media/

[.lead]
The `set snmpTrapDestination trapReceiverIP` command turns on or turns off sending authentication failure messages for an SNMP trap destination. Failure occurs when the SNMP agent received a message from an SNMP manager, but the message contained an invalid community name or user name.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax

----
set snmpTrapDestination trapReceiverIP=ipAddress
    (communityName="communityName" | (userName="userName" [engineId=(local | engineId)]))
    [sendAuthenticationFailureTraps=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`trapReceiverIP`
a|
The IP address of the SNMP manager to which you want to send trap messages.
a|
`communityName`
a|
The name of the SNMP community for which you want to send trap messages.
a|
`userName`
a|
The name of the SNMP user for which you want to send trap messages.
a|
`engineId`
a|
The engine ID of the SNMP user for which you want to send trap messages. The engine ID is required if there is more than one USM user with the same user name. The value may be "[.code]``local``" to specify the local SNMP agent is the authoritative agent or a hexidecimal digit string to specify a remote SNMP agent engine ID.
a|
`sendAuthenticationFailureTraps`
a|
This parameter turns on or turns off sending authentication failure messages to an SNMP manager. To send authentication failure messages, set the parameter to `TRUE`. To prevent sending authentication failure messages, set the parameter to `FALSE`. The default is `TRUE`.
|===

== Minimum firmware level

8.30
