---
permalink: wombat/reference_wombat_delete_controller_cacertificate.html
sidebar: sidebar
keywords: 
summary: 'The delete controller caCertificate command removes the installed root/intermediate CA certificate from the specified controller.'
---
= Remove installed root/intermediate CA certificates
:icons: font
:imagesdir: ./media/

[.lead]
The `delete controller caCertificate` command removes the installed root/intermediate CA certificate from the specified controller.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

delete controller [(a|b)] caCertificate aliases=("alias1" ... "aliasN")
----

== Parameters

|===
| Parameter| Description
a|
`controller`
a|
Allows you to specify the controller on which you want to delete the signed certificate from. Valid controller identifiers are a or b, where a is the controller in slot A, and b is the controller in slot B. Enclose the controller identifier in square brackets ([ ]).
a|
`aliases`
a|
Allows you to specify one or more CA certificates to be deleted using the alias names or specify all. The aliases must be from the controller for which the certificate is being deleted. Enclose all the aliases in parentheses. If you enter more than one alias, separate them with a space.
|===

== Examples

----

SMcli -n Array1 -c "delete controller[a] caCertificate aliases=("myAlias" "anotherAlias");"

SMcli completed successfully.
----

== Minimum firmware level

8.40
