---
permalink: wombat/reference_wombat_set_volumegroup.html
sidebar: sidebar
keywords: 
summary: 'The set volumeGroup command defines the properties for a volume group.'
---
= Set volume group
:icons: font
:imagesdir: ./media/

[.lead]
The `set volumeGroup` command defines the properties for a volume group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
You must perform only one operation (add drives, change the RAID level, or change volume group ownership) per command. You cannot perform more than one operation with a single command.
====

== Syntax

----
set volumeGroup [volumeGroupName]
[addDrives=(trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----

== Parameters

|===
| Parameter| Description
a|
`volumeGroup`
a|
The name of the volume group for which you want to set properties. Enclose the volume group name in square brackets ([ ]).
a|
`addDrives`

a|
The location of the drive that you want to add to the volume group. For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`raidLevel`

a|
The RAID level for the volume group. Valid values are `0`, `1`, `3`, `5`, or `6`.
a|
`owner`

a|
The controller that owns the volume group. Valid controller identifiers are `a` or `b`, where `a` is the controller in slot A , and `b` is the controller in slot B. Use this parameter only if you want to change the volume group owner.
|===

== Notes

Host I/O errors might result in volume groups with more than 32 volumes. This operation also might result in internal controller reboots because the timeout period ends before the volume group definition is set. If you experience this issue, quiesce the host I/O operations, and try the command again.

When you use this command, you can specify only one of the parameters.

[NOTE]
====
Specifying the `addDrives` parameter or the `raidLevel` parameter starts a long-running operation that you cannot stop.
====

The `addDrives` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0`, and specify the ID of the slot in which a drive resides.

== Troubleshooting

Attempting to expand large volume groups by adding drives, also called Dynamic Capacity Expansion (DCE), may fail with the following message:

`Return code: Error 26 - The modification operation cannot complete because of the number of drives in the volume group and the segment size of the associated volumes. Reduce the segment size of all volumes in the volume group to 128 KB or below using the Change Segment Size option. Then, retry the operation.`

Systems running 7.35.xx.xx firmware may fail with the following message instead of the one noted above:

`Return code: Error 462 - A SYMbol procedure could not be carried out because the firmware could not allocate sufficient cache memory. Operation when error occurred: PROC_startVolum`

In addition to the above messages, a Major Event Log (MEL) event indicating insufficient cache available to complete the DCE operation may occur.

Any controller running 7.xx firmware may encounter this problem.

DCE requires enough memory to buffer the data read from the original volume and the data to be written to the expanded volume. Some combination of number of drives in the expansion operation, stripe size, and whether mirror operations are enabled may result in not enough memory being available to complete the DCE operation.

If the above situation is encountered, possible workarounds are as follows:

* Create the desired size volume group using other unassigned drives.
* Delete the current volume group and then recreate the volume group with the desired number of drives.
* Reduce the segment size being used and then retry the operation.
* If possible, add additional memory to the controller and then retry the operation.

== Minimum firmware level

7.10 adds RAID 6 capability.

7.30 removes the `availability` parameter.

7.60 adds the `drawerID` user input.
