---
permalink: wombat/reference_wombat_create_initiator.html
sidebar: sidebar
keywords: 
summary: 'The create initiator command creates the initiator object.'
---
= Create initiator
:icons: font
:imagesdir: ./media/

[.lead]
The `create initiator` command creates the initiator object.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
This command replaces the deprecated xref:reference_wombat_create_iscsiinitiator.adoc[Create iSCSI initiator] command.
====

[NOTE]
====
This command is only applicable to iSCSI, iSER, NVMe over RoCE, NVMe over InfiniBand, and NVMe over Fibre Channel.
====

== Syntax

----

create initiator identifier="initiatorQualifiedName" userLabel="initiatorName" host="hostName"
interfaceType=(iscsi | iser | nvmeof) [chapSecret="securityKey"]
----

== Parameters

|===
| Parameter| Description
a|
`identifier`
a|
Allows you to specify the identifier qualified name (such as iqn or nqn) to create an initiator . Enclose the identifier in double quotation marks (" ").
a|
`userLabel`
a|
Allows you to specify a user label for the initiator. Enclose the name in double quotation marks (" ").
a|
`host`
a|
Allows you to specify the host name where the initiator is installed. Enclose the name in double quotation marks (" ").
a|
`interfaceType`
a|
Allows you to specify which interface type the initiator is for. Valid choices are: iscsi, iser, or nvmeof.
a|
`chapSecret`
a|
Allows you to enter the security key that you want to use to authenticate a peer connection. Enclose the security key in double quotation marks (" "). This parameter is applicable only to iSCSI and iSER host interface types.
|===

== Minimum firmware level

8.41
