---
permalink: wombat/reference_wombat_show_alldrives.html
sidebar: sidebar
keywords: 
summary: 'The show allDrives command returns information about the drives in the storage array.'
---
= Show drive
:icons: font
:imagesdir: ./media/

[.lead]
The `show allDrives` command returns information about the drives in the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

For each drive in the storage array, this command returns the following information:

* The total number of drives
* The type of drive (SAS, or NVMe4K)
* Information about the basic drive:
 ** The tray location and the slot location
 ** The status
 ** The capacity
 ** The data transfer rate
 ** The product ID
 ** The firmware level
* Information about wear life of SSD drives (this information is only valid for the E2800 and E5700/EF570 and is not shown if the array does not contain SSD drives):
 ** The average erase count.
 ** The spare blocks remaining.
 ** The percent endurance used (new in the 11.41 release). The percent endurance used is the amount of data written to the SSD drives to date divided by the total theoretical write limit for the drives.
* Information about the drive channel:
 ** The tray location and the slot location
 ** The preferred channel
 ** The redundant channel
* Hot spare coverage
* Details for each drive
+
[NOTE]
====
Date of Manufacture information is not available for NVMe drives.
====

== Syntax

----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\]))
summary
----

== Parameters

|===
| Parameter| Description
a|
`allDrives`
a|
The setting to return information about all of the drives in the storage array.
a|
`driveMediaType`

a|
The type of drive media for which you want to retrieve information. The following values are valid types of drive media:

* `HDD` -- Use this option when you have hard drives in the drive tray.
* `SSD` -- Use this option when you have solid state drives in the drive tray.
* `unknown` -- Use this option if you are not sure what types of drive media are in the drive tray.
* `allMedia` -- Use this option when you want to use all types of drive media that are in the drive tray.

a|
`driveType`
a|
The type of drive for which you want to retrieve information. You cannot mix drive types.

Valid drive types are:

* `SAS`
* `NVMe4K`

If you do not specify a drive type, the command defaults to any type.

a|
`drive` or `drives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`summary`
a|
The setting to return the status, the capacity, the data transfer rate, the product ID, and the firmware version for the specified drives.
|===

== Notes

To determine information about the type and location of all of the drives in the storage array, use the `allDrives` parameter.

To determine the information about the SAS drives in the storage array, use the `driveType` parameter.

To determine the type of drive in a specific location, use the `drive` parameter, and enter the tray ID and the slot ID for the drive.

The `drive` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0`, and specify the ID of the slot in which a drive resides.

== Minimum firmware level

5.43

7.60 adds the `drawerID` user input and the `driveMediaType` parameter.

8.41 adds wear life reporting information, in the form of the percentage of endurance used, for SSD drives in an E2800, E5700, or EF570 system.
