---
permalink: wombat/reference_wombat_smcli_autosupportschedule_reset.html
sidebar: sidebar
keywords: 
summary: 'The SMcli autoSupportSchedule reset command resets the daily and weekly times and days of the week that AutoSupport messages are sent. You can accept default random values generated by the management software, or you can specify values with this command.'
---
= Reset AutoSupport message collection schedule
:icons: font
:imagesdir: ./media/

[.lead]
The `SMcli autoSupportSchedule reset` command resets the daily and weekly times and days of the week that AutoSupport messages are sent. You can accept default random values generated by the management software, or you can specify values with this command.

== Supported Arrays

This command applies to all E2700 and E5600 storage arrays in the management domain at once. It does not apply to E2800 or E5700 storage arrays.

== Context

[NOTE]
====
This command is an SMcli command, not a script command. You must run this command from a command line. You cannot run this command from the script editor in the storage management software.
====

* If AutoSupport is enabled, the management software sends both daily AutoSupport messages and weekly AutoSupport messages.
* The management software randomly selects a time of day for both daily and weekly messages and a day of the week for weekly messages. Management software makes all attempts to ensure that no two storage arrays within a management domain sends scheduled AutoSupport messages at the same time.
* You can specify a range (hour-level granularity) of when to send daily and when to send weekly messages for the storage arrays in your management domain.
* For the weekly schedule, you select preferred days of the week for AutoSupport collection and transmission.

== Syntax

----
SMcli -autoSupportSchedule reset | (dailyTime=<startTime>-<endTime>
   dayOfWeek=[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
   weeklyTime=<startTime>-<endTime>)
----

== Parameters

|===
| Parameter| Description
a|
`reset`
a|
Resets and generates new schedules using a 24 hour day and 7 day weeks (Sunday to Saturday) time interval.

a|
`dailyTime `
a|
<``startTime``> - <``endTime``> Specifies the time of day that you want to start and end the collection of AutoSupport data for all storage arrays. The startTime and endTime must be in the form of HH:MM[am\|pm}.

a|
`dayOfWeek `
a|
[Sunday\|Monday\|Tuesday\|Wednesday\|Thursday\|Friday\|Saturday] Specifies the preferred days of the week (Sunday through Saturday) that you want to collect AutoSupport bundle collection data for all storage arrays. The `dayOfWeek` parameter must be surrounded by brackets and separated with a space.

a|
`weeklyTime `
a|
<``startTime``> - <``endTime``> Specifies the time of day that you want to start and end the collection of the AutoSupport bundle collection data for each day of the week that you have selected. The `startTime` and `endTime` must be in the form of HH:MM[am\|pm].

|===

== Minimum Firmware Level

8.25

== Example

----
 SMcli -autoSupportSchedule dailyTime=10:00am-11:00am
dayOfWeek=[Monday Thursday Friday] weeklyTime=2:00am-3:00am
----

`SMcli -autoSupportSchedule dailyTime=10:00am-11:00am dayOfWeek=[Monday Thursday Friday] weeklyTime=2:00am-3:00am`

== Verification

Use the `SMcli -autoSupportSchedule show` command to see the resulting change to the schedule in the management domain.
