---
permalink: wombat/reference_wombat_diagnose_controller_iscsihostport.html
sidebar: sidebar
keywords: 
summary: 'The diagnose controller iscsiHostPort command runs diagnostic tests on the copper cables between iSCSI host interface cards and a controller.'
---
= Diagnose controller iSCSI host cable
:icons: font
:imagesdir: ./media/

[.lead]
The `diagnose controller iscsiHostPort` command runs diagnostic tests on the copper cables between iSCSI host interface cards and a controller.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

You can run diagnostics on a selected port or all ports. The ports must be able to support the cable diagnostics. If the ports do not support cable diagnostics, an error is returned.

== Syntax

----
diagnose controller [(a|b)]
iscsiHostPort ([all] | [portLabel])
testID=cableDiagnostics
----

== Parameters

|===
| Parameter| Description
a|
`controller`
a|
The controller on which you want to run the cable diagnostic test. Valid controller identifiers are `a` or `b`, where `a` is the controller in slot A, and `b` is the controller in slot B. Enclose the controller identifier in square brackets ([ ]). If you do not specify a controller, the storage management software returns a syntax error.
a|
`iscsiHostPort`
a|
The iSCSI host port on which you want to run the diagnostic tests. You can run the diagnostics on all iSCSI host ports, or you can run the diagnostics on a specific iSCSI host port.

See the following for more information:

<<ESERIES-SECTION_ID_ON_CONREFFED_SECTION,"Identifying an iSCSI host port label">>
a|
`testID`
a|
The identifier for the diagnostic test that you want to run. For this diagnostic test, the only choice is `cableDiagnostics`.
|===

== Identifying an iSCSI host port label

You must specify a label for the host port. Follow these steps to specify the host port label:

. If you do not know the port label for the iSCSI host port, run the `show controller` command.
. In the Host interface section of the results, locate the host port you want to select.
+
[NOTE]
====
The port label is the complete value returned for the `Port` field.
====

. Enclose the entire value of the port label in both quotes and square brackets: ["[.code]``portLabel``"]. For example, if the port label is `Ch 2`, specify the iSCSI host port as follows:
+
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
If you are using a Windows command line and the label contains a pipe (|), the character should be escaped (using {caret}); otherwise, it will be interpreted as a command. For example, if the port label is `e0b|0b`, specify the iSCSI host port as follows:
====
+
----
iscsiHostPort[\"e0b^|0b\"]
----

[NOTE]
====
For backward compatibility, the iscsiPortNumber, enclosed by braces [ ] rather than quotes and braces [" "] can still be used for E2700, E5600, or EF560 controllers (and other previous generations of E-Series or EF-Series controllers). For those controllers, valid values for iscsiPortNumber are as follows:

* For controllers with integrated host ports, the numbering is 3, 4, 5, or 6.
* For controllers with host ports on a host interface card only, the numbering is 1, 2, 3, or 4.

An example of the prior syntax is as follows:

----
iscsiHostPort[3]
----

====

== Notes

When you run the cable diagnostic test, the firmware returns the following information:

* Host Port: The port on which the diagnostic test was run.
* HIC: The host interface card associated with this port.
* The date and time the test was run.
* Status:
 ** OK: All of the pairs of cables are good and do not have any faults.
 ** Open: One or more of the four pairs of cables are open.
 ** Short: One or more of the four pairs of cables are shorted.
 ** Incomplete: One or more of the four pairs returned incomplete or invalid test results.
* Length -- The length of the cables are listed in meters and the following information about the cables is returned:
 ** When the cable status is OK, the approximate lengths of the cable pairs are returned. The lengths of the cable pairs are shown as a range (L1-L2), which are the shortest and the longest lengths of the cable pairs.
 ** If the cable status is Open or Short, the approximate distance to the failure in the cable pairs. If there is one failure, the length is reported for that cable pair. If there is more than one failure, the information returned is both the shortest and longest lengths to the failures. The lengths are listed as a range (L1-L2) where L1<L2.
 ** If the cable status is Incomplete, the information returned are the lengths for the shortest and longest cable pairs that the firmware can successfully test. The lengths are listed for the valid cable pairs as a range (L1-L2) where L1<L2.
* Register values for the cable diagnostic registers. The values are in a hexadecimal format:
 ** Two bytes show the combined cable status (four bits per port).
 ** Four two-byte numbers show the length of each channel.

== Minimum firmware level

7.77

8.10 revises the numbering system for iSCSI host ports.
