---
permalink: wombat/reference_wombat_set_asyncmirrorgroup.html
sidebar: sidebar
keywords: 
summary: 'The set asyncMirrorGroup command changes the synchronization settings and warning thresholds that the controller owner of the primary side of the asynchronous mirror group uses when it performs an initial synchronization or resynchronization.'
---
= Set asynchronous mirror group
:icons: font
:imagesdir: ./media/

[.lead]
The `set asyncMirrorGroup` command changes the synchronization settings and warning thresholds that the controller owner of the primary side of the asynchronous mirror group uses when it performs an initial synchronization or resynchronization.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin or Support Admin role.

== Context

Changing the synchronization settings affects the synchronization operations of all mirrored pairs within the asynchronous mirror group.

== Syntax

----
set asyncMirrorGroup [asyncMirrorGroupName]
[volume="repos_xxxx" increaseRepositoryCapacity (repositoryVolume=("repos_xxxx")]
[syncInterval=integer (minutes | hours | days)]
[warningSyncThreshold=integer (minutes | hours | days)]
[warningRecoveryThreshold=integer (minutes | hours | days)]
[userLabel="New_asyncMirrorGroupName"]
[warningThresholdPercent=percentValue]
[role=(primary | secondary)]
[autoResync=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`asyncMirrorGroup`
a|
The name of the asynchronous mirror group that you want to modify. Enclose the asynchronous mirror group name in square brackets ([ ]). If the asynchronous mirror group name has special characters or numbers, you must enclose the name in double quotation marks (" ") inside square brackets.

a|
`volume`
a|
The name of an asynchronous mirror group repository volume for which you want to increase the capacity.

The name of a repository volume is comprised of two parts:

* The term "repos"
* A four-digit numerical identifier that the storage management software assigns to the repository volume name

Enclose the name of the repository volume in double quotation marks (" ").

a|
`syncInterval`
a|
Specify the length of time between automatically sending updates of modified data from the local storage array to the remote storage array. You can specify the length of time in minutes, hours, or days.

a|
`warningSyncThreshold`
a|
Specify the length of time to wait until a warning is triggered for cases in which the synchronization of all of the volumes within the asynchronous mirror group takes longer than the defined time. You can specify the length of time in minutes, hours, or days.

a|
`warningRecoveryThreshold`
a|
Specify the length of time to wait until a warning is triggered when the automatic data update for the point-in-time image on the remote storage array is older than the defined time. Define the threshold from the end of the previous update. You can specify the length of time in minutes, hours, or days.

[NOTE]
====
You must set the Recovery Point Threshold to be twice as large as the synchronization interval threshold.
====

a|
`userLabel`
a|
The new name that you want to give to the asynchronous mirror group. Use this parameter when you want to rename the asynchronous mirror group. Enclose the new asynchronous mirror group name in double quotation marks (" ").
a|
`warningThresholdPercent`
a|
Specify the percent value that determines when a warning is triggered when the capacity of a mirror repository volume reaches the defined percentage. Define the threshold by percentage (%) of the capacity remaining.

a|
`role`
a|
Use this parameter to promote the asynchronous mirror group to a primary role or demote the asynchronous mirror group to a secondary role. To define the asynchronous mirror group as the primary role, set this parameter to `primary`. To define the asynchronous mirror group as the secondary role, set this parameter to `secondary`.
a|
`autoResync`
a|
The settings for automatic resynchronization between the primary volumes and the secondary volumes of an asynchronous mirrored pair within an asynchronous mirror group. This parameter has these values:

* `enabled` -- Automatic resynchronization is turned on. You do not need to do anything further to resynchronize the primary volume and the secondary volume.
* `disabled` -- Automatic resynchronization is turned off. To resynchronize the primary volume and the secondary volume, you must run the `start asyncMirrorGroup` command.

|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

When you use this command, you can specify one or more of the parameters. You do not, however, need to use all of the parameters.

An asynchronous mirror group repository volume is an expandable volume that is structured as a concatenated collection of up to 16 standard volume entities. Initially, an expandable repository volume has only a single volume. The capacity of the expandable repository volume is exactly that of the single volume. You can increase the capacity of an expandable repository volume by attaching additional unused repository volumes to it. The composite expandable repository volume capacity then becomes the sum of the capacities of all of the concatenated standard volumes.

== Minimum firmware level

7.84
