---
permalink: wombat/reference_wombat_stop_snapimage_rollback.html
sidebar: sidebar
keywords: 
summary: 'The stop snapImage rollback command stops a snapshot image rollback operation that was initiated by the start snapImage rollback command.'
---
= Stop snapshot image rollback
:icons: font
:imagesdir: ./media/

[.lead]
The `stop snapImage rollback` command stops a snapshot image rollback operation that was initiated by the `start snapImage rollback` command.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
Canceling a snapshot image rollback operation leaves the base volume in an indeterminate state with potentially invalid or inconsistent data. The related snapshot image volume becomes disabled and unusable.
====

== Syntax

----
stop snapImage [snapCGID:imageID] rollback
----

== Parameter

|===
| Parameter| Description
a|
`snapImage`
a|
The name of the snapshot image for which you want to stop a rollback operation. The name of a snapshot image is comprised of two parts:

* The name of the snapshot group
* An identifier for the snapshot image in the snapshot group

The identifier for the snapshot image can be one of these:

* An integer value that is the sequence number of the snapshot in the snapshot group.
* `NEWEST` -- Use this option when you want to show the latest snapshot image created in the snapshot group.
* `OLDEST` -- Use this option when you want to show the earliest snapshot image created in the snapshot group.

Enclose the snapshot image name in double quotation marks (" ") inside square brackets ([ ]).

|===

== Notes

The name of a snapshot image has two parts separated by a colon (:):

* The identifier of the snapshot group
* The identifier of the snapshot image

For example, if you want to stop a rollback operation for snapshot image 12345 in a snapshot group that has the name snapGroup1, you would use this command:

----
stop snapImage ["snapGroup1:12345"] rollback;
----

To stop a rollback operation for the most recent snapshot image in a snapshot group that has the name snapGroup1, you would use this command:

----
stop snapImage ["snapGroup1:newest"] rollback;
----

== Minimum firmware level

7.83
