---
permalink: wombat/wombat-set-volume-ssdcacheenabled.html
sidebar: sidebar
keywords: 
summary: 'The set volume ssdCacheEnabled command turns on or off caching using the SSD cache feature for a specific volume.'
---
= Set SSD cache for a volume
:icons: font
:imagesdir: ./media/

[.lead]
The `set volume ssdCacheEnabled` command turns on or off caching using the SSD cache feature for a specific volume.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Context

The volume can be one of these:

* Standard volume, identified by either a name or a WWID
* Snapshot volume
* Consistency group snapshot volume

== Syntax applicable to a standard volume

----
set volume ([volumeName] | <"WWID">) ssdCacheEnabled=(TRUE | FALSE)
----

== Syntax applicable to a snapshot volume

----
set snapVolume ["snapVolumeName"] ssdCacheEnabled=(TRUE | FALSE)
----

== Syntax applicable to a consistency group snapshot volume

----
set cgSnapVolume ["cgSnapVolumeName"] ssdCacheEnabled=(TRUE | FALSE)
----

== Parameters

|===
| Parameter| Description
a|
`volume`
a|
The name of the standard volume for which you want to turn on or turn off the SSD cache. Enclose the name of the volume in square brackets ([ ]). If the name of the volume has special characters or numbers, you must enclose the name of the volume in double quotation marks (" ") inside of square brackets ([ ]).

a|
`volume`
a|
The World Wide Identifier (WWID) of the standard volume for which you want to turn on or turn off the SSD cache. Enclose the WWID in double quotation marks (" ") inside angle brackets (< >).
a|
`snapVolume`
a|
The name of the snapshot volume for which you want to turn on or turn off the SSD cache. Enclose the name of snapshot volume in double quotation marks (" ") inside of square brackets ([ ]).
a|
`cgSnapVolume`
a|
The name of the consistency group snapshot volume for which you want to turn on or turn off the SSD cache. Enclose the name of the consistency group snapshot volume in double quotation marks (" ") inside of square brackets ([ ]).
a|
`ssdCacheEnabled`
a|
To turn on SSD cache, set this parameter to `TRUE`. To turn off SSD cache, set this parameter to `FALSE`.
|===

== Notes

You can turn the SSD cache on or off for only one volume at a time.

When you turn off SSD cache for a volume, the SSD cache for that volume is purged.

== Minimum firmware level

7.84
