---
permalink: wombat/wombat-reset-storagearray-sasphybaseline.html
sidebar: sidebar
keywords: 
summary: 'The reset storageArray SASPHYBaseline command resets the SAS physical layer \(SAS PHY\) baseline for all devices, and removes the list of errors from the .csv file.'
---
= Reset storage array SAS PHY baseline
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray SASPHYBaseline` command resets the SAS physical layer (SAS PHY) baseline for all devices, and removes the list of errors from the `.csv` file.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

The `.csv` file is generated when you run the `save storageArray SASPHYCounts` command.

[NOTE]
====
The previous release of the `reset storageArray SASPHYBaseline` command cleared error counts for all devices except the drives. The `reset storageArray SASPHYBaseline` command now resets the SAS PHY baseline for the drives as well as the other devices. All errors are deleted from the `.csv` file.
====

== Syntax

----
reset storageArray SASPHYBaseline
----

== Parameters

None.

== Minimum firmware level

6.10

7.83 resets the SAS PHY baseline for drives.
