---
permalink: commands-a-z/create-storagearray-syslog.html
sidebar: sidebar
keywords: 
summary: 'The create storageArray syslog command allows you to archive audit logs onto an external syslog server. After a connection is established between the storage array and syslog server, audit logs are automatically saved to the syslog server.'
---
= Create storage array syslog configuration
:icons: font
:imagesdir: ./media/

[.lead]
The `create storageArray syslog` command allows you to archive audit logs onto an external syslog server. After a connection is established between the storage array and syslog server, audit logs are automatically saved to the syslog server.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

create storageArray syslog serverAddress="<address>" port=<port> protocol=("udp" | "tcp" | "tls") components=(componentName=("auditLog") ...)
----

== Parameters

|===
| Parameter| Description
a|
serverAddress
a|
Syslog receiver hostname or IP address.
a|
port
a|
Syslog receiver port number.
a|
protocol
a|
Syslog transmission protocol. Acceptable values include udp, tcp, or tls.
a|
components
a|
List of component entries that will be logged to the syslog server. Currently, only audit logs are supported.
a|
componentName
a|
Component name; currently only "auditLog" is supported.
|===

== Minimum firmware level

8.42

== Example

----
SMcli -n Array1 -c "create storageArray syslog
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e
Server Address: 192.168.2.1.com
Port: 514
Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----
