---
permalink: wombat/wombat-set-thin-volume-attributes.html
sidebar: sidebar
keywords: 
summary: 'The set volume command defines the properties for a thin volume.'
---
= Set thin volume attributes
:icons: font
:imagesdir: ./media/

[.lead]
The `set volume` command defines the properties for a thin volume.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

You can use the parameters to define properties for one or more thin volumes.

== Syntax

----
set (volume [volumeName] |
volumes [volumeName1 ... volumeNameN] | volume <"wwID">)
[newCapacity=capacityValue]
[repositoryMaxCapacity=capacityValue]
[repositoryExpansionPolicy=(automatic|manual)]
[warningThresholdPercent=warningThresholdPercentValue]
[addRepositoryCapacity=capacity-spec][hostReportingPolicy=(standard | thin)]
----

== Parameters

|===
| Parameter| Description
a|
`volume`
a|
The name of the volume for which you want to define properties. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the volume name in double quotation marks (" ") inside square brackets.

a|
`volume`
a|
The World Wide Identifier (WWID) of the volume for which you want to define properties. Enclose the WWID in double quotation marks (" ") inside angle brackets (< >).
a|
`volumes`
a|
The names of several volumes for which you want to define properties. All of the volumes will have the same properties. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or consist only of numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`newCapacity`
a|
This parameter increases the virtual capacity of the thin volume. The virtual capacity is the value that the volume will report to a host that is mapped to the volume. Values smaller or equal to the existing capacity will cause an error. Size is defined in units of `bytes`, `KB`, `MB`, `GB`, or `TB`.

The minimum virtual capacity is 32 MB.

The maximum virtual capacity is 63 TB.

a|
`repositoryMaxCapacity`
a|
This parameter sets the maximum capacity of the repository volume. The value must not be smaller that the physical capacity of the repository volume. If the new value results in a reduction in capacity to a level below the warning threshold, the command will produce an error.
[NOTE]
====
The command `repositoryMaxCapacity` works with `repositoryExpansionPolicy=automatic`.
====

a|
`repositoryExpansionPolicy`
a|
This parameter sets the expansion policy to `automatic` or `manual`.When you change the policy from `automatic` to `manual`, the maximum capacity value (quota) changes to the physical capacity of the repository volume.
a|
`warningThresholdPercent`
a|
The percentage of thin volume capacity at which you receive a warning alert that the thin volume is nearing full. Use integer values. For example, a value of 70 means 70 percent.

Valid values are from 1 to 100.

Setting this parameter to 100 disables warning alerts.

a|
`addRepositoryCapacity`
a|
This parameter allocates capacity from the free extent of the disk pool. If insufficient space is available the command fails.
[NOTE]
====
The command `addRepositoryCapacity` works with `repositoryExpansionPolicy=manual`.
====

a|
`hostReportingPolicy`
a|
This parameter changes the way in which the thin volume is reported to the host. Valid values are `standard` or `thin`.
|===

== Notes

When you use this command, you can specify one or more of the optional parameters.

The following table lists the capacity limits for a thin volume.

|===
| Type of Capacity| Size
a|
Minimum virtual capacity
a|
32 MB
a|
Maximum virtual capacity
a|
63 TB
a|
Minimum physical capacity
a|
4 GB
a|
Maximum physical capacity
a|
64 TB
|===
Thin volumes support all of the operations that standard volumes do with the following exceptions:

* You cannot change the segment size of a thin volume.
* You cannot enable the pre-read redundancy check for a thin volume.
* You cannot use a thin volume as the target volume in a volume copy.
* You cannot use a thin volume in a Synchronous Mirroring operation.

If you want to change a thin volume to a standard volume, use the volume copy operation to create a copy of the thin volume. The target of a volume copy is always a standard volume.

== Minimum firmware level

7.83
