---
permalink: wombat/wombat-set-volume-logicalunitnumber.html
sidebar: sidebar
keywords: 
summary: 'The set volume logicalUnitNumber command defines the logical unit number \(LUN\) or namespace ID \(NSID\) mapping between a volume and a host or host group.'
---
= Set volume mapping
:icons: font
:imagesdir: ./media/

[.lead]
The `set volume logicalUnitNumber` command defines the logical unit number (LUN) or namespace ID (NSID) mapping between a volume and a host or host group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This command is applicable to volumes in either a volume group or disk pool.

[NOTE]
====
You cannot use this command for a snapshot volume that is used in online volume copy.
====

== Syntax

----
set (volume [volumeName] | volume <"wwID"> | accessVolume)
logicalUnitNumber=lun
(host="hostName" |
hostGroup=("hostGroupName" | defaultGroup)
----

== Parameter

|===
| Parameter| Description
a|
`volume`
a|
The name of the volume for which you want to define the logical unit number. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the volume name in double quotation marks (" ") inside square brackets.

a|
`volume`
a|
The World Wide Identifier (WWID) of the volume for which you want to define the logical unit number. Enclose the WWID in double quotation marks (" ") inside angle brackets (< >).
a|
`accessVolume`
a|
The logical unit number for the access volume. The logical unit number is the only property that you can set for the access volume.

a|
`logicalUnitNumber`
a|
The logical unit number or namespace ID that you want to use to map to a specific host. This parameter also assigns the host to a host group.

[NOTE]
====
The logical unit number or namespace ID you specify must not already be in use, and must be within the range supported by the host Operating System. There will be no error if you map the volume to a logical unit number or namespace ID not supported by the host, but the host won't be able to access the volume.
====

a|
`host`
a|
The name of the host to which the volume is mapped. Enclose the host name in double quotation marks (" ").

a|
`hostGroup`
a|
The name of the host group to which the volume is mapped. Enclose the host group name in double quotation marks (" "). `defaultGroup` is the host group that contains the host to which the volume is mapped.

|===

== Notes

A host group is an optional topological element that you can define if you want to designate a collection of hosts that share access to the same volumes. The host group is a logical entity. Define a host group only if you have two or more hosts that can share access to the same volumes.

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

The access volume is the volume in a SAN environment that is used for in-band communication between the storage management software and the storage array controller. This volume uses a LUN or NSID address and consumes 20 MB of storage space that is not available for application data storage. An access volume is required only for in-band managed storage arrays. If you specify the `accessVolume` parameter, the only property you can set is the `logicalUnitNumber` parameter.

== Minimum firmware level

7.83 adds snapshot volume for disk pools.
