---
permalink: commands-a-z/set-consistency-group-attributes.html
sidebar: sidebar
keywords: 
summary: 'The set consistencyGroup command defines the properties for a snapshot consistency group.'
---
= Set consistency group attributes
:icons: font
:imagesdir: ./media/

[.lead]
The `set consistencyGroup` command defines the properties for a snapshot consistency group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
set consistencyGroup ["consistencyGroupName"]
[userLabel="consistencyGroupName"]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=percentValue]
[autoDeleteLimit=numberOfSnapImages]
[rollbackPriority=(lowest | low | medium | high | highest)]
----

== Parameters

|===
| Parameter| Description
a|
`consistencyGroupName`
a|
The name of the consistency group for which you are setting properties. Enclose the consistency group name in double quotation marks (" ") inside square brackets ([ ]).
a|
`userLabel`
a|
The new name that you want to give to the snapshot consistency group. Enclose the new consistency group name in double quotation marks (" ").
a|
`repositoryFullPolicy`
a|
How you want snapshot processing to continue if the snapshot repository volumes are full. You can choose to fail writes to the base volume (`failBaseWrites`) or delete (purge) the snapshot images (`purgeSnapImages`). The default action is `purgeSnapImages`.
a|
`repositoryFullLimit`
a|
The percentage of repository capacity at which you receive a warning that the snapshot repository volume is nearing full. Use integer values. For example, a value of 70 means 70 percent. The default value is 75.

a|
`autoDeleteLimit`
a|
Each consistency group can be configured to perform automatic deletion of its snapshot images to keep the total number of snapshot images in the snapshot group at or below a designated level. When this option is enabled, then any time a new snapshot image is created in the snapshot group, the system automatically deletes the oldest snapshot image in the group to comply with the limit value. This action frees repository capacity so it can be used to satisfy ongoing copy-on-write requirements for the remaining snapshot images.

a|
`rollBackPriority`
a|
The priority for rollback operations for a consistency group while the storage array is operational. Valid values are `highest`, `high`, `medium`, `low`, or `lowest`.

|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

When you use this command, you can specify one or more of the parameters. You do not, however, need to use all of the parameters.

The rollback priority defines the amount of system resources that should be allocated to the rollback operation at the expense of system performance. A value of `high` indicates that the rollback operation is prioritized over all other host I/O. A value of `low` indicates that the rollback operation should be performed with minimal impact to host I/O.

== Auto delete

You can configure each snapshot group to perform automatic deletion of its snapshot images to keep the total number of snapshot images in the snapshot group at or below a maximum number of images. When the number of snapshot images in the snapshot group is at the maximum limit, the `autoDeleteLimit` parameter automatically deletes snapshot images whenever a new snapshot image is created in the snapshot group. The `autoDeleteLimit` parameter deletes the oldest snapshot images in the snapshot group until the maximum number of images defined with the parameter is met. Deleting snapshot images in this way frees repository capacity so it can be used to satisfy ongoing copy-on-write requirements for the remaining snapshot images.

== Minimum firmware level

7.83
