---
permalink: commands-a-z/set-iscsiinitiator.html
sidebar: sidebar
keywords: 
summary: 'The set iscsiInitiator command sets the attributes for an iSCSI initiator.'
---
= Set iSCSI initiator
:icons: font
:imagesdir: ./media/

[.lead]
The `set iscsiInitiator` command sets the attributes for an iSCSI initiator.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

[NOTE]
====
This command is deprecated and is replaced by the xref:wombat-set-initiator.adoc[Set initiator] command.
====

== Syntax

----
set iscsiInitiator (["initiatorUserLabel"] | <"iscsiInitiatorName">)
(userLabel="newName" |
host="newHostName" |
chapSecret="newSecurityKey")
----

== Parameters

|===
| Parameter| Description
a|
`initiatorUserLabel`
a|
The iscsi Initiator user label of the iSCSI initiator for which you want to set attributes. Enclose the iSCSI initiator user label in double quotation marks (" ") inside square brackets ([ ]).
[NOTE]
====
Begin the initiator user label with the host name to which the host port is connected. Because there can be more than one host port identifier on a host, use a unique suffix for the host port ID. If the host name is `ICTM1590S02H1` the initiator label appears as follows:
====

----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----

a|
`iscsiInitiatorName`
a|
The name of the initiator for which you want to set attributes. Enclose the `iscsiInitiatorName` in double quotation marks (" ") inside angle brackets (< >).
[NOTE]
====
The `iscsiInitiatorName` is the iSCSI Qualified Name (iqn). An example:
====

----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----

a|
`userLabel`
a|
The new user label that you want to use for the iSCSI initiator. Enclose the new user label in double quotation marks (" ").
[NOTE]
====
A best practice is to begin the initiator user label with the host name to which the host port is connected. Because there can be more than one host port identifier on a host, use a unique suffix for the host port ID. If the host name is `ICTM1590S02H1` then an example of the initiator user label is shown below:
====

----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----

a|
`host`
a|
The name of the new host to which the host port is connected. Enclose the host name in double quotation marks (" "). An example is shown below:

----
["ICTM1590S02H2"]
----

a|
`chapSecret`
a|
The security key that you want to use to authenticate a peer connection. Enclose the security key in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

Challenge Handshake Authentication Protocol (CHAP) is a protocol that authenticates the peer of a connection. CHAP is based upon the peers sharing a _secret_. A secret is a security key that is similar to a password.

Use the `chapSecret` parameter to set up the security keys for initiators that require a mutual authentication. The CHAP secret must be between 12 characters and 57 characters. This table lists the valid characters.

|===
a|
Space
a|
!
a|
"
a|
#
a|
$
a|
%
a|
&
a|
'
a|
(
a|
)
a|
*
a|
a|
,
a|
-
a|
.
a|
/
a|
0
a|
1
a|
2
a|
3
a|
4
a|
5
a|
6
a|
7
a|
8
a|
9
a|
:
a|
;
a|
<
a|
=
a|
>
a|
?
a|
@
a|
A
a|
B
a|
C
a|
D
a|
E
a|
F
a|
G
a|
H
a|
I
a|
J
a|
K
a|
L
a|
M
a|
N
a|
O
a|
P
a|
Q
a|
R
a|
S
a|
T
a|
U
a|
V
a|
W
a|
X
a|
Y
a|
Z
a|
[
a|
 a|
]
a|

a|
_
a|
'
a|
a
a|
b
a|
c
a|
d
a|
e
a|
f
a|
g
a|
h
a|
i
a|
j
a|
k
a|
l
a|
m
a|
n
a|
o
a|
p
a|
q
a|
r
a|
s
a|
t
a|
u
a|
v
a|
w
a|
x
a|
y
a|
z
a|
{
a|
\|
a|
}
a|
~
a|
 
|===

== Minimum firmware level

7.10

8.41 This command is deprecated.
