---
permalink: wombat/wombat-set-drivechannel.html
sidebar: sidebar
keywords: 
summary: 'The set driveChannel command defines how the drive channel performs.'
---
= Set drive channel status
:icons: font
:imagesdir: ./media/

[.lead]
The `set driveChannel` command defines how the drive channel performs.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax

----
set driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)]
status=(optimal | degraded)
----

== Parameters

|===
| Parameter| Description
a|
`driveChannel`
a|
The identifier number of the drive channel for which you want to set the status. Valid drive channel values are `1`, `2`, `3`, `4`, `5`, `6`, `7`, or `8`. Enclose the drive channel number in square brackets ([ ]).
a|
`status`
a|
The condition of the drive channel. You can set the drive channel status to `optimal` or `degraded`.
|===

== Notes

Use the `optimal` option to move a degraded drive channel back to the Optimal state. Use the `degraded` option when the drive channel is experiencing problems, and the storage array requires additional time for data transfers.

== Minimum firmware level

6.10

7.15 adds the update to the drive channel identifier.
