---
permalink: commands-a-z/reset-drive.html
sidebar: sidebar
keywords: 
summary: 'The reset drive command power cycles a drive in a volume group or a disk pool to aid in the recovery of a drive that is exhibiting inconsistent or non-optimal behavior.'
---
= Reset drive
:icons: font
:imagesdir: ./media/

[.lead]
The `reset drive` command power cycles a drive in a volume group or a disk pool to aid in the recovery of a drive that is exhibiting inconsistent or non-optimal behavior.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

By power cycling a drive, you can clear some errors that cause inconsistent or non-optimal behavior. This avoids replacing a drive when it is experiencing only a transient, non-fatal error, and the drive can remain operational. Resetting a drive in this way reduces disruptions and avoids replacing a drive.

If the problem cannot be corrected by power cycling the drive, the data is copied from the drive and the drive is powered down for replacement.

[NOTE]
====
This command cannot be used for SSD drives manufactured by Pliant. Use the `show storageArray profile` command or the `show drive` command to display the manufacturer of the drive(s).
====

== Syntax

----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----

== Parameters

|===
| Parameter| Description
a|
`drive`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`drive`
a|
The World Wide Identifier (WWID) of the drive that you want to replace. Enclose the WWID in double quotation marks (" ") inside angle brackets (< >).
|===

== Notes

The `drive` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0` , and specify the ID of the slot in which a drive resides.

After power cycling the drive, the controller must verify the drive to be functional before it can be placed back into use. If the drive cannot be verified it is marked as a failed drive. Power cycling a failed drive requires global hot spare drives and full copy back to a replacement drive after it is brought into service.

Failed drives cannot be reset by a power cycle more than once in a 24 hour period, and in some cases cannot be reset more than once. Thresholds and counters for drive power cycles are kept in persistent storage, and are included in state capture data. Informational events are logged when a drive is power cycled.

== Minimum firmware level

8.20
