---
permalink: wombat/wombat-autoconfigure-storagearray-hotspares.html
sidebar: sidebar
keywords: 
summary: 'The autoConfigure storageArray hotSpares command automatically defines and configures the hot spares in a storage array. You can run this command at any time. This command provides the best hot spare coverage for a storage array.'
---
= Autoconfigure storage array hot spares
:icons: font
:imagesdir: ./media/

[.lead]
The `autoConfigure storageArray hotSpares` command automatically defines and configures the hot spares in a storage array. You can run this command at any time. This command provides the best hot spare coverage for a storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
autoConfigure storageArray hotSpares
----

== Parameters

None.

== Notes

When you run the `autoconfigure storageArray hotSpares` command, the controller firmware determines the number of hot spares to create based on the total number and type of drives in the storage array. For SAS drives, the controller firmware creates one hot spare for the storage array and one additional hot spare for every 60 drives in the storage array.

== Minimum firmware level

6.10
