---
permalink: wombat/wombat-set-storagearray-controllerhealthimageallowoverwrite.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray controllerHealthImageAllowOverWrite command sets a flag on a controller to allow a new controller health image to overwrite an existing controller health image on storage arrays that support the controller health image feature.'
---
= Set storage array controller health image allow overwrite
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray controllerHealthImageAllowOverWrite` command sets a flag on a controller to allow a new controller health image to overwrite an existing controller health image on storage arrays that support the controller health image feature.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the storage array does not support the controller health image feature, the command returns an error.

[NOTE]
====
With firmware version 8.20 the `coreDumpAllowOverWrite` parameter is replaced with the `controllerHealthImageAllowOverWrite` parameter.
====

== Syntax

----
set storageArray controllerHealthImageAllowOverWrite
----

== Parameters

None.

== Notes

When the controller health image is retrieved, the `allow overwrite` flag is set. If the controller health image is not retrieved, the image expires in 48 hours, after which the `allow overwrite` flag is set. When you use the `set storageArray controllerHealthImageAllowOverWrite` command to set the `allow overwrite` flag, the 48-hour expiration is waived as if the image had been retrieved.

== Minimum firmware level

7.86

8.20 replaces the `coreDumpAllowOverWrite` parameter with the `controllerHealthImageAllowOverWrite` parameter.
