---
permalink: commands-a-z/reset-storagearray-autosupport-schedule.html
sidebar: sidebar
keywords: 
summary: 'The reset storageArray autoSupport schedule command resets the daily and weekly times and days of the week that AutoSupport messages are sent back to the random values generated by the management software.'
---
= Reset AutoSupport message collection schedule (for individual E2800 or E5700 arrays)
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray autoSupport schedule` command resets the daily and weekly times and days of the week that AutoSupport messages are sent back to the random values generated by the management software.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

* The management software randomly selects a time of day for both daily and weekly messages and a day of the week for weekly messages.
* The management software makes all attempts to ensure that no two storage arrays within a management domain send scheduled AutoSupport messages at the same time.

== Syntax

----
reset storageArray autoSupport schedule
----

== Parameters

None.

== Examples

----

SMcli -n Array1 -c "reset storageArray autoSupport schedule;"

SMcli completed successfully.
----

== Verification

Use the `show storageArray autoSupport` command to see the resulting change to the schedule.

== Minimum firmware level

8.40
