---
permalink: wombat/wombat-reset-storagearray-ibstatsbaseline.html
sidebar: sidebar
keywords: 
summary: 'The reset storageArray ibStatsBaseline command resets the InfiniBand statistics baseline to 0 for the storage array.'
---
= Reset storage array InfiniBand statistics baseline
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray ibStatsBaseline` command resets the InfiniBand statistics baseline to 0 for the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

[NOTE]
====
This command is deprecated and is replaced by the xref:wombat-reset-storagearray-hostportstatisticsbaseline.adoc[Reset storage array host port statistics baseline] command.
====

== Syntax

----
reset storageArray ibStatsBaseline
----

== Parameters

None.

== Notes

This command does not actually reset the raw counts maintained in the hardware and firmware. Instead, the firmware creates a snapshot of the current counter values and uses these values to report differences in the counts when the statistics are retrieved. The new baseline time is applied to both controllers so that the controller counts are synchronized with each other. If one controller resets without the other controller resetting, the counters are no longer synchronized. The client becomes aware that the controllers are not synchronized because the timestamp data reported along with the statistics is not the same for both controllers.

== Minimum firmware level

7.10

8.41 This command is deprecated.
