---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip

sidebar:
  entries:
  - title: SANtricity CLI docs
    url: /index.html
  - title: What's new
    url: /whats-new.html
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: E-Series
  repo: e-series-family
