---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip

sidebar:
  entries:
  - title: SANtricity CLI docs
    url: /index.html
  - title: What's new
    url: /whats-new.html
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: Legal notices
    url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: CLI overview
          url: get-started/overview-format-commands.html
        - title: CLI command structure
          url: get-started/structure-of-a-cli-command.html
    - title: E-Series docs
      links:
        - title: E-Series systems docs
          url: https://docs.netapp.com/us-en/e-series/index.html
        - title: SANtricity System Manager 11.8
          url: https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html
        - title: SANtricity Unified Manager 6
          url: https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html
    - title: Tools & support
      links:
        - title: NetApp Interoperability Matrix
          url: http://mysupport.netapp.com/matrix/
        - title: NetApp Knowledge Base
          url: https://kb.netapp.com/
        - title: Active IQ (login required)
          url: https://activeiq.netapp.com/?source=aiqnsspage
        - title: E-Series/SANtricity downloads (login required)
          url: https://mysupport.netapp.com/site/downloads#E
product-family:
  name: E-Series
  repo: e-series-family
