---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip

sidebar:
  entries:
  - title: Home
    url: /index.html
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: Legal notices
    url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: get-started/changes-in-the-cli-and-script-commands-in-this-release.html
        - title: CLI overview
          url: get-started/overview-format-commands.html
        - title: CLI command structure
          url: get-started/structure-of-a-cli-command.html
    - title: Online help
      links:
        - title: SANtricity System Manager 11.7
          url: https://docs.netapp.com/ess-11/topic/com.netapp.doc.ssm-sam-117/home.html
        - title: SANtricity Unified Manager 5
          url: https://docs.netapp.com/ess-11/topic/com.netapp.doc.ssm-uni-5/home.html
    - title: Something here
      links:
          - title: Something here
            url:
    - title: Something here
      links:
          - title: Something here
            url:
    - title: Something here
      links:
        - title: Something here
          url:
    - title: Tools & support
      links:
        - title: NetApp Interoperability Matrix
          url: http://mysupport.netapp.com/matrix/
        - title: NetApp Knowledge Base
          url: https://kb.netapp.com/
        - title: Active IQ (login required)
          url: https://activeiq.netapp.com/?source=aiqnsspage
        - title: E-Series/SANtricity downloads (login required)
          url: https://mysupport.netapp.com/site/downloads#E
