---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip

sidebar:
  entries:
  - title: Home
    url: /index.html
  - section: get-started
  - section: commands-a-z
  - section: commands-category
  - title: Legal notices
    url: /legal-notices.html
