---
permalink: reference_wombat_stop_cgsnapimage_rollback.html
sidebar: sidebar
keywords: 
summary: 'The stop cgSnapImage rollback command stops a rollback operation to member base volumes in a snapshot consistency group.'
---
= Stop consistency group snapshot rollback
:icons: font
:imagesdir: ./media/

[.lead]
The `stop cgSnapImage rollback` command stops a rollback operation to member base volumes in a snapshot consistency group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
Canceling a consistency group snapshot rollback operation leaves the base volume in an indeterminate state with potentially invalid or inconsistent data. The related consistency group snapshot volume becomes disabled and unusable.
====

== Syntax

----
stop cgSnapImage["snapCGID:imageID"] rollback
memberVolumeSet ("memberVolumeName1" ... "memberVolumeNamen")
----

== Parameter

|===
| Parameter| Description
a|
`cgSnapImage`
a|
The name of the consistency group snapshot image for which you want to stop a rollback operation. The name of a snapshot image is comprised of two parts:

* The name of the snapshot group
* An identifier for the snapshot image in the snapshot group

The identifier for the snapshot image can be one of these:

* An integer value that is the sequence number of the snapshot in the snapshot group.
* `NEWEST` -- Use this option when you want to show the latest snapshot image created in the snapshot group.
* `OLDEST` -- Use this option when you want to show the earliest snapshot image created in the snapshot group.

Enclose the snapshot image name in double quotation marks (" ") inside square brackets ([ ]).

a|
`memberVolumeSet`
a|
The name of one or more member base volumes in a consistency group that you want to stop a rollback operation. Enclose each member base volume name in double quotation marks (" ") inside parentheses.

You can enter more than one member base volume name. Enclose all of the member base volume names in one set of square brackets ([ ]). Enclose each member base volume name in double quotation marks (" "). Separate each member base volume name with a space.

When the `memberVolumeSet` parameter is not used stopping the rollback process applies to all member volumes of the consistency group.

|===

== Notes

The name of a snapshot image has two parts separated by a colon (:):

* The identifier of the snapshot group
* The identifier of the snapshot image

For example, if you want to stop a roll back operation for the newest snapshot image in an entire consistency group that has the name CG1, you would use this command:

----
stop cgSnapImage ["CG1:newest"] rollback;
----

To stop a roll back operation for the snapshot image 12345 for base volume members memVol1, memVol2, and memVol3 in a consistency group that has the name CG2, you would use this command:

----
stop cgSnapImage ["CG2:12345"] rollback memberVolumeset=("memVol1 memVol2 memVol3");
----

== Minimum firmware level

7.83
