---
permalink: reference_wombat_disable_storagearray_externalkeymanagement_file.html
sidebar: sidebar
keywords: 
summary: 'The disable storageArray externalKeyManagement file command disables external security key management for a storage array that has Full Disk Encryption drives.'
---
= Disable external security key management
:icons: font
:imagesdir: ./media/

[.lead]
The `disable storageArray externalKeyManagement file` command disables external security key management for a storage array that has Full Disk Encryption drives.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----
disable storageArray externalKeyManagement
file="fileName"
passPhrase="passPhraseString"
saveFile=(TRUE | FALSE)
----

== Context

[NOTE]
====
This command enables internal key management as the alternate form of Drive Security.
====

[NOTE]
====
This command applies only to external key management.
====

== Parameters

|===
| Parameter| Description
a|
`file`
a|
The file path and the file name where the internal security key file is stored. For example:

----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----

[NOTE]
====
The file name must have an extension of `.slk`.
====

a|
`passPhrase`
a|
A character string that encrypts the security key so that you can store the security key in an external file.
a|
`saveFile`
a|
Verifies and saves the security key to a file. Set to `FALSE` to not save and verify the security key to a file. The default value is `TRUE`.
|===

== Notes

Your pass phrase must meet these criteria:

* Must be between eight and 32 characters long.
* No whitespace.
* Must contain at least one uppercase letter.
* Must contain at least one lowercase letter.
* Must contain at least one number.
* Must contain at least one non-alphanumeric character, for example, < > @ +.

[NOTE]
====
If your pass phrase does not meet these criteria, you will receive an error message.
====

== Minimum firmware level

8.40

8.70 adds the `saveFile` parameter.
