---
permalink: reference_wombat_show_volumecopy.html
sidebar: sidebar
keywords: 
summary: 'The show volumeCopy command returns information about volume copy operations.'
---
= Show volume copy
:icons: font
:imagesdir: ./media/

[.lead]
The `show volumeCopy` command returns information about volume copy operations.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

This command returns this information about volume copy operations:

* The copy status
* The start time stamp
* The completion time stamp
* The copy priority
* The source volume World Wide Identifier (WWID) or the target volume WWID
* The target volume Read-Only attribute setting

You can retrieve information about a specific volume copy pair or all of the volume copy pairs in the storage array. This command is valid for snapshot volume copy pairs.

== Syntax

----
show volumeCopy (allVolumes | source ["sourceName"] |
target ["targetName"])
----

== Parameters

|===
| Parameter| Description
a|
`allVolumes`
a|
The setting to return information about volume copy operations for all of the volume copy pairs.
a|
`source`
a|
The name of the source volume about which you want to retrieve information. Enclose the source volume name in double quotation marks (" ") inside of square brackets ([ ]).
a|
`target`
a|
The name of the target volume about which you want to retrieve information. Enclose the target volume name in double quotation marks (" ") inside of square brackets ([ ]).
|===
