---
permalink: reference_wombat_delete_diskpool.html
sidebar: sidebar
keywords: 
summary: 'The delete diskPool command deletes a disk pool.'
---
= Delete disk pool
:icons: font
:imagesdir: ./media/

[.lead]
The `delete diskPool` command deletes a disk pool.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
*Possible damage to the storage array configuration* -- All of the data in the disk pool is lost as soon as you run this command.
====

Depending on your version of the storage management software, this command also deletes all of the volumes in the disk pool. If your version of the storage management software does not support automatic deletion of the volumes, you can force the deletion of the disk pool and volumes.

== Syntax

----
delete diskPool [diskPoolName]
[force=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`diskPoolName`
a|
The name of the disk pool that you want to delete. Enclose the disk pool name in square brackets ([ ]). If the disk pool name contains special characters or consists only of numbers, you must enclose the name in double quotation marks (" ") inside square brackets.
a|
`force`
a|
This parameter forces the deletion of volumes if your storage management software does not support automatic deletion of the volumes in the disk pool. To force the deletion of a disk pool and the volumes that it contains, set this parameter to `TRUE`. The default is `FALSE`.

|===

== Notes

Each disk pool name must be unique. You can use any combination of alphanumeric characters, underscore (_), hyphen(-), and pound (#) for the user label. User labels can have a maximum of 30 characters.

== Minimum firmware level

7.83
