---
permalink: reference_wombat_recreate_storagearray_securitykey.html
sidebar: sidebar
keywords: 
summary: 'The recreate storageArray securityKey command regenerates a storage array security key for use with the external security key management feature.'
---
= Re-create external security key
:icons: font
:imagesdir: ./media/

[.lead]
The `recreate storageArray securityKey` command regenerates a storage array security key for use with the external security key management feature.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command applies only to external key management.
====

== Syntax

----
recreate storageArray securityKey
passPhrase="passPhraseString"
file="fileName"
----

== Parameters

|===
| Parameter| Description
a|
`passPhrase`
a|
A character string that encrypts the security key so that you can store the security key in an external file. Enclose the pass phrase in double quotation marks (" ").
a|
`file`
a|
The file path and the file name that has the security key. For example:

----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----

[NOTE]
====
The file name must have an extension of `.slk`.
====

|===

== Notes

Your pass phrase must meet these criteria:

* The pass phrase must be between eight and 32 characters long.
* The pass phrase must contain at least one uppercase letter.
* The pass phrase must contain at least one lowercase letter.
* The pass phrase must contain at least one number.
* The pass phrase must contain at least one non-alphanumeric character, for example, < > @ +.

[NOTE]
====
If your pass phrase does not meet these criteria, you will receive an error message.
====

== Minimum firmware level

7.70
