---
permalink: reference_wombat_start_drivechannel_locate.html
sidebar: sidebar
keywords: 
summary: 'The start driveChannel locate command identifies the drive trays that are connected to a specific drive channel by turning on the indicator lights for the drive tray that is connected to the drive channel.'
---
= Start drive channel locate
:icons: font
:imagesdir: ./media/

[.lead]
The `start driveChannel locate` command identifies the drive trays that are connected to a specific drive channel by turning on the indicator lights for the drive tray that is connected to the drive channel.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

Use the `stop driveChannel locate` command to turn off the indicator lights on the drive tray.

== Syntax

----
start driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] locate
----

== Parameter

|===
| Parameter| Description
a|
`driveChannel`
a|
The identifier number of the drive channel that you want to locate. Valid values for the identifier number for the drive channel are `1`, `2`, `3`, `4`, `5`, `6`, `7`, or `8`. Enclose the drive channel identifier number in square brackets ([ ]).
|===

== Minimum firmware level

6.10

7.15 adds an update to the drive channel identifier.
