---
permalink: reference_wombat_reset_storagearray_hostportstatisticsbaseline.html
sidebar: sidebar
keywords: 
summary: 'The reset storageArray hostPortStatisticsBaseline command resets the storage array host port statistics baseline.'
---
= Reset storage array host port statistics baseline
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray hostPortStatisticsBaseline` command resets the storage array host port statistics baseline.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

[NOTE]
====
This command replaces the deprecated xref:reference_wombat_reset_storagearray_ibstatsbaseline.adoc[Reset storage array Infiniband statistics baseline], xref:reference_wombat_reset_storagearray_iscsistatsbaseline.adoc[Reset storage array iSCSI baseline], and xref:reference_wombat_reset_storagearray_iserstatsbaseline.adoc[Reset storage array iSER baseline] commands.
====

== Syntax

----

reset storageArray hostPortStatisticsBaseline type=(ISCSI| ISER | SRP | NVMEOF)
----

== Parameters

|===
| Parameter| Description
a|
`type`
a|
Allows you to indicate which statistics type to collect. Valid choices are:``ISCSI``, `ISER`, `SRP`, and `NVMEOF`.
|===

== Minimum firmware level

8.41
