---
permalink: reference_wombat_delete_snapvolume.html
sidebar: sidebar
keywords: 
summary: 'The delete snapVolume command deletes a snapshot volume and optionally the associated snapshot repository members.'
---
= Delete snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `delete snapVolume` command deletes a snapshot volume and optionally the associated snapshot repository members.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
You cannot use this command for snapshot images involved in online volume copy.
====

== Syntax

----
delete snapVolume ["snapVolumeName"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`snapVolume`
a|
The name of the snapshot volume that you want to delete. Enclose the snapshot volume name in double quotation marks (" ") inside square brackets ([ ]).
a|
`deleteRepositoryMembers`
a|
The parameter to save or delete the repository members. To save the repository members, set this parameter to `FALSE`. To delete the repository members, set this parameter to `TRUE`. The default value is `TRUE`. If you do not use this parameter, the repository members are automatically deleted.
|===

== Minimum firmware level

7.83
