---
permalink: reference_wombat_show_volume.html
sidebar: sidebar
keywords: 
summary: 'The show volume command returns the expansion history or the consumed capacity for the specified thin volume or volumes.'
---
= Show thin volume
:icons: font
:imagesdir: ./media/

[.lead]
The `show volume` command returns the expansion history or the consumed capacity for the specified thin volume or volumes.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Syntax

----
show (allVolumes | volume [volumeName] |
volumes [volumeName1 ... volumeNameN])
(consumedCapacity |
(expansionHistory [file=fileName]))
----

== Parameters

|===
| Parameter| Description
a|
`allVolumes`
a|
This parameter returns information about all of the thin volumes in the storage array.
a|
`volume`
a|
The name of a thin volume for which you are retrieving information. Enclose the thin volume name in square brackets ([ ]). If the thin volume name has special characters or numbers, you must enclose the thin volume name in double quotation marks (" ") inside square brackets.

a|
`volumes`
a|
The names of several thin volumes for which you want to retrieve information. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`consumedCapacity`
a|
The setting to return a concise list of information about the consumed capacity of the thin volumes.
a|
`expansionHistory`
a|
The setting to return a concise list of information about the expansion history of the thin volumes.
a|
`file`
a|
The `file` parameter specifies a file to log the output of the `expansionHistory` parameter. The `file` is valid only when used with the `expansionHistory` parameter. An invalid file name causes the command to fail.

|===

== Notes

With the `expansionHistory` parameter, the command returns information similar to the example shown below.

|===
a|

----
Thin volume name: volume-nameRepository volume Name: REPOS_NNNN
----

a|

----
Logged Time
----

a|

----
Expansion Type
----

a|

----
Start Capacity
----

a|

----
End Capacity
----

a|

----
MM/DD/YYYY HH:MM:SS
----

a|

----
Manual|Automatic
----

a|

----
NNNNNNNN bytes
----

a|

----
NNNNNNNN bytes
----

|===
With the `consumedCapacity` parameter, the command returns information similar to the example shown below.

|===
a|

----
Volume
----

a|

----
Provisioned Capacity
----

a|

----
Consumed Capacity
----

a|

----
Quota
----

a|

----
% Prov.Consumed
----

a|
`volumeName`
a|

----
500.000 GB
----

a|

----
230.000 GB
----

a|

----
700.000 GB
----

a|

----
46%
----

|===

== Minimum firmware level

7.83
