---
permalink: reference_wombat_set_auditlog.html
sidebar: sidebar
keywords: 
summary: 'The set auditLog command configures the audit log settings.'
---
= Set audit log settings
:icons: font
:imagesdir: ./media/

[.lead]
The `set auditLog` command configures the audit log settings.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

set auditLog (logLevel={all | writeOnly} |
    fullPolicy={overwrite | preventSystemAccess} |
    maxRecords=n | warningThreshold=n)
----

== Parameters

|===
| Parameter| Description
a|
`logLevel`
a|
Allows you to specify the level of logging. Valid choices are: ``all``and `writeOnly`. The default value is `writeOnly`.
a|
`fullPolicy`
a|
Allows you to specify the policy when the log is full. Valid choices are: ``overwrite``and `preventSystemAccess`.
a|
`maxRecords`
a|
Allows the user to specify the maximum number of records to be stored where `n` is an integer starting at 30000 and ending at 50000.
a|
`warningThreshold`
a|
Allows you to specify the percentage at which a warning alert will be sent to indicate that the audit log is nearing full when full policy is set to `preventSystemAccess`. Use integer values between 0 to 100. Setting this parameter to 0 (zero) disables the warning alerts.
|===

== Examples

----

SMcli -n Array1 -c "set auditLog logLevel=writeOnly fullPolicy=preventSystemAccess maxRecords=40000 warningThreshold=90;"

SMcli completed successfully.
----

== Minimum firmware level

8.40
