---
permalink: reference_wombat_check_volume_parity.html
sidebar: sidebar
keywords: 
summary: 'The check volume parity command checks a volume for parity and media errors, and then writes the results of the check to a file.'
---
= Check volume parity
:icons: font
:imagesdir: ./media/

[.lead]
The `check volume parity` command checks a volume for parity and media errors, and then writes the results of the check to a file.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
check volume [volumeName] parity
[parityErrorFile=filename]
[mediaErrorFile=filename]
[priority=(highest | high | medium | low | lowest)]
[startingLBA=LBAvalue]
[endingLBA=LBAvalue]
[verbose=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`volume`
a|
The name of the specific volume for which you want to check parity. Enclose the volume name in square brackets ([ ]). If the volume name contains special characters or consists only of numbers, you must enclose the identifier in double quotation marks (" ") inside square brackets.
a|
`parityErrorFile`
a|
The file path and the file name to which you want to save the parity error information. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\parerr.txt"`

This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

a|
`mediaErrorFile`
a|
The file path and the file name to which you want to save the media error information. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\mederr.txt"`

This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

a|
`priority`
a|
The priority that the parity check has relative to host I/O activity. Valid values are `highest`, `high`, `medium`, `low`, or `lowest`.The lowest priority rate benefits system performance, but the parity check takes longer. The highest priority rate benefits the parity check, but system performance might be compromised.
a|
`startingLBA`
a|
The starting logical block address.
a|
`endingLBA`
a|
The ending logical block address.
a|
`verbose`
a|
The setting to capture progress details, such as percent complete, and to show the information as the volume parity is being scanned. To capture progress details, set this parameter to `TRUE`. To prevent capturing progress details, set this parameter to `FALSE`.
|===

== Notes

The starting logical block address and the ending logical block address are useful for very large single-volume LUNs or namespaces. Running a volume parity check on a very large single volume LUN or namespace can take a long time. By defining the beginning address and ending address of the data blocks, you can reduce the time that a volume parity check takes to complete.
