---
permalink: reference_wombat_delete_sgsnapvolume.html
sidebar: sidebar
keywords: 
summary: 'The delete sgSnapVolume command deletes the snapshot volume of a consistency group. Optionally, you can also delete the repository members.'
---
= Delete consistency group snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `delete sgSnapVolume` command deletes the snapshot volume of a consistency group. Optionally, you can also delete the repository members.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
delete cgSnapVolume ["snapVolumeName"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----

== Parameters

|===
| Parameter| Description
a|
`cgSnapVolume`
a|
The name of the consistency group snapshot volume that you want to delete. Enclose the name of the consistency group snapshot volume in double quotation marks (" ") inside square brackets ([ ]).
a|
`deleteRepositoryMembers`
a|
The parameter to save or delete the member volumes. To save the member volumes, set this parameter to `TRUE`. To delete the member volumes, set this parameter to `FALSE`. The default value is `TRUE`.

|===

== Minimum firmware level

7.83
