---
permalink: reference_wombat_resume_snapimage_rollback.html
sidebar: sidebar
keywords: 
summary: 'The resume snapImage rollback command resumes a rollback operation that has entered a paused state.'
---
= Resume snapshot image rollback
:icons: font
:imagesdir: ./media/

[.lead]
The `resume snapImage rollback` command resumes a rollback operation that has entered a paused state.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

A rollback operation can enter a paused state due to processing errors, which causes a Needs Attention condition for the storage array.

If the rollback operation cannot be resumed, the selected snapshot image reverts to a paused state, and the Needs Attention condition is displayed.

[NOTE]
====
You cannot use this command for snapshot images involved in online volume copy.
====

== Syntax

----
resume snapImage [snapImageName] rollback
----

== Parameter

|===
| Parameter| Description
a|
`snapImage`
a|
The name of the snapshot image for which you want to restart a rollback operation. The name of a snapshot image is comprised of two parts:

* The name of the snapshot group
* An identifier for the snapshot image in the snapshot group

The identifier for the snapshot image can be one of these:

* An integer value that is the sequence number of the snapshot in the snapshot group.
* `NEWEST` - Use this option when you want to show the latest snapshot image created in the snapshot group.
* `OLDEST` - Use this option when you want to show the earliest snapshot image created in the snapshot group.

Enclose the snapshot image name in double quotation marks (" ") inside square brackets ([ ]).

|===

== Notes

The name of a snapshot image has two parts separated by a colon (:):

* The identifier of the snapshot group
* The identifier of the snapshot image

For example, if you want to restart a rollback operation for snapshot image 12345 in a snapshot group that has the name snapgroup1, you would use this command:

----
resume snapImage ["snapgroup1:12345"] rollback;
----

== Minimum firmware level

7.83
