---
permalink: reference_wombat_enable_diskpool_security.html
sidebar: sidebar
keywords: 
summary: 'The enable diskPool security command converts a non-secure disk pool to a secure disk pool.'
---
= Enable disk pool security
:icons: font
:imagesdir: ./media/

[.lead]
The `enable diskPool security` command converts a non-secure disk pool to a secure disk pool.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
All of the drives that comprise the disk pool must be secure-capable.
====

== Syntax

----
enable diskPool [diskPoolName] security
----

== Parameter

|===
| Parameter| Description
a|
`diskPool`
a|
The name of the disk pool that you want to place in the Security Enabled state. Enclose the disk pool identifier in square brackets ([ ]).
|===

== Notes

Each disk pool name must be unique. You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the user label. User labels can have a maximum of 30 characters.

== Minimum firmware level

7.83
