---
permalink: reference_wombat_clear_storagearray_recoverymode.html
sidebar: sidebar
keywords: 
summary: 'The clear storageArray recoveryMode command forces a storage array to exit recovery mode.'
---
= Clear storage array recovery mode
:icons: font
:imagesdir: ./media/

[.lead]
The `clear storageArray recoveryMode` command forces a storage array to exit recovery mode.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
clear storageArray recoveryMode
----

== Parameters

None.

== Notes

[NOTE]
====
Recovery mode is entered during start-of-day operations when the system configuration is cleared and a valid on board backup is available. This mode is exited by either restoring the system configuration from a backup location, or by clearing the existing on board backups. While recovery mode is in force, a *needs attention* condition is raised and the Recovery Guru is available from the user interface. However, the system configuration is empty during recovery mode.
====

[NOTE]
====
If you want to return the storage array to a previous configuration, you must restore the configuration from the backup before clearing recovery mode. You must perform validation checks or check with technical support to make sure that the restore was successful. After determining that the restore was successful, recovery mode can be cleared.
====

== Minimum firmware level

7.83
