---
permalink: whats-new.html
sidebar: sidebar
keywords: what's new
summary: "This topic lists changes in the latest SANtricity System Manager releases of the CLI command and Script commands."
---
= What's new
:icons: font
:imagesdir: ../media/

[.lead]
This topic lists changes in the latest SANtricity System Manager releases of the CLI command and Script commands.

[NOTE]
====
When issuing SMcli commands at the command prompt, you must enter an additional backslash (`\`) character as an escape character in the file path name of an input or output file when using the Windows OS. The additional backslash (`\`) must be included when using SMcli in secure, https mode, by providing the -u option to specify a role-based access management user. Example: `C:\\dir\\subdir\\filename`
====

[NOTE]
====
If you are currently using SANtricity 11.52 or earlier, you cannot upgrade to the latest version of SANtricity through the legacy CLI. Upgrades from SANtricity 11.52 to later versions can only be performed through the SMcli.
====

== SANtricity 11.90

The following table list changes to the CLI and Script Commands for release 11.90.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html[Set AutoSupport Dispatch Size Limit]
a|
Added command 
a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html[Save controller arrayManagementCSR]
a|
Added `KeySize` parameter.
a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-https-delivery-method-e2800-e5700.html[Set AutoSupport delivery configuration]
a|
Added `destinationAddress` parameter.
a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples[Show AutoSuppot Settings]
a|
Added dispatch size limits and destination email addresses to example output for command.
a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-storagearray.html[Set storage array]
a|
Updated `mediaScanRate` parameter range to 1 - 210 days. 
 a|
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html[Download storageArray keyManagementCertificate]
a|
Added `privateKeyFile`.  
|===

== SANtricity 11.81

The following table list changes to the CLI and Script Commands for release 11.81.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices[Identify devices]
a|
Added `identifyDevices` parameter.
|===

== SANtricity 11.80

The following table list changes to the CLI and Script Commands for release 11.80.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[Save check volume parity job parity errors]
a|
Added command
a|
xref:./commands-a-z/start-check-vol-parity-job.adoc[Start check volume parity job]
a|
Added command
a|
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[Show check volume parity jobs]
a|
Added command
a|
xref:./commands-a-z/show-check-vol-parity-job.adoc[Show check volume parity job]
a|
Added command
a|
xref:./commands-a-z/stop-check-vol-parity-job.adoc[Stop check volume parity job]
a|
Added command
a|
xref:./get-started/command-line-parameters.adoc[Legacy command line parameters]
a|
Added `-useLegacyTransferPort` parameter. 
a|
xref:./commands-a-z/autoconfigure-storagearray.adoc[Autoconfigure storage array]
a|
Added `blockSize` parameter.
a|
xref:./commands-a-z/check-volume-parity.adoc[Check volume parity]
a|
Deprecated command. 
|===

== SANtricity 11.70.5

There are no CLI and Script Command changes for release 11.70.5.

== SANtricity 11.70.4

The following table list changes to the CLI and Script Commands for release 11.70.4.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./get-started/downloadable-smcli-parameters.adoc[Downloadble SMcli command line parameters]
a|
Added `-t` and `-T` access token parameter descriptions for multifactor authentication.
|===

== SANtricity 11.70.3

The following table list changes to the CLI and Script Commands for release 11.70.3.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[Start Disk Pool Resource Provisioning]
a|
Added command
a|
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[Start Volume Group Resource Provisioning]
a|
Added command
a|
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[Start Disk Pool Full Provisioning]
a|
Updated `disableResourceProvisioning` parameter description.
a|
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[Start Volume Group Full Provisioning]
a|
Updated `disableResourceProvisioning` parameter description.
a|
xref:./commands-a-z/recreate-storagearray-securitykey.html[Re-create external security key]
a|
Added `deleteOldKey` parameter.
a|
xref:./commands-a-z/create-diskpool.html[Create disk pool]
a|
Updated `driveCount` parameter description.
|===

== SANtricity 11.70.2

The following table list changes to the CLI and Script Commands for release 11.70.2.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./commands-a-z/create-snmpuser-username.adoc[Register SNMPv3 USM user]
a|
Added command
a|
xref:./commands-a-z/set-snmpuser-username.adoc[Update SNMPv3 USM user]
a|
Added command
a|
xref:./commands-a-z/show-allsnmpusers.adoc[Show SNMPv3 USM user]
a|
Added command
a|
xref:./commands-a-z/delete-snmpuser-username.adoc[Unregister SNMPv3 USM user]
a|
Added command
a|
xref:./commands-a-z/create-snmptrapdestination.adoc[Register SNMP trap destination]
a|
Added `userName` and `engineid` parameters.
a|
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[Update SNMP trap destination]
a|
Added `userName` and `engineid` parameters.
a|
xref:./commands-a-z/start-snmptrapdestination.adoc[Test SNMP trap destination]
a|
Added `userName` and `engineid` parameters.
|===

== SANtricity 11.70.1

The following table list changes to the CLI and Script Commands for release 11.70.1.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./commands-a-z/start-drive-erase.adoc[Start drive erase]
a|
Added command
a|
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[Import storage array security key]
a|
Added `forceOverwrite` parameter.
a|
xref:./commands-a-z/set-controller-hostport.adoc[Set controller host port properties]
a|
Added `fecMode` parameter.
a|
xref:./commands-a-z/show-syslog-summary.adoc[Show syslog configuration]
a|
Added `syslogFormat` parameter.
a|
xref:./commands-a-z/set-syslog.adoc[Configure syslog settings]
a|
Added `syslogFormat` parameter.
a|
xref:./commands-a-z/set-emailalert.adoc[Configure email alert settings]
a|
Added `serverEncryption`, `serverPort`, `serverUsername`, and `serverPassword` parameters.
a|
xref:./commands-a-z/show-emailalert-summary.adoc[Show email alert configuration]
a|
Added `SMTP` encryption, port, and credential parameter data.
a|
xref:./commands-a-z/recover-volume.adoc[Recover RAID volume]
a|
Added `blockSize` parameter.
|===

== SANtricity 11.70

The following table list changes to the CLI and Script Commands for release 11.70.

[cols="2*",options="header"]
|===
| Command| Description of Change
a|
xref:./commands-a-z/download-storagearray-firmware.adoc[Download storage array firmware/NVSRAM]
a|
Added `healthCheckNeedsAttnOverride` parameter.
a|
xref:./commands-a-z/create-volume-diskpool.adoc[Create volume in disk pool]
a|
Added `raidLevel` parameter.
a|
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[Enable external security key management]
a|
Added `saveFile` parameter.
a|
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[Disable external security key management]
a|
Added `saveFile` parameter.
a|
xref:./commands-a-z/recover-volume.adoc[Recover RAID volume]
a|
Added `hostUnmapEnabled` parameter.
|===
