---
permalink: wombat-save-storagearray-rlscounts.html
sidebar: sidebar
keywords: 
summary: 'The save storageArray RLSCounts command saves the read link status \(RLS\) counters to a file.'
---
= Save storage array RLS counts
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray RLSCounts` command saves the read link status (RLS) counters to a file.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
save storageArray RLSCounts file="filename"
----

== Parameter

|===
| Parameter| Description
a|
`file`
a|
The file path and the file name to which you want to save the RLS counters. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\rlscnt.csv"`

The default name of the file that contains the RLS counts is `read-link-status.csv`. You can use any file name, but you must use the `.csv` extension.

|===

== Notes

To more effectively save RLS counters to a file, perform these steps:

. Run the `reset storageArray RLSBaseline` command to set all of the RLS counters to 0.
. Run the storage array for a predetermined amount of time (for instance, two hours).
. Run the `save storageArray RLSCounts file="``filename``"` command.

== Minimum firmware level

6.10
