---
permalink: wombat-show-allsnmpcommunities.html
sidebar: sidebar
keywords: 
summary: 'The show allSnmpCommunities command returns information about the Simple Network Management Protocol \(SNMP\) communities defined for the storage array. SNMP communities are collections of devices, such as routers, switches, printers, storage devices, grouped together to manage and monitor the devices.'
---
= Show SNMP communities
:icons: font
:imagesdir: ./media/

[.lead]
The `show allSnmpCommunities` command returns information about the Simple Network Management Protocol (SNMP) communities defined for the storage array. SNMP communities are collections of devices, such as routers, switches, printers, storage devices, grouped together to manage and monitor the devices.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin or Storage Monitor role.

== Context

Information returned includes the following:

* The total number of communities
* The total number of trap destinations
* The names of the SNMP communities

== Syntax

----
show (allSnmpCommunities |
snmpCommunity communityName="snmpCommunityName" |
snmpCommunities [snmpCommunityName1 ... snmpCommunityNameN])
[summary]
----

== Parameters

|===
| Parameter| Description
a|
`allSnmpCommunities`
a|
This parameter returns information about all of the SNMP communities in the storage array.
a|
`communityName`
a|
The name of the SNMP community for which you want to retrieve information. Enclose the SNMP community name in double quotation marks (" ").
a|
`snmpCommunities`
a|
The names of several SNMP communities for which you want to retrieve information. Enter the names of the SNMP communities using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`summary`
a|
This parameter returns a list of the total number of SNMP communities and the total number of SNMP trap destinations. When you use this parameter, all of the detail information is omitted.
|===

== Notes

SNMP supports one or more _communities_ to which managers and managed devices belong. SNMP requests contain a _community string_ in the data packets passed over the network that acts as a crude password. SNMP agents can reject GET or SET requests with an unrecognized community string. A community string is also included in TRAP notifications sent from agent to manager as well.

The embedded SNMP agent supports both IPV4 and IPV6.

This command returns SNMP community information similar to this example.

----
SNMP COMMUNITIES------------------------------
SUMMARY
   Total SNMP Communities: 2
   Total SNMP Trap Destinations: 1
DETAILS
   SNMP Community: TestComm1
   SNMP Permission: Read Only
      Associated Trap Destination:
      Trap Receiver IP Address: 10.113.173.133
      Send Authentication Failure Traps: true
   SNMP Community: Test2
   SNMP Permission: Read Only
      Associated Trap Destination:
----

== Minimum firmware level

8.30
