---
permalink: wombat-import-storagearray-securitykey-file.html
sidebar: sidebar
keywords: 
summary: 'The import storageArray securityKey file command unlocks one or more full disk encryption \(FDE\) drives that you have moved from one storage array to another storage array.'
---
= Import storage array security key
:icons: font
:imagesdir: ./media/

[.lead]
The `import storageArray securityKey file` command unlocks one or more full disk encryption (FDE) drives that you have moved from one storage array to another storage array.

== Supported Arrays

If external key management is enabled, then this command applies only to the E2800, E5700, EF600, or EF300 arrays. If internal key management is enabled, then the command applies to any individual storage array, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

Only the drives with the matching security key are unlocked. After they are unlocked, the security key for the new storage array is applied.

[NOTE]
====
This command applies to both internal and external key management.
====

== Syntax

----
import storageArray securityKey file="fileName"
passPhrase="passPhraseString"
[forceOverwrite=(TRUE|FALSE)
----

== Parameters

|===
| Parameter| Description
a|
`file`
a|
The file path and the file name that has the original security key of the imported FDE drives. For example:

----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----

[NOTE]
====
The file name must have an extension of `.slk`.
====

a|
`passPhrase`
a|
The character string that provides authentication for the security key.
a|
`forceOverwrite`
a|
If this parameter is set to `TRUE`, the import will force overwriting the FDE key when the import would normally not be allowed, such as when one controller is absent or failed. By default, the force overwrite parameter is set to FALSE.
|===

== Notes

The controller firmware creates a lock that restricts access to the FDE drives. FDE drives have a state called Security Capable. When you create a security key, the state is set to Security Enabled, which restricts access to all FDE drives that exist within the storage array.

Your pass phrase must meet these criteria:

* Must be between eight and 32 characters long.
* Must contain at least one uppercase letter.
* Must contain at least one lowercase letter.
* Must contain at least one number.
* Must contain at least one non-alphanumeric character, for example, < > @ +.

[NOTE]
====
If your pass phrase does not meet these criteria, you will receive an error message and will be asked to retry the command.
====

== Minimum firmware level

7.40

8.40 added the ability to import an external storage array security key

11.70.1 added the `forceOverwrite` parameter.
