---
permalink: wombat-stop-storagearray-configdbdiagnostic.html
sidebar: sidebar
keywords: 
summary: 'The stop storageArray configDbDiagnostic command stops the diagnostic test to validate the configuration database in the controller firmware that was started by the start storageArray configDbDiagnostic command.'
---
= Stop storage array configuration database diagnostic
:icons: font
:imagesdir: ./media/

[.lead]
The `stop storageArray configDbDiagnostic` command stops the diagnostic test to validate the configuration database in the controller firmware that was started by the `start storageArray configDbDiagnostic` command.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
stop storageArray configDbDiagnostic
----

== Parameters

None.

== Notes

The controller firmware returns a confirmation that the diagnostic test was cancelled.

In addition, you can start the database configuration diagnostic test through the storage management software GUI; however, you cannot stop the database configuration diagnostic test through the storage management software GUI. If you want to stop a running diagnostic test, you must use the `stop storageArray configDbDiagnostic` command.

If you try to use the `stop storageArray configDbDiagnostic` command after validation of the storage array configuration has finished, you do not receive any message that the validation has finished. This behavior is expected.

== Minimum firmware level

7.75

7.77 refines usage.
