---
permalink: wombat-create-mapping-cgsnapvolume.html
sidebar: sidebar
keywords: 
summary: 'The create mapping cgSnapVolume command creates a logical mapping from a consistency group snapshot volume to a host or a host group.'
---
= Create consistency group snapshot volume mapping
:icons: font
:imagesdir: ./media/

[.lead]
The `create mapping cgSnapVolume` command creates a logical mapping from a consistency group snapshot volume to a host or a host group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
create mapping cgSnapVolume="snapVolumeName"
(host="hostName" | hostGroup=("hostGroupName" | defaultGroup))
----

== Parameters

|===
| Parameter| Description
a|
`cgSnapVolume`
a|
The name of the consistency group snapshot volume for which you want to create a logical mapping. Enclose the consistency group snapshot volume name in double quotation marks (" ").
a|
`host`
a|
The name of a host to which you want to create a logical mapping. Enclose the host name in double quotation marks (" ").
a|
`hostGroup`
a|
The name of a host group to which you want to create a logical mapping. Enclose the host group name in double quotation marks (" "). If you use the `defaultGroup` keyword, do not enclose it in quotation marks.
|===

== Notes

A host is a computer that is attached to the storage array and accesses the volumes on the storage array through the host ports. You can define specific mappings to an individual host. You also can assign the host to a host group that shares access to one or more volumes.

A host group is an optional topological element that you can define if you want to designate a collection of hosts that share access to the same volumes. The host group is a logical entity. Define a host group only if you have two or more hosts that share access to the same volumes.

== Minimum firmware level

7.83
