---
permalink: wombat-set-snapgroup.html
sidebar: sidebar
keywords: 
summary: 'The set snapGroup command defines the properties for a snapshot group.'
---
= Set snapshot group attributes
:icons: font
:imagesdir: ./media/

[.lead]
The `set snapGroup` command defines the properties for a snapshot group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
set snapGroup ["snapGroupName"]
[userLabel="snapGroupName"] |
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages) |
[repositoryFullLimit=percentValue |
[autoDeleteLimit=numberOfSnapImages] |
[rollbackPriority=(lowest | low | medium | high | highest)]
----

== Parameters

|===
| Parameter| Description
a|
`snapGroup`
a|
The name of the snapshot group for which you are setting properties. Enclose the snapshot group name in double quotation marks (" ") inside of square brackets ([ ]).
a|
`userLabel`
a|
The new name that you want to give to the snapshot group. Use this parameter when you want to rename the snapshot group. Enclose the new snapshot group name in double quotation marks (" ").
a|
`repositoryFullPolicy`
a|
How you want snapshot image processing to continue if the repository volumes for the snapshot image group are full. You can choose to fail writes to the base volume (`failBaseWrites`) or delete (purge) the snapshot images (`purgeSnapImages`). The default action is `purgeSnapImages`.
a|
`repositoryFullLimit`
a|
The percentage of repository volume capacity at which you receive a warning that the snapshot image repository volume is nearing full. Use integer values. For example, a value of 70 means 70 percent. The default value is 75.

a|
`autoDeleteLimit`
a|
The maximum number of snapshot images that you want to automatically delete if you have selected to purge the snapshot images for a repository full policy. Use integer values. The default value is 32.

a|
`rollBackPriority`
a|
Use this parameter to determine whether system resources should be allocated to the rollback operation at the expense of system performance. Valid values are `highest`, `high`, `medium`, `low`, or `lowest` A value of `high` indicates that the rollback operation is prioritized over all other host I/O. A value of `lowest` indicates that the rollback operation should be performed with minimal impact to host I/O.

|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

When you use this command, you can specify one or more of the parameters. You do not, however, need to use all of the parameters.

== Minimum firmware level

7.83
