---
permalink: wombat-download-controller-arraymanagementservercertificate.html
sidebar: sidebar
keywords: 
summary: 'The download controller arrayManagementServerCertificate command installs the server certificate on the controller.'
---
= Install server signed certificate
:icons: font
:imagesdir: ./media/

[.lead]
The `download controller arrayManagementServerCertificate` command installs the server certificate on the controller.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

Perform this action for each controller using the signed certificate that is applicable to the controller. The signed certificate must include the controller's IPs/DNS names.

== Syntax

----

download controller [(a|b)] arrayManagementServerCertificate file="filename"
----

== Parameters

|===
| Parameter| Description
a|
`controller`
a|
Allows the user to specify the controller on which you want to install the server signed certificate for. Valid controller identifiers are a or b, where a is the controller in slot A, and b is the controller in slot B. Enclose the controller identifier in square brackets ([ ]).
a|
`file`
a|
Allows the user to specify the file path and filename that contains the signed certificate. The acceptable extensions are .cer, .crt, .der.
|===

== Examples

----

SMcli -n Array1 -c "download controller [a] arrayManagementServerCertificate
   file="C:\serverSignedCertificateA.cer";"

SMcli -n Array1 -c "download controller [b] arrayManagementServerCertificate
   file="C:\serverSignedCertificateB.cer";"

SMcli completed successfully.
----

== Minimum firmware level

8.40
