---
permalink: wombat-show-asyncmirrorgroup-summary.html
sidebar: sidebar
keywords: 
summary: 'The show asyncMirrorGroup summary command displays configuration information for one or more asynchronous mirror groups.'
---
= Show asynchronous mirror groups
:icons: font
:imagesdir: ./media/

[.lead]
The `show asyncMirrorGroup summary` command displays configuration information for one or more asynchronous mirror groups.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin role.

== Context

This command also displays the asynchronous mirrored pairs associated with each asynchronous mirror group, including incomplete asynchronous mirrored pairs.

You also can use this command to show the progress of periodic data synchronization on all of the mirrored pairs within the asynchronous mirror group.

== Syntax

----
show (allAsyncMirrorGroups |
asyncMirrorGroup [asyncMirrorGroupName] |
asyncMirrorGroups [asyncMirrorGroupName1 ... asyncMirrorGroupNameN])
[summary]
----

== Parameter

|===
| Parameter| Description
a|
`allAsyncMirrorGroups`
a|
Use this parameter if you want to display the properties for all asynchronous mirror groups.
a|
`asyncMirrorGroup`
a|
The name of an asynchronous mirror group for which you want to show configuration information and the progress of periodic data synchronization. Enclose the asynchronous mirror group name in square brackets ([ ]). If the asynchronous mirror group name has special characters or numbers, you must enclose the asynchronous mirror group name in double quotation marks (" ") inside square brackets.

a|
`asyncMirrorGroups`
a|
The names of several asynchronous mirror groups for which you want to retrieve information. Enter the names of the asynchronous mirror groups using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the asynchronous mirror group names have special characters or numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`summary`
a|
This parameter displays a concise list of information about the synchronization progress of one or more asynchronous mirror groups.

|===

== Minimum firmware level

7.84
