---
permalink: wombat-show-syncmirror-synchronizationprogress.html
sidebar: sidebar
keywords: 
summary: 'The show syncMirror synchronizationProgress command returns the progress of data synchronization between the primary volume and the secondary volume in a Synchronous Mirroring configuration.'
---
= Show synchronous mirroring volume synchronization progress
:icons: font
:imagesdir: ./media/

[.lead]
The `show syncMirror synchronizationProgress` command returns the progress of data synchronization between the primary volume and the secondary volume in a Synchronous Mirroring configuration.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

This command shows the progress as a percentage of data synchronization that has been completed.

[NOTE]
====
In previous versions of this command the feature identifier was `remoteMirror`. This feature identifier is no longer valid and is replaced by `syncMirror`.
====

== Syntax

----
show syncMirror (localVolume [volumeName] |
localVolumes [volumeName1... volumeNameN]) synchronizationProgress
----

== Parameter

|===
| Parameter| Description
a|
`volume`
a|
The name of the primary volume of the remote mirrored pair for which you want to check synchronization progress. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the volume name in double quotation marks (" ") inside square brackets.

a|
`volumes`
a|
The names of the primary volume of the remote mirrored pair for which you want to check synchronization progress. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or consist only of numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

|===

== Minimum firmware level

5.40
