---
permalink: wombat-set-cgsnapvolume.html
sidebar: sidebar
keywords: 
summary: 'The set cgSnapVolume command creates a unique name for a snapshot volume of a consistency group.'
---
= Set consistency group snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `set cgSnapVolume` command creates a unique name for a snapshot volume of a consistency group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
set cgSnapVolume [cgSnapVolumeName]
userLabel="cgSnapVolumeName"
----

== Parameters

|===
| Parameter| Description
a|
`cgSnapVolume`
a|
The name of the consistency group volume that you want to rename. Enclose the name of the consistency group snapshot volume in square brackets ([ ]).
a|
`userLabel`
a|
The new name that you want to give to the snapshot volume in the consistency group. Enclose the new snapshot volume name in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

7.83
