---
permalink: wombat-stop-pendingsnapimagecreation.html
sidebar: sidebar
keywords: 
summary: 'The stop pendingSnapImageCreation command cancels all of the pending snapshot images that are to be created on a snapshot or snapshot consistency group.'
---
= Stop snapshot group pending snapshot images
:icons: font
:imagesdir: ./media/

[.lead]
The `stop pendingSnapImageCreation` command cancels all of the pending snapshot images that are to be created on a snapshot or snapshot consistency group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the snapshot group does not have any pending snapshot images, the firmware displays an error message and does not run the command. You can run this command on a snapshot group or a snapshot consistency group.

== Syntax

----
stop (snapGroup [snapGroupName] |
consistencyGroup [snapConsistencyGroupName])
pendingSnapImageCreation
----

== Parameters

|===
| Parameter| Description
a|
`snapGroup`
a|
The name of the snapshot group for which you want to stop pending snapshot images. Enclose the snapshot group name in square brackets ([ ]). If the snapshot group name has special characters or numbers, you must enclose the snapshot group name in double quotation marks (" ") inside square brackets.

a|
`consistencyGroup`
a|
The name of the snapshot consistency group for which you want to stop pending snapshot images. Enclose the snapshot consistency group name in square brackets ([ ]). If the snapshot consistency group name has special characters or numbers, you must enclose the snapshot group name in double quotation marks (" ") inside square brackets.

|===

== Minimum firmware level

7.83
