---
permalink: wombat-save-storagearray-firmwareinventory.html
sidebar: sidebar
keywords: 
summary: 'The save storageArray firmwareInventory command saves a report to a file of all of the firmware currently running on the storage array.'
---
= Save storage array firmware inventory
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray firmwareInventory` command saves a report to a file of all of the firmware currently running on the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

The report lists the firmware for these components:

* Controllers
* Drives
* Drawers (if applicable)
* Environmental services modules (ESMs)
* Power supplies

You can use the information to help identify out-of-date firmware or firmware that does not match the other firmware in your storage array. You can also send the report to technical support for further review.

== Syntax

----
save storageArray firmwareInventory file="filename"
----

== Parameter

|===
| Parameter| Description
a|
`file`
a|
The file path and the file name to which you want to save the firmware inventory. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\fwinvent.txt"`

The default name of the file that contains the firmware inventory is `firmware-inventory.txt`. This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

|===

== Minimum firmware level

7.70
