---
permalink: wombat-check-asyncmirrorgroup-repositoryconsistency.html
sidebar: sidebar
keywords: 
summary: 'The check asyncMirrorGroup repositoryConsistency command produces a report based on analysis of the data in the underlying repository volume of the specified asynchronous mirror group.'
---
= Check asynchronous mirror group consistency
:icons: font
:imagesdir: ./media/

[.lead]
The `check asyncMirrorGroup repositoryConsistency` command produces a report based on analysis of the data in the underlying repository volume of the specified asynchronous mirror group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin role.

== Syntax

----
check asyncMirrorGroup[asyncMirrorGroupName]
repositoryConsistency localVolume=[localVolumeName"]
file="filePath"
----

== Parameters

|===
| Parameter| Description
a|
`asyncMirrorGroup`
a|
The name of the asynchronous mirror group on which to run a consistency check. Enclose the asynchronous mirror group name in square brackets ([ ]). If the asynchronous mirror group name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.

a|
`repositoryConsistency`
a|
Specifies that the asynchronous mirror group is checked for consistency.

a|
`localVolume`
a|
Specifies the name of a local volume that participates in the mirror relationship. You can specify a local volume that is either the source or the destination on a mirror relationship. If the local volume name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.

a|
`file`
a|
The file path and the file name to which you want to save the report that results from the consistency check. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` This parameter must appear last, after any of the optional parameters.

|===

== Notes

The report generated by this command is intended for use by technical support to analyze problems.

== Minimum firmware level

7.83
