---
permalink: wombat-clear-volume-reservations.html
sidebar: sidebar
keywords: 
summary: 'The clear volume reservations command clears persistent volume reservations.'
---
= Clear volume reservations
:icons: font
:imagesdir: ./media/

[.lead]
The `clear volume reservations` command clears persistent volume reservations.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
clear (allVolumes | volume [volumeName] |
volumes ["volumeName1" ... "volumeNameN"]) reservations
----

== Parameters

|===
| Parameter| Description
a|
`allVolumes`
a|
The setting to clear persistent volume reservations on all of the volumes in the storage array.
a|
`volume`
a|
The name of a volume for which you are clearing persistent reservations. Enclose the volume name in square brackets ([ ]). If the volume name contains special characters or consists only of numbers, you must enclose the name in double quotation marks (" ") inside square brackets.

a|
`volumes`
a|
The names of several volumes for which you are clearing persistent reservations. Enter the names of the member volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

|===

== Notes

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.
