---
permalink: wombat-set-hostport.html
sidebar: sidebar
keywords: 
summary: 'The set hostPort command changes the properties for a host port.'
---
= Set host port
:icons: font
:imagesdir: ./media/

[.lead]
The `set hostPort` command changes the properties for a host port.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
This command does not work in an iSCSI environment, where the host ports are considered initiators. Instead, use the `set iscsiInitiator` command. See xref:wombat-set-iscsiinitiator.adoc[Set iSCSI initiator].
====

== Syntax

----
set hostPort [portLabel] userLabel=newPortLabel
[host=hostName]
----

== Parameters

|===
| Parameter| Description
a|
`hostPort`
a|
The name of the host port for which you want to change the host type, or for which you want to create a new name. Enclose the host port name in square brackets ([ ]). If the host port name has special characters or numbers, enclose the host port name in double quotation marks (" ") inside square brackets.
a|
`userLabel`
a|
The new name that you want to give to the host port. Enclose the new name of the host port in double quotation marks (" ").
a|
`host`
a|
The name of the host for which you are defining an HBA or HCA host port. Enclose the host name in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, hyphens, and underscores for the user label. User labels can have a maximum of 30 characters.

== Minimum firmware level

6.10
