---
permalink: wombat-set-emailalert.html
sidebar: sidebar
keywords: 
summary: 'The set emailAlert command configures the email to send an email to a specified technical support or organization. The email alert contains a summary of the event, detailed information about the affected storage, and customer contact information.'
---
= Configure email alert settings
:icons: font
:imagesdir: ./media/

[.lead]
The `set emailAlert` command configures the email to send an email to a specified technical support or organization. The email alert contains a summary of the event, detailed information about the affected storage, and customer contact information.

== Supported Arrays

This command applies to theE2800, E5700, EF600, and EF300 storage arrays. However, you can use the command as an SMcli command, not a script command, for E2700 or E5600 arrays. In this case, the command applies to all of the arrays in the management domain.

== Syntax

----

set emailAlert
    serverAddress="serverAddress" |
    serverEncryption=none | smtps | starttls |
    serverPort=port value |
    serverUsername="username" |
    serverPassword="password" |
    senderAddress="emailAddress" |
    additionalContactInfo="filename"  |
    (recipientAddresses=("emailAddress1" ... "emailAddressN") |
 addRecipientAddresses=("emailAddress1" ... "emailAddressN"))
----

== Parameters

|===
| Parameter| Description
a|
`serverAddress`
a|
Allows you to set the email server address. The email server address can be a fully qualified domain name, IPv4 address, or IPv6 address.
a|
`serverEncryption`
a|
The encryption to be used to communicate with the server. The value may be one of the following:

* `none` - No encryption
* `smtps` - Create an SSL/TLS connection (implicit TLS)
* `starttls` - Create an unencrypted connection and then establish an SSL/TLS session (explicit TLS)

a|
`serverPort`
a|
The TCP port to be used to connect to the server. The default value will depend on the encryption type.

* `none` - Defaults to port 25
* `smtps` - Defaults to port 465
* `starttls` - Defaults to port 587

a|
`serverUsername`
a|
The user name to provide authentication credentials to the server. If the user name is specified, the password must also be specified.
a|
`serverPassword`
a|
The password to provide authentication credentials to the server. If the password is specified, the user name must also be specified.
a|
`senderAddress`
a|
Allows you to set the sender's email address.
a|
`additionalContactInfo`
a|
Allows you to provide the filename that contains the additional contact information to be used in the email alert.
a|
`recipientAddresses`
a|
Allows you to set one or more recipient email addresses. Using this set option will clear out existing email addresses. Enclose all of the names in parentheses. Enclose each of the names in double quotation marks (""). Separate each of the names with a space.
a|
`addRecipientAddresses`
a|
Allows you to add one or more recipient email addresses to the existing list. Enclose all of the names in parentheses. Enclose each of the names in double quotation marks (""). Separate each of the names with a space.
|===

== Examples

----

SMcli -n Array1 -c "set emailAlert
   serverAddress="email.server.domain.com"
    serverEncryption=("smtps") |
    serverPort="smtps" |
    serverUsername="username" |
    serverPassword="password" |
   senderAddress="no-reply@server.domain.com"
   additionalContactInfo="C:\additionalInfo.txt"
   recipientAddresses=("person1@email.domain.com" "person2@email.domain.com");"

SMcli -n Array1 -c "set emailAlert addRecipientAddresses=("person3@netapp.com");"

SMcli completed successfully.
----

== Minimum firmware level

8.40

11.70.1 adds the `serverEncryption`, `serverPort`, `serverUsername`, and `serverPassword` parameters.
