---
permalink: wombat-set-snapvolume.html
sidebar: sidebar
keywords: 
summary: 'The set snapVolume command renames an existing snapshot volume.'
---
= Rename snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `set snapVolume` command renames an existing snapshot volume.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
set snapVolume ["snapVolumeName"] userLabel="snapImageVolumeName"
----

== Parameters

|===
| Parameter| Description
a|
`snapVolume`
a|
The name of the snapshot volume that you want to rename. Enclose the snapshot volume name in double quotation marks (" ") inside of square brackets ([ ]).
a|
`userLabel`
a|
A new name that you want to give to the snapshot volume. Enclose the new snapshot volume name in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

7.83
