---
permalink: get-started/adding-comments-to-a-script-file.html
sidebar: sidebar
keywords: add, comments, script file
summary: "The script engine looks for certain characters or a command to show comments. You can add comments to a script file in three ways."
---
= Add comments to a script file
:icons: font
:imagesdir: ./media/

The script engine looks for certain characters or a command to show comments. You can add comments to a script file in three ways:

* Add text after two forward slashes (`//` ) as a comment until an end-of-line character is reached. If the script engine does not find an end-of-line character in the script after processing a comment, an error message appears, and the script operation is terminated. This error usually occurs when a comment is placed at the end of a script and you have forgotten to press the *Enter* key.
+
----
// Deletes the existing configuration.
set storageArray resetConfiguration=true;
----

* Add text between `/*` and `*/` as a comment. If the script engine does not find both a starting comment notation and an ending comment notation, an error message appears, and the script operation is terminated.
+
----
/* Deletes the existing configuration */
set storageArray resetConfiguration=true;
----

* Use the `show` statement to embed comments in a script file that you want to appear while the script file is running. Enclose the text that you want to appear by using double quotation marks ("` `").
+
----
show “Deletes the existing configuration”;
set storageArray resetConfiguration=true;
----
