---
permalink: /get-started/formatting-cli-commands.html
sidebar: sidebar
keywords: 
summary: ''
---
= Formatting CLI commands
:icons: font
:imagesdir: ./media/

Double quotation marks (" ") that are used as part of a name or label require special consideration when you run the CLI commands and the script commands on a Windows, Linux, or Solaris operating system.

When double quotation marks (" ") are part of a name or value, you must insert a backslash (\) before each double quotation mark character. For example:

----
-c "set storageArray userLabel=\"Engineering\";"
----

In this example, "Engineering" is the storage array name. A second example is:

----
-n \"My\"_Array
----

In this example, "My"_Array is the name of the storage array.

You cannot use double quotation marks (" ") as part of a character string (also called string literal) within a script command. For example, you cannot enter the following string to set the storage array name to "Finance" Array:

----
-c "set storageArray userLabel=\"\"Finance\"Array\";"
----

In a Windows operating system, if you do not use double quotation marks (" ") around a name, you must insert a caret ( {caret} ) before each special script character. Special characters are {caret}, | , <, and >.

Insert a caret before each special script character when used with the terminals `-n`, `-o`, `-f`, and `-p`. For example, to specify storage array CLI>CLIENT, enter this string:

----
-n CLI^>CLIENT
----

Insert one caret ({caret}) before each special script character when used within a string literal in a script command. For example, to change the name of a storage array to FINANCE_|_PAYROLL, enter the following string:

----
-c "set storageArray userLabel=\"FINANCE_^|_PAYROLL\";"
----

[NOTE]
====
When issuing SMcli commands at the command prompt, an additional backslash (`\`) character is required as an escape character in the file path name of an input or output file when using the Windows OS. The additional backslash (`\`) must be included when using SMcli in secure, https mode, by providing the -u option to specify a role-based access management user.*Example:*

----
C:\\dir\\subdir\\filename
----

====
