---
permalink: get-started/overview-format-commands.html
sidebar: sidebar
keywords:
summary: ''
---
= Overview of CLI
:icons: font
:imagesdir: ./media/

The command line interface (CLI) is a software application that provides a way to configure and monitor storage arrays. Using the CLI, you can run commands from an operating system prompt, such as the DOS `C:` prompt, a Linux operating system path, or a Solaris operating system path.

The CLI gives you direct access to a script engine that is a utility in the storage management software. The script engine runs commands that configure and manage the storage arrays. The script engine reads the commands, either through a script file or directly from the command line, and performs the operations instructed by the commands.

The script commands configure and manage a storage array. The script commands are distinct from the CLI commands. You can enter individual script commands, or you can run a file of script commands. When you enter an individual script command, you embed the script command in a CLI command. When you run a file of script commands, you embed the file name in the CLI command.

Some software features described in this document might not be available for your E-Series Storage System. For questions about available features, contact your account representative.

The CLI is a feature of the SANtricity Storage Manager software.
