---
permalink: get-started/usage-guidelines.html
sidebar: sidebar
keywords: script command, guidelines
summary: "This list provides guidelines for writing script commands on the command line."
---
= Script command guidelines
:icons: font
:imagesdir: ./media/

This list provides guidelines for writing script commands on the command line:

* You must end all commands with a semicolon (`;`).
* You can enter more than one command on a line, but you must separate each command with a semicolon (`;`).
* You must separate each base command and its associated primary parameters and secondary parameters with a space.
* The script engine is not case sensitive. You can enter commands by using uppercase letters, lowercase letters, or mixed-case letters.
* Add comments to your scripts to make it easier for you and future users to understand the purpose of the script commands. (For information about how to add comments, see link:adding-comments-to-a-script-file.html[Adding comments to a script file].)

[NOTE]
====
While the CLI commands and the script commands are not case sensitive, user labels (such as for volumes, hosts, or host ports) are case sensitive. If you try to map to an object that is identified by a user label, you must enter the user label exactly as it is defined, or the CLI commands and the script commands will fail.
====
