---
permalink: commands-a-z/change-ssd-cache-application-type.html
sidebar: sidebar
keywords: ssd cache application type
summary: "The set ssdCache command changes the application type associated with the SSD cache. The application type can be web server, database, or multimedia. Changing the application type changes the block size, sub-block size, populate on read threshold, and populate on write threshold for the volumes underlying the SSD cache."
---
= Change SSD cache application type
:icons: font
:imagesdir: ../media/

[.lead]
The `set ssdCache` command changes the application type associated with the SSD cache. The application type can be web server, database, or multimedia. Changing the application type changes the block size, sub-block size, populate on read threshold, and populate on write threshold for the volumes underlying the SSD cache.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600, and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Support Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set ssdCache pass:quotes[[_ssdCacheName_]]usageHint=(webServer|dataBase|fileSystem)
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache for which you want to change the application type. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name contains special characters or consists only of numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
a|
`usageHint`
a|
The values are based on the typical I/O usage pattern of the application that is using the SSD cache. Valid values are `webServer`, `dataBase`, or `fileSystem`.
|===

== Minimum firmware level

7.84

11.80 adds EF600 and EF300 array support
