---
permalink: commands-a-z/check-repositoryconsistency.html
sidebar: sidebar
keywords: check, repository, consistency
summary: "The check repositoryConsistency command produces a report based on analysis of the data in a specified object’s underlying repository volume."
---
= Check repository consistency
:icons: font
:imagesdir: ./media/

[.lead]
The `check repositoryConsistency` command produces a report based on analysis of the data in a specified object's underlying repository volume.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
----
check (snapGroup pass:quotes[[_snapGroupName_]] repositoryConsistency |
snapVolume pass:quotes[[_snapVolumeName_]] repositoryConsistency |
volume pass:quotes[[_volumeName_]] repositoryConsistency |
volumeCopy target pass:quotes[[_targetName_]] repositoryConsistency |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[_"localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`repositoryConsistency`
a|
Specifies that the snapshot group, snapshot volume, volume, or asynchronous mirror group (depending on which is specified by the corresponding parameter) is checked for consistency.
a|
`snapGroup`
a|
The name of the snapshot group on which to run a consistency check. Enclose the snapshot group name in square brackets ([ ]). If the snapshot group name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
a|
`snapVolume`
a|
The name of the snapshot volume on which to run a consistency check. Enclose the snapshot volume name in square brackets ([ ]). If the snapshot volume name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
a|
`volume`
a|
The name of the thin volume on which to run a consistency check. Enclose the thin volume name in square brackets ([ ]). If the thin volume name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
a|
`volumeCopy`
a|
Specifies that the target of a volume copy relationship is checked for consistency.
a|
`target`
a|
Use only in conjunction with the `volumeCopy` parameter to specify the name of the volume that is the target of the volume copy relationship. If the volume name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
a|
`asyncMirrorGroup`
a|
The name of the asynchronous mirror group on which to run a consistency check. Enclose the asynchronous mirror group name in square brackets ([ ]). If the asynchronous mirror group name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
a|
`localVolume`
a|
Use only with the `asyncMirrorGroup` parameter to specify the name of a local volume that participates in the mirror relationship. You can specify a local volume that is either the source or the destination on a mirror relationship. Enclose the local volume name in double quotation marks (" ").
a|
`file`
a|
The file path and the file name to which you want to save the report that results from the consistency check. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` This parameter must appear last, after any of the optional parameters.

|===

== Notes

The report generated by this command is intended for use by technical support to analyze problems.

== Minimum firmware level

7.83
