---
permalink: /commands-a-z/create-snmpcommunity.html
sidebar: sidebar
keywords: 
summary: 'The create snmpCommunity command creates a new Simple Network Management Protocol \(SNMP\) community, community name string and registers the new community as a known entity to the SNMP agent. Any attempt to register a new community with the same name as that of an existing community is rejected and the firmware returns an error message.'
---
= Register SNMP community
:icons: font
:imagesdir: ./media/

[.lead]
The `create snmpCommunity` command creates a new Simple Network Management Protocol (SNMP) community, community name string and registers the new community as a known entity to the SNMP agent. Any attempt to register a new community with the same name as that of an existing community is rejected and the firmware returns an error message.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax

----
create snmpCommunity communityName="snmpCommunityName"
----

== Parameters

|===
| Parameter| Description
a|
`communityName`
a|
The name of the SNMP community that you want to create. Enclose the SNMP community name in double quotation marks (" ").
|===

== Minimum firmware level

8.30
