---
permalink: commands-a-z/create-hostport.html
sidebar: sidebar
keywords: create, host, port
summary: "The create hostPort command creates a new host port identification on a host bus adapter (HBA) or on a host channel adapter (HCA)."
---
= Create host port
:icons: font
:imagesdir: ./media/

[.lead]
The `create hostPort` command creates a new host port identification on a host bus adapter (HBA) or on a host channel adapter (HCA).

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

The host port identification is a software value that represents the physical HBA or HCA host port to the controller. Without the correct host port identification, the controller cannot receive instructions or data from the host port.

== Syntax
[subs=+macros]
[source,cli]
----
create hostPort identifier=pass:quotes[_("wwID"_ | "_gid"_)
userLabel="_portLabel"_]
[host=pass:quotes[_"hostName"_]]
[interfaceType=(FC | SAS | IB)]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`identifier`
a|
The 8-byte World Wide Identifier (WWID) or the 16-byte group identifier (GID) of the HBA or HCA host port. Enclose the WWID or the GID in double quotation marks (" ").
a|
`userLabel`
a|
The name that you want to give to the new HBA or HCA host port. Enclose the host port label in double quotation marks (" ").
a|
`host`
a|
The name of the host for which you are defining an HBA or HCA host port. Enclose the host name in double quotation marks (" ").
a|
`interfaceType`
a|
The identifier of the type of interface for the host port.

The choices for the types of host port interfaces are:

* `FC` -- Fibre Channel
* `SAS` -- Serial-Attached SCSI
* `IB` -- InfiniBand

An FC or a SAS selection requires an 8-byte WWID. An IB selection requires a 16-byte group identifier (GID).

If you do not specify the type of interface, `FC` is used as the default interface for the host port.

|===

== Notes

An HBA host port or an HCA host port is a physical connection on a host bus adapter or on a host channel adapter that resides in a host computer. An HBA host port or an HCA host port provides host access to the volumes in a storage array. If the HBA or the HCA has only one physical connection (one host port), the terms host port and host bus adapter or host channel adapter are synonymous.

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

5.20

7.10 deprecates the `hostType` parameter. The `hostType` parameter has been added to the `create host` command.

7.32 adds the `interfaceType` parameter.
