---
permalink: commands-a-z/create-mapping-volume.html
sidebar: sidebar
keywords: create, volume, map
summary: "The create mapping volume command creates a logical mapping from a volume to a host or a host group."
---
= Create Volume Mapping
:icons: font
:imagesdir: ./media/

[.lead]
The `create mapping volume` command creates a logical mapping from a volume to a host or a host group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
----
create mapping volume=pass:quotes[_"VolumeName"_
(host="_hostName_" | hostGroup=("_hostGroupName_"] | defaultGroup))
logicalUnitNumber=lun
mapWaitPeriod=mapWaitPeriodValue
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`Volume`
a|
The name of the volume for which you want to create a logical mapping. Enclose the volume name in double quotation marks (" ").
a|
`host`
a|
The name of a host to which you want to create a logical mapping. Enclose the host name in double quotation marks (" ").
a|
`hostGroup`
a|
The name of a host group to which you want to create a logical mapping. Enclose the host group name in double quotation marks (" "). If you use the `defaultGroup` keyword, do not enclose it in quotation marks.
a|
`logicalUnitNumber`
a|
The logical number or namespace ID that you want to use to map to a specific host. This parameter also assigns the host to a host group.
[NOTE]
====
The logical unit number or namespace ID you specify must not already be in use, and must be within the range supported by the host Operating System. There will be no error if you map the volume to a logical unit number or namespace ID not supported by the host, but the host won't be able to access the volume.
====

a|
`mapWaitPeriod`
a|
Blocks the mapping until it is able to complete the command or it times out as not to affect the interaction. If a value is not entered, the default behavior is to fail the action if the volume cannot be mapped immediately.
|===

== Minimum firmware level

7.83

8.63 adds the mapWaitPeriod parameter.
