---
permalink: commands-a-z/create-cgsnapimage-consistencygroup.html
sidebar: sidebar
keywords: create, consistency group, snapshot image
summary: "he create cgSnapImage consistencyGroup command creates a new snapshot image for each base volume that is a member of a snapshot consistency group."
---
= Create consistency group snapshot image
:icons: font
:imagesdir: ./media/

[.lead]
The `create cgSnapImage consistencyGroup` command creates a new snapshot image for each base volume that is a member of a snapshot consistency group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
----
create cgSnapImage consistencyGroup=pass:quotes[_"consistencyGroupName"_]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`consistencyGroup`
a|
The name of the consistency group for which you are creating snapshot images. Enclose the consistency group name in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

The command causes all pending I/O operations to each base volume that is a member of the consistency group to be drained and suspended before creating the snapshot images. If the creation of all of the snapshot images cannot be completed successfully for all of the consistency group members, the operation fails and new snapshot images are not created.

Normally, all members of a snapshot consistency group have the same number of snapshot images. When you add a new member to a snapshot consistency group, that new member lacks the snapshot images that were previously created on the established members of the snapshot consistency group. This is not an error condition. Requests for deletion or rollback of snapshot images that exist on only a subset of the snapshot consistency group members affects only those members for which the specified snapshot image actually exists.

== Minimum firmware level

7.83
