---
permalink: commands-a-z/create-asyncmirrorgroup.html
sidebar: sidebar
keywords: create, asynchronous, mirror, group
summary: "The create asyncMirrorGroup command creates a new, empty asynchronous mirror group on both the local storage array and the remote storage array."
---
= Create asynchronous mirror group
:icons: font
:imagesdir: ./media/

[.lead]
The `create asyncMirrorGroup` command creates a new, empty asynchronous mirror group on both the local storage array and the remote storage array.

== Supported Arrays

This command applies to any individual storage array, with some restrictions. If you are running the command on the E2700 or E5600 array, there are no restrictions.

[NOTE]
====
If you are running the command on the E2800 or E5700 array, the client type must be set to `symbol`. This command will not execute if they client type is set to `https`.
====

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin role.

== Context

An asynchronous mirror group is a container that can house several mirrored pairs so that they can be managed as one entity. You create an asynchronous mirror group to define the synchronization settings for all mirrored pairs within the group. Each mirrored pair in an asynchronous mirror group share the same synchronization settings, primary and secondary role, and write mode.

The asynchronous mirror group is associated with the local storage array and remote storage array that is used for mirroring. The local storage array is the primary side of the asynchronous mirror group, while the remote storage array is the secondary side of the asynchronous mirror group. All volumes added to the asynchronous mirror group on the local storage array hold the primary role in the mirror relationship. Subsequently, all volumes added to the asynchronous mirror group on the remote storage array hold the secondary role in the mirror relationship.

Make sure that you execute the `Create Asynchronous Mirror Group` command on the local storage array. Asynchronous mirror group creation is initiated from the storage array that contains the volumes that hold the primary role in the mirror relationship. You use the `Create Asynchronous Mirror Group` command to specify the identity of the remote storage array that contains the volumes that hold the secondary role in the mirror relationship.

== Syntax
[subs=+macros]
----
create asyncMirrorGroup userLabel=pass:quotes[_"asyncMirrorGroupName"_]
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_] | remoteStorageArrayWWN=pass:quotes[_"wwID"_])
[remotePassword=pass:quotes[_"password"_]
interfaceType=(FC | iSCSI)
[syncInterval=pass:quotes[_integer_](minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningRecoveryThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[autoResync=(TRUE | FALSE)]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`userLabel`
a|
The name of the new asynchronous mirror group that you want to create. Enclose the new asynchronous mirror group name in double quotation marks (" ").

The name must be unique on the local and remote storage arrays.

a|
`remoteStorageArrayName`
a|
The name for the remote storage array on which you are mirroring the asynchronous mirror group. Enclose the storage array name in double quotation marks (" ").

The remote storage array must have the same connection type as the local storage array.

a|
`remoteStorageArrayWWN`
a|
The World Wide Identifier (WWID) of the remote storage array on which you are mirroring the asynchronous mirror group. You can use the WWID instead of the storage array name to identify the storage array. Enclose the WWID in angle brackets (< >).

The remote storage array must have the same connection type as the local storage array.

a|
*remotePassword* ``
a|
The password for the remote storage array. Use this parameter when the remote storage array is password protected. Enclose the password in double quotation marks (" ").

a|
*interfaceType* ``
a|
Specify which connection type to use: either Fibre Channel fabric or iSCSI interface. (The default is Fibre Channel.) The local storage array and the remote storage array must be connected through a proper Fibre Channel fabric or iSCSI interface.

a|
`syncInterval`
a|
Specify the length of time between automatically sending updates of modified data from the local storage array to the remote storage array. You can specify the length of time in minutes, hours, or days.

[NOTE]
====
Do not add a space between the integer and the length of time.
====

Example: `10minutes`

a|
`warningSyncThreshold`
a|
Specify the length of time to wait until a warning is triggered for cases in which the synchronization of all of the volumes within the asynchronous mirror group takes longer than the defined time. You can specify the length of time in minutes, hours, or days.

[NOTE]
====
Do not add a space between the integer and the length of time.
====

Example: `30minutes`

a|
`warningRecoveryThreshold`
a|
Specify the length of time to wait until a warning is triggered when the automatic data update for the point-in-time image on the remote storage array is older than the defined time. Define the threshold from the end of the previous update. You can specify the length of time in minutes, hours, or days.

[NOTE]
====
You must set the Recovery Point Threshold to be twice as large as the synchronization interval threshold.
====

[NOTE]
====
Do not add a space between the integer and the length of time.
====

Example: `60minutes`

a|
`warningThresholdPercent`
a|
Specify the length of time to wait until a warning is triggered when the capacity of a mirror repository volume reaches the defined percentage. Define the threshold by percentage (%) of the capacity remaining.

a|
`autoResync`
a|
The settings for automatic resynchronization between the primary volumes and the secondary volumes of an asynchronous mirrored pair within an asynchronous mirror group. This parameter has these values:

* `enabled` -- Automatic resynchronization is turned on. You do not need to do anything further to resynchronize the primary volume and the secondary volume.
* `disabled` -- Automatic resynchronization is turned off. To resynchronize the primary volume and the secondary volume, you must run the `resume asyncMirrorGroup` command.

|===

== Notes

* The Asynchronous Mirroring feature must be enabled and activated on the local and remote storage arrays that will be used for mirror activities.
* You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.
* The local and remote storage arrays must be connected through a Fibre Channel fabric or iSCSI interface.
* Passwords are stored on each storage array in a management domain. If a password was not previously set, you do not need a password. The password can be any combination of a alphanumeric characters with a maximum of 30 characters. (You can define a storage array password by using the `set storageArray` command.)
* Depending on your configuration, there is a maximum number of asynchronous mirror groups you can create on a storage array.
* Asynchronous mirror groups are created empty and mirrored pairs are added to them later on. Only mirrored pairs can be added to an asynchronous mirror group. Each mirrored pair is associated with exactly one asynchronous mirror group.
* The Asynchronous Mirroring process is initiated at a defined synchronization interval. Periodic point-in-time images are replicated as only the changed data is copied and not the entire volume.

== Minimum firmware level

7.84
