---
permalink: commands-a-z/create-hostgroup.html
sidebar: sidebar
keywords: 
summary: 'The create hostGroup command creates a new host group.'
---
= Create host group
:icons: font
:imagesdir: ./media/

[.lead]
The `create hostGroup` command creates a new host group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
create hostGroup userLabel="hostGroupName"
----

== Parameter

|===
| Parameter| Description
a|
`userLabel`
a|
The name that you want to give the host group that you are creating. Enclose the host group name in double quotation marks (" ").
|===

== Notes

A host group is an optional topological element that you can define if you want to designate a collection of hosts that share access to the same volumes. The host group is a logical entity. Define a host group only if you have two or more hosts that can share access to the same volumes.

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

5.20
