---
permalink: /commands-a-z/delete-auditlog.html
sidebar: sidebar
keywords: 
summary: 'The delete auditLog command deletes some or all of the records in the audit log.'
---
= Delete audit log records
:icons: font
:imagesdir: ./media/

[.lead]
The `delete auditLog` command deletes some or all of the records in the audit log.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

delete auditLog (all | (endRecord=timestamp | endDate=date) |
 (retentionCount=integer))
----

== Parameters

|===
| Parameter| Description
a|
`all`
a|
Allows you to delete all audit log records.
a|
`endRecord`
a|
Allows you to specify the ending record to delete, starting from the oldest record. The value is the integral value that represents the time stamp of the last audit log record, inclusive.
a|
`endDate`
a|
Allows you to specify the ending date to delete, starting from the oldest record. The format for entering the date is MM:DD:YY in the client time zone.
[NOTE]
====
The audit log records, including the date specified, will be deleted.
====

a|
`retentionCount`
a|
Allows you to specify the number of the newest audit log records to be retained.
|===

== Examples

----

SMcli -n Array1 -c "delete auditLog all;"

SMcli -n Array1 -c "delete auditLog endRecord=1493070393313;"

SMcli -n Array1 -c "delete auditLog endDate=04:30:17;"

SMcli -n Array1 -c "delete auditLog retentionCount=1000;"

SMcli completed successfully.
----

== Minimum firmware level

8.40
