---
permalink: commands-a-z/delete-host.html
sidebar: sidebar
keywords: delete, host
summary: "The delete host command deletes one or more hosts."
---
= Delete host
:icons: font
:imagesdir: ./media/

[.lead]
The `delete host` command deletes one or more hosts.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
----
delete host pass:quotes[[_hostName_]]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`host`
a|
The name of the host that you want to delete. Enclose the host name in square brackets ([ ]). If the host name has special characters, you must enclose the host name in double quotation marks (" ") inside square brackets.
|===

== Notes

A host is a computer that is attached to the storage array and accesses the volumes on the storage array through the host ports on the host.

== Minimum firmware level

5.20
