---
permalink: commands-a-z/delete-hostport.html
sidebar: sidebar
keywords: delete, hostport, command, host, port, identification
summary: "The delete hostPort command deletes a host port identification."
---
= Delete host port
:icons: font
:imagesdir: ../media/

[.lead]
The `delete hostPort` command deletes a host port identification.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

The identification is a software value that represents the physical host port to the controller. By deleting the identification, the controller no longer recognizes instructions and data from the host port.

[IMPORTANT]
====
This command does not work in an iSCSI environment, where the host ports are considered initiators. Instead, use the `delete iscsiInitiator` command. See xref:delete-iscsiinitiator.adoc[Delete iSCSI initiator].
====

== Syntax
[source,cli]
----
delete hostPort [hostPortName]
----

== Parameter
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`hostPort`
a|
The name of the host port that you want to delete. Enclose the name of the host port in square brackets ([ ]). If the host port name contains special characters or consists only of numbers, you also must enclose the name in double quotation marks (" ") inside square brackets.
|===

== Notes

A host port is a physical connection on a host adapter that resides within a host computer. A host port provides a host access to the volumes in a storage array.

== Minimum firmware level

5.20
