---
permalink: commands-a-z/delete-initiator.html
sidebar: sidebar
keywords: delete, initiator, command, object, supported, array, role
summary: "The delete initiator command deletes the initiator object."
---
= Delete initiator
:icons: font
:imagesdir: ../media/

[.lead]
The `delete initiator` command deletes the initiator object.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[IMPORTANT]
====
This command replaces the deprecated xref:delete-iscsiinitiator.adoc[Delete iSCSI initiator] command.
====

[NOTE]
====
This command is applicable only to iSCSI, iSER, NVMe over RoCE, NVMe over InfiniBand, and NVMe over Fibre Channel.
====

== Syntax
[source,cli]
----
delete initiator (["initiatorName"] | <"initiatorQualifiedName">)
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`initiator`
a|
Allows you to specify the initiator identifier for which you want to delete. Enclose the name in double quotation marks ("` "`). You also must enclose the name in square brackets ([ ]) if the value is a user label or angle brackets (< >) if the value is a qualified name (for example, iqn or nqn).
|===

== Minimum firmware level

8.41
