---
permalink: commands-a-z/delete-snmpcommunity.html
sidebar: sidebar
keywords: delete, snmpcommunity, command, existing, simple, network, management, protocol, community, previously, create, effective, unregister, trap, destination, associate, remove
summary: "The delete snmpCommunity command deletes an existing Simple Network Management Protocol (SNMP) community that you previously created and registered using the create snmpCommunity command. Deleting an SNMP community effectively unregisters the community. Any trap destinations associated with that community are also removed."
---
= Unregister SNMP community
:icons: font
:imagesdir: ./media/

[.lead]
The `delete snmpCommunity` command deletes an existing Simple Network Management Protocol (SNMP) community that you previously created and registered using the `create snmpCommunity` command. Deleting an SNMP community effectively unregisters the community. Any trap destinations associated with that community are also removed.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[delete snmpCommunity communityName="_snmpCommunityName_"]
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`communityName`
a|
The name of the SNMP community that you want to delete. Enclose the SNMP community name in double quotation marks (" ").
|===

== Minimum firmware level

8.30
