---
permalink: /commands-a-z/diagnose-asyncmirrorgroup.html
sidebar: sidebar
keywords: 
summary: 'The diagnose asyncMirrorGroup command tests possible communication problems between the local storage array and the remote storage array associated with an asynchronous mirror group.'
---
= Test asynchronous mirror group connectivity
:icons: font
:imagesdir: ./media/

[.lead]
The `diagnose asyncMirrorGroup` command tests possible communication problems between the local storage array and the remote storage array associated with an asynchronous mirror group.

== Supported Arrays

This command applies to any individual storage array, with some restrictions. If you are running the command on the E2700 or E5600 array, there are no restrictions.

[NOTE]
====
If you are running the command on the E2800 or E5700 array, the client type must be set to `symbol`. This command will not execute if they client type is set to `https`.
====

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin role.

== Syntax

----
diagnose asyncMirrorGroup [asyncMirrorGroupName]
testID=(all | connectivity | latency | bandwidth | portConnections)
----

== Parameter

|===
| Parameter| Description
a|
`asyncMirrorGroup`
a|
The name of an existing asynchronous mirror group that you want to test. Enclose the asynchronous mirror group name in square brackets ([ ]). If the asynchronous mirror group name has special characters or numbers, you must enclose the asynchronous mirror group name in double quotation marks (" ") inside square brackets.

a|
`testID`
a|
The identifier for the diagnostic test you want to run. The identifier and corresponding tests are as follows:

* All -- Performs all the tests associated with this command.
* Connectivity -- Verifies that the two controllers have a communication path. The connectivity test sends an inter-controller message between the storage arrays, and then validates that the corresponding asynchronous mirror group on the remote storage array exists. It also validates that the volume members of the asynchronous mirror group on the remote system match the volume members of the asynchronous mirror group on the local system.
* Latency -- Sends a SCSI test unit command to each volume on the remote storage array associated with the asynchronous mirror group to test the minimum, average, and maximum latency.
* Bandwidth -- Sends two inter-controller messages to the remote storage array to test the minimum, average, and maximum bandwidth as well as the negotiated link speed of the port on the controller performing the test.
* Port connections -- Shows the port that is being used for mirroring on the local storage array and the port that is receiving the mirrored data on the remote storage array.

|===

== Minimum firmware level

7.84
