---
permalink: commands-a-z/diagnose-syncmirror.html
sidebar: sidebar
keywords: diagnose, syncmirror, command, test, connection, specified, primary, volumes, mirror, storage, array, synchronous, feature, enabled
summary: "The diagnose syncMirror command tests the connection between the specified primary volumes and the mirror volumes on a storage array with the synchronous mirroring feature enabled."
---
= Diagnose synchronous mirroring
:icons: font
:imagesdir: ./media/

[.lead]
The `diagnose syncMirror` command tests the connection between the specified primary volumes and the mirror volumes on a storage array with the synchronous mirroring feature enabled.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
In previous versions of this command the feature identifier was `remoteMirror`. This feature identifier is no longer valid and is replaced by `syncMirror`.
====

== Syntax
[subs=+macros]
----
pass:quotes[diagnose syncMirror (_primary [primaryVolumeName_]] |pass:quotes[primaries ["_primaryVolumeName1_]" ... pass:quotes[_"primaryVolumeNameN"_]])
testID=connectivity
----

== Parameter
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`primary`
a|
The name of the primary volume of the remote mirror pair that you want to test. Enclose the primary volume name in square brackets ([ ]). If the primary volume name has special characters or consists only of numbers, you must enclose the primary volume name in double quotation marks (" ") inside square brackets.

a|
`primaries`
a|
You can enter more than one volume name. Enclose all of the volume names in one set of square brackets ([ ]). Enclose each volume name in double quotation marks (" "). Separate each volume name with a space.

The names of several volumes that you want you want to use as primary volumes. Enter the names of the primary volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

|===

== Minimum firmware level

6.10
