---
permalink: commands-a-z/download-storagearray-firmware.html
sidebar: sidebar
keywords: download, storage, array, firmware, command, downloads, optionally, values, controllers, role, context, parameter
summary: "The download storageArray firmware command downloads firmware and, optionally, NVSRAM values for the storage array controller."
---
= Download storage array firmware/NVSRAM
:icons: font
:imagesdir: ./media/

[.lead]
The `download storageArray firmware` command downloads firmware and, optionally, NVSRAM values for the storage array controller.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

If you want to download only NVSRAM values, use the `downLoad storageArray NVSRAM` command.

== Syntax
[subs=+macros]
----
download storageArray firmware [, NVSRAM ]
pass:quotes[file="_filename_" [, "_NVSRAM-filename_"]]
[downgrade=(TRUE | FALSE)
activateNow=(TRUE | FALSE)
healthCheckMelOverride=(TRUE | FALSE)
healthCheckNeedsAttnOverride=(TRUE | FALSE)
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`NVSRAM`
a|
This parameter downloads a file with NVSRAM values when you download a firmware file. Do not include square brackets with this parameter. Include a comma after the `firmware` parameter.
a|
`file`
a|
This parameter specifies the file path and the file name that contains the firmware. Enclose the file path and the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\dnld\safrm.dlp"`

Valid file names have a `.dlp`  extension.

a|
`NVSRAM-filename`
a|
This parameter specifies the file path and the file name that contains the NVSRAM values. Enclose the NVSRAM file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\dnld\safrm.dlp"` Valid file names have a `.dlp`  extension.

Include a comma before the file name when you download both firmware and NVSRAM.

a|
`downgrade`
a|

[ATTENTION]
====
*Possible damage to the storage array configuration* -- Downloading a previous version of the controller firmware or NVSRAM incorrectly can result in damage to the controllers or a loss of data access. Contact technical support before using this parameter.
====

This setting allows a previous version of firmware to be loaded. The default value is `FALSE`. Set the `*downgrade*` parameter to `TRUE` if you want to download an earlier version of firmware.

[NOTE]
====
This parameter is not valid when you are only downloading NVSRAM.
====

a|
`activateNow`
a|
This setting activates the firmware image and the NVSRAM image. The default value is `TRUE`. If you set the `activateNow` parameter to `FALSE`, you must run the `activate storageArray firmware` command to activate the firmware and the NVSRAM at a later time.
[NOTE]
====
This parameter is not valid when you are only downloaded NVSRAM.
====

a|
`healthCheckMelOverride`
a|
This setting overrides the results of the health check of the major event log (MEL). MEL validation still occurs; it is not bypassed. If the MEL check fails, you can bypass the failure by using this parameter when running the command.

Before any download, the controller checks the event log to determine if an event has occurred that might prevent the new controller firmware from successfully downloading. If such an event has occurred, the controller will normally not download new firmware.

This parameter forces the controller to download new firmware. The default value is `FALSE`. Set this value to `TRUE` if you want to force the controller to download new controller firmware.

a|
`healthCheckNeedsAttnOverride`
a|
This setting overrides the health check results from specific set of Needs Attention conditions. Needs Attention validation for a specific set of conditions still occurs; it is not bypassed. If the Needs Attention check fails, you can bypass the failure by using this parameter when running the command.

Before any download, the controller checks a specific set of Needs Attention conditions to determine if a failure has occurred that might prevent the new controller firmware from successfully downloading. If such an event has occurred, the controller will normally not download new firmware.

This parameter forces the controller to download new firmware. The default value is `FALSE`. Set this value to `TRUE` if you want to force the controller to download new controller firmware.

|===

== Minimum firmware level

5.00

8.10 adds the `*healthCheckMelOverride*` parameter.

8.70 adds `*healthCheckNeedsAttnOverride*` parameter.
