---
permalink: commands-a-z/download-tray-firmware-file.html
sidebar: sidebar
keywords: 
summary: 'The download tray firmware file command downloads environmental services module \(ESM\) firmware.'
---
= Download environmental card firmware
:icons: font
:imagesdir: ./media/

[.lead]
The `download tray firmware file` command downloads environmental services module (ESM) firmware.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

[NOTE]
====
On duplex systems managed by System Manager (for example, E2800), there is an IOM Auto-Synchronization Service running on the controllers that will automatically sync the IOM firmware with the version contained in the SANtricity OS bundle that is loaded on the controllers. If you do not want the IOM firmware to be reverted to match the version loaded on the controllers, you will need to disable this service. The IOM Auto-Synchronization Service can be suspended using the System Manager or the REST API. When suspending this service, be aware that leaving auto-synchronization enabled ensures the IOM firmware is up to date.
====

== Syntax

----
download (allTrays | tray [trayID])
firmware file="filename"
----

== Parameters

|===
| Parameter| Description
a|
`allTrays`
a|
This parameter downloads new firmware to all of the compatible trays in the storage array. The firmware package you select determines which trays are compatible. Incompatible trays are skipped. No error message is displayed about incompatible trays.
a|
`tray`
a|
The drive tray that contains the ESM card to which you want to load new firmware. Tray ID values are `0` to `99`. Enclose the tray ID value in square brackets ([ ]).
[NOTE]
====
There can be no leading zero in the tray ID. For example, if the displayed tray ID is "02," this command requires it to be specified as [2], not [02].
====

a|
`file`
a|
The file path and the file name of the file that contains the firmware image. Enclose the file path and the file name of the firmware image in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\dnld\esmfrm.esm"`

Valid file names have an `.esm`  extension.

|===

== Notes

The `tray` parameter downloads new firmware to a specific drive tray. If you need to download new firmware to more than one drive tray, but not all drive trays, you must enter this command for each drive tray.

== Minimum firmware level

5.20
