---
permalink: commands-a-z/download-controller-cacertificate.html
sidebar: sidebar
keywords: download, controller, certificate, command, install, root, intermediate, web, servers, validate, array, roles, context
summary: "The download controller caCertificate command installs the root/intermediate CA certificates on the controllers’ web servers to validate the web server signed certificate."
---
= Install root/intermediate CA certificates
:icons: font
:imagesdir: ./media/

[.lead]
The `download controller caCertificate` command installs the root/intermediate CA certificates on the controllers' web servers to validate the web server signed certificate.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

Perform this action for each controller.

== Syntax
[subs=+macros]
----

download controller[(a|b)] caCertificate pass:quotes[[alias="_string_"]]
         pass:quotes[file="_filename_"]
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`controller`
a|
Allows you to specify the controller on which you want to install the root/intermediate signed certificate. Valid controller identifiers are a or b, where a is the controller in slot A, and b is the controller in slot B. Enclose the controller identifier in square brackets ([ ]).
a|
`alias`
a|
Allows you to specify an alias to represent the root/intermediate certificate. This alias is used to look up information about the root/intermediate certificates or to delete them. An alias is associated to a root/intermediate certificate and must be unique.
a|
`file`
a|
Allows you to specify the file that contains the root/intermediate CA certificate. The acceptable extensions are .pem, .cer, .crt, and .der.
|===

== Examples

----

SMcli -n Array1 -c "download controller[a] caCertificate alias="myAlias" file="C:\rootCA1.cer";"
SMcli -n Array1 -c "download controller[b] caCertificate file="C:\rootCA1.cer";"

SMcli completed successfully.
----

== Minimum firmware level

8.40
