---
permalink: commands-a-z/download-drive-firmware.html
sidebar: sidebar
keywords: download, drive, firmware, array, support, role, context, level
summary: "The download drive firmware command downloads a firmware image to a drive."
---
= Download drive firmware
:icons: font
:imagesdir: ./media/

[.lead]
The `download drive firmware` command downloads a firmware image to a drive.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

[CAUTION]
====
*Possible damage to the storage array configuration* -- Downloading drive firmware incorrectly can result in damage to the drives or a loss of data access.
====

[NOTE]
====
The `content` parameter is deprecated. Use the `firmware` parameter instead.
====

This command is intended for downloading a firmware image to only one drive model at a time. If you use this command in a script, make sure that you use this command only once. If you use this command more than once, the operation can fail. You can download firmware images to all of the drives in a storage array at one time by using the `download storageArray driveFirmware` command.

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[download (drive \[_trayID_,[_drawerID,_]pass:quotes[_slotID_] \| drives\ pass:quotes[[_trayID1_,[_drawerID1_,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
 [online|offline] firmware file="filename"
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`drive` or `drives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`online` or `offline`
a|
Select `online` to perform an online drive firmware download, otherwise select `offline`. The default value is `offline`.

a|
`file`
a|
The file path and the file name of the file that contains the firmware image. Enclose the file path and the file name of the firmware image in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\dnld\drvfrm.dlp"`

Valid file names have a `.dlp`  extension.

a|
`firmware`
a|
Indicates to download controller firmware.

|===

== Notes

Before trying to download drive firmware, take these precautions:

* Unless you are using the `online` parameter, stop all I/O activity to the storage array before you download the firmware image. The `download drive firmware` command without the `online` parameter blocks all I/O activity until the download finishes or fails; however, as a precaution, make sure that all I/O activity that might affect the drive is stopped.
* Make sure that the firmware image file is compatible with the drive tray. If you download a firmware image file that is not compatible with the drive tray that you have selected, the drive tray might become unusable.
* Do not make any configuration changes to the storage array while you download drive firmware. Trying to make a configuration change can cause the firmware download to fail and make the selected drives unusable.
* For online drive firmware update requests issued using this command, the controller will remove RAID 0 volume group drives from the list of drives to which new firmware is downloaded. Individual drive return status will be set to `Never Attempted With Reason`.

When you download the firmware to the drives, you must provide the full path and file name to the firmware image that is stored on your system.

You can use `download drive` command to test the firmware on one drive before you install the firmware on all of the drives in a storage array. The download returns one of these statuses:

* Successful
* Unsuccessful With Reason
* Never Attempted With Reason

The `drive` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0`, and specify the ID of the slot in which a drive resides.

== Minimum firmware level

7.60 adds the `drawerID` user input.

8.25 adds the `online` parameter.
