---
permalink: commands-a-z/download-storagearray-nvsram.html
sidebar: sidebar
keywords: download, storagearray, down, values, controller, support, role, command, array
summary: "The download storageArray NVSRAM command downloads the NVSRAM values for the storage array controller."
---
= Download storage array NVSRAM
:icons: font
:imagesdir: ./media/

[.lead]
The `download storageArray NVSRAM` command downloads the NVSRAM values for the storage array controller.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[download storageArray NVSRAM file="_filename_"]
[healthCheckMelOverride=(TRUE | FALSE)]
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`file`
a|
The file path and the file name that contains the NVSRAM values. Enclose the NVSRAM file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\dnld\afrm.dlp"`

Valid file names have a `.dlp`  extension.

a|
`healthCheckMelOverride`
a|
The setting to override the results of the health check of the major event log (MEL). MEL validation still occurs, it is not bypassed. If the MEL check fails, you can bypass the failure by using this parameter when running the command.

Before any download, the controller checks the event log to determine if an event has occurred that might prevent the new NVSRAM from successfully downloading. If such an event has occurred, the controller will normally not download new NVSRAM.

This parameter forces the controller to download new NVSRAM. The default value is `FALSE`. Set this value to `TRUE` if you want to force the controller to download new NVSRAM.

|===

== Minimum firmware level

6.10

8.10 adds the `healthCheckMelOverride` parameter.
