---
permalink: commands-a-z/enable-or-disable-autosupport-individual-arrays.html
sidebar: sidebar
keywords: command, enable, disable, autosupport, feature, storage, array, possible, transit, messages, technical, support, site, capable, automatically, prepare, collect, data, remote, troubleshooting, problem, analysis
summary: "This command enables or disables AutoSupport (ASUP) feature for the storage array and makes it possible to transmit messages to the technical support site. After you enable the ASUP feature, the ASUP-capable storage array is automatically prepared to collect and send support-related data to technical support. The data can then be used for remote troubleshooting and problem analysis."
---
= Enable or disable AutoSupport (all individual arrays)
:icons: font
:imagesdir: ../media/

[.lead]
This command enables or disables AutoSupport (ASUP) feature for the storage array and makes it possible to transmit messages to the technical support site. After you enable the ASUP feature, the ASUP-capable storage array is automatically prepared to collect and send support-related data to technical support. The data can then be used for remote troubleshooting and problem analysis.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

After enabling this feature, you can next enable the AutoSupport OnDemand feature (if desired), and then enable the AutoSupport Remote Diagnostics feature (if desired).

You must enable the three features in this order:
[START=1]
. *Enable AutoSupport*
. *Enable AutoSupport OnDemand*
. *Enable AutoSupport Remote Diagnostics*

== Syntax
[source,cli]
----
set storageArray autoSupport (enable | disable)
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`enable \| disable`
a|
Allows you to enable or disable AutoSupport. If the OnDemand and Remote Diagnostics features are enabled, the disable action will turn off OnDemand and Remote Diagnostics features as well.
|===

=== Examples

----

   SMcli -n Array1 -c "set storageArray autoSupport enable;"

   SMcli completed successfully.
----

== Verification

Use the `show storageArray autoSupport` command to see whether you have enabled the feature. The initial line of the displayed output shows the enable status:

----
The AutoSupport feature is enabled on this storage array.
----

== Minimum Firmware Level

7.86 - added command for all storage arrays up to model E2700 and E5600

8.40 - added support for the E2800 and E5700
