---
permalink: commands-a-z/load-storagearray-dbmdatabase.html
sidebar: sidebar
keywords: load, storage array, database, command, management
summary: "The load storageArray dbmDatabase command restores a Database Management (DBM) database image by retrieving the image from a file or from cache."
---
= Load storage array DBM database
:icons: font
:imagesdir: ./media/

[.lead]
The `load storageArray dbmDatabase` command restores a Database Management (DBM) database image by retrieving the image from a file or from cache.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

This command restores a storage array DBM database to the exact configuration that existed when the database image was captured using the `save storageArray dbmDatabase` command. The data in a file includes data for RAID configuration, volume groups and disk pools.

Before using this command with the `file` option, you must first obtain a validator string (a security code) from technical support. To obtain a validator, use the `save storageArray dbmValidatorInfo` command to generate an XML file that contains validator information. Technical support uses the XML file to generate the validator string required for this command.

== Syntax
[subs=+macros]
----
load storageArray dbmDatabase
pass:quotes[((file="_filename_" validator="_validatorValue_") | sourceLocation=onboard)]
[controller [(a|b)]]
[contentType= all]
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`file`
a|
The file path and the file name of the DBM database you want to upload. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Array Backups\DBMbackup_03302010.dbm"` This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

a|
`validator`
a|
The alphanumeric security code that is required to restore a storage array to an existing configuration.

You must get the validator from technical support. To get the validator, generate the required validation information XML file by running the `save storageArray dbmValidatorInfo` command. After the validation information XML file is available, contact technical support to get the validator.

Enclose the validator in double quotation marks (" ").

a|
`sourceLocation`
a|
This parameter specifies the location from which to retrieve backup database information. The parameter must be included for consistency, but the only allowed value is `onboard`.
a|
`controller`
a|
This parameter specifies the controller from which data will be exclusively retrieved. Enclose the controller identifier in square brackets ([ ]). If the `controller` parameter is not specified, data might be retrieved from either controller.

Valid controller identifiers are `a` or `b`, where `a` is the controller in slot A, and `b` is the controller in slot B.

a|
`contentType`
a|
This parameter specifies the content type of the data that will be retrieved.

This parameter is set to `all` by default, so that all of the data including disk pool configuration data is retrieved.

|===

== Notes

Depending on the size of the database image, restoring the database might take up as much as 30 minutes. The host software will not show the controllers in an Optimal state until after all actions for loading the database image are completed on the controllers.

== Minimum firmware level

7.75

7.83 adds these parameters:

* sourceLocation
* controller
* contentType
