---
permalink: commands-a-z/recopy-volumecopy-target.html
sidebar: sidebar
keywords: volumecopy, target, command, operation, volume, copy, pair, reinitiate, array, role, context
summary: "The recopy volumeCopy target command reinitiates a volume copy operation using an existing volume copy pair."
---
= Recopy volume copy
:icons: font
:imagesdir: ../media/

[.lead]
The `recopy volumeCopy target` command reinitiates a volume copy operation using an existing volume copy pair.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
With firmware version 7.83 the `copyType=(online | offline)` parameter is no longer used.
====

This command is valid for snapshot image volume copy pairs.

This command works with volume copy pairs that you created with a snapshot image volume.

[NOTE]
====
Starting a volume copy operation overwrites all existing data on the target volume, makes the target volume read-only to hosts, and fails all snapshot image volumes associated with the target volume, if any exist. If you have used the target volume as a copy before, be sure you no longer need the data or have it backed up.
====

== Syntax
[source,cli]
----
recopy volumeCopy target [targetName]
[source [sourceName]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`target`
a|
The name of the target volume for which you want to reinitiate a volume copy operation. Enclose the target volume name in square brackets ([ ]). If the target volume name has special characters, you must enclose the target volume name in double quotation marks (" ") inside square brackets.
a|
`source`
a|
The name of the source volume for which you want to reinitiate a volume copy operation. Enclose the source volume name in square brackets ([ ]). If the source volume name has special characters, you must enclose the source volume name in double quotation marks (" ") inside square brackets.
a|
`copyPriority`
a|
The priority that the volume copy has relative to host I/O activity. Valid values are `highest`, `high`, `medium`, `low`, or `lowest`.
a|
`targetReadOnlyEnabled`
a|
The setting so that you can write to the target volume or only read from the target volume. To write to the target volume, set this parameter to `FALSE`. To prevent writing to the target volume, set this parameter to `TRUE`.
|===

== Notes

Copy priority defines the amount of system resources that are used to copy the data between the source volume and the target volume of a volume copy pair. If you select the highest priority level, the volume copy uses the most system resources to perform the volume copy, which decreases performance for host data transfers.

== Minimum firmware level

6.10

7.83 removes the `copyType=(online | offline)` parameter.
