---
permalink: commands-a-z/recreate-storagearray-securitykey.html
sidebar: sidebar
keywords: recreate, external, security key
summary: "The recreate storageArray securityKey command regenerates a storage array security key for use with the external security key management feature."
---
= Re-create external security key
:icons: font
:imagesdir: ./media/

[.lead]
The `recreate storageArray securityKey` command regenerates a storage array security key for use with the external security key management feature.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command applies only to external key management.
====

== Syntax
[subs=+macros]
[source,cli]
----
recreate storageArray securityKey
passPhrase=pass:quotes[_"passPhraseString"_
file="_fileName"_]
[deleteOldKey=(TRUE | FALSE)]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`passPhrase`
a|
A character string that encrypts the security key so that you can store the security key in an external file. Enclose the pass phrase in double quotation marks (" ").
a|
`file`
a|
The file path and the file name that has the security key. For example:

----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----

[NOTE]
====
The file name must have an extension of `.slk`.
====

a|
`deleteOldKey`
a|
Set this parameter to `TRUE` to delete the old security key from the external key management server after the new security key is created. The default is `FALSE`.

|===

== Notes

Your pass phrase must meet these criteria:

* The pass phrase must be between eight and 32 characters long.
* The pass phrase must contain at least one uppercase letter.
* The pass phrase must contain at least one lowercase letter.
* The pass phrase must contain at least one number.
* The pass phrase must contain at least one non-alphanumeric character, for example, < > @ +.

[NOTE]
====
If your pass phrase does not meet these criteria, you will receive an error message.
====

== Minimum firmware level

7.70

11.73 adds the `deleteOldKey` parameter.
