---
permalink: commands-a-z/remove-drives-from-ssd-cache.html
sidebar: sidebar
keywords: remove, drives, ssd, cache
summary: "The set ssdCache command decreases the capacity of the SSD cache by removing Solid State Disks (SSDs)."
---
= Remove drives from SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `set ssdCache` command decreases the capacity of the SSD cache by removing Solid State Disks (SSDs).

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Syntax
[subs=+macros]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache from which you want to remove SSDs. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or consists only of numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
a|
`removeDrives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

|===

== Notes

You cannot remove all of the SSDs from the SSD cache using this command; at least one SSD must remain in the SSD cache. If you want to completely remove the SSD cache, use the `delete ssdCache` command instead.

== Minimum firmware level

7.84
