---
permalink: commands-a-z/remove-volume-asyncmirrorgroup.html
sidebar: sidebar
keywords: remove, volume, asynchronous, mirror, group
summary: "The remove volume asyncMirrorGroup command removes a member volume from an existing asynchronous mirror group."
---
= Remove volume from asynchronous mirror group
:icons: font
:imagesdir: ./media/

[.lead]
The `remove volume asyncMirrorGroup` command removes a member volume from an existing asynchronous mirror group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, or E5700 storage array, you must have the Storage Admin role.

== Context

Optionally, you can delete the repository volume members from the asynchronous mirror group.

This command is valid only on the local storage array that contains the asynchronous mirror group whose member volume that you want to remove.

== Syntax
[subs=+macros]
----
remove volume pass:quotes[[_"volumeName"_]] asyncMirrorGroup=pass:quotes[_"asyncMirrorGroupName"_]
[deleteRepositoryMembers=(TRUE | FALSE)]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`volume`
a|
The name of the specific volume that you want to remove from the asynchronous mirror group. Enclose the volume name in double quotation marks (" ") inside square brackets ([ ]).

a|
`asyncMirrorGroup`
a|
The name of the asynchronous mirror group that contains the member volume that you want to remove. Enclose the asynchronous mirror group name in double quotation marks (" ").

a|
`deleteRepositoryMembers`
a|
Determines whether to remove all of the repository members from the asynchronous mirror group.
|===

== Minimum firmware level

7.84
