---
permalink: commands-a-z/rename-ssd-cache.html
sidebar: sidebar
keywords: rename, ssd, cache
summary: "The set ssdCache command changes the name of the SSD cache."
---
= Rename SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `set ssdCache` command changes the name of the SSD cache.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600, and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Support Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set ssdCache pass:quotes[[_old_ssdCacheName_]] userLabel=pass:quotes[_"new_ssdCacheName_"]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache that you want to rename. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or consists only of numbers, you also must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
a|
`userLabel`
a|
The new name for the SSD cache. Enclose the name in double quotation marks (" ").You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the identifier. Identifiers can have a maximum of 30 characters.
|===

== Minimum firmware level

7.84

11.80 adds EF600 and EF300 array support
