---
permalink: commands-a-z/rename-ssd-cache.html
sidebar: sidebar
keywords: 
summary: 'The set ssdCache command changes the name of the SSD cache.'
---
= Rename SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `set ssdCache` command changes the name of the SSD cache.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Syntax

----
set ssdCache [old_ssdCacheName] userLabel="new_ssdCacheName"
----

== Parameter

|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache that you want to rename. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or consists only of numbers, you also must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
a|
`userLabel`
a|
The new name for the SSD cache. Enclose the name in double quotation marks (" ").You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the identifier. Identifiers can have a maximum of 30 characters.
|===

== Minimum firmware level

7.84
