---
permalink: /commands-a-z/reset-storagearray-iscsistatsbaseline.html
sidebar: sidebar
keywords: 
summary: 'The reset storageArray iscsiStatsBaseline command resets the iSCSI baseline to 0 for the storage array.'
---
= Reset storage array iSCSI baseline
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray iscsiStatsBaseline` command resets the iSCSI baseline to 0 for the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

[NOTE]
====
This command is deprecated and is replaced by the xref:wombat-reset-storagearray-hostportstatisticsbaseline.adoc[Reset storage array host port statistics baseline] command.
====

== Syntax

----
reset storageArray iscsiStatsBaseline
----

== Parameters

None.

== Notes

This command resets the baseline to 0 for both controllers in the storage array. The purpose of resetting both of the controller baselines is to help make sure that the controller counts are synchronized between the controllers. If one controller resets but the second controller does not reset, the host is informed that the controllers are out of synchronization. The host is informed by the time stamps that are reported with the statistics.

== Minimum firmware level

7.10

8.41 This command is deprecated.
