---
permalink: commands-a-z/reset-controller-arraymanagementsignedcertificate.html
sidebar: sidebar
keywords: reset, installed, signed, certificate
summary: "The reset controller arrayManagementSignedCertificate command resets the installed signed certificate and root/intermediate certificates on the controller. All root and intermediate certificates as well as any signed certificates will be replaced by a single self-signed certificate."
---
= Reset installed signed certificate
:icons: font
:imagesdir: ./media/

[.lead]
The `reset controller arrayManagementSignedCertificate` command resets the installed signed certificate and root/intermediate certificates on the controller. All root and intermediate certificates as well as any signed certificates will be replaced by a single self-signed certificate.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

reset controller [(a|b)] arrayManagementSignedCertificate
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`controller`
a|
Allows the user to specify the controller on which you want to retrieve the root/intermediate certificates. Valid controller identifiers are a or b, where a is the controller in slot A, and b is the controller in slot B. Enclose the controller identifier in square brackets ([ ]).
|===

== Examples

----

SMcli -n Array1 -c "reset controller [a] arrayManagementSignedCertificate;"

SMcli completed successfully.
----

== Minimum firmware level

8.40
