---
permalink: commands-a-z/reset-storagearray-volumedistribution.html
sidebar: sidebar
keywords: reset, storage array, volume, distribution
summary: "The reset storageArray volumeDistribution command reassigns (moves) all of the volumes to their preferred controller."
---
= Reset storage array volume distribution
:icons: font
:imagesdir: ../media/

[.lead]
The `reset storageArray volumeDistribution` command reassigns (moves) all of the volumes to their preferred controller.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[source,cli]
----
reset storageArray volumeDistribution
----

== Parameters

None.

== Notes

If you use this command on a host without a multi-path driver, you must stop I/O operations to the volumes until this command has completed to prevent application errors.

Under certain host operating system environments, you might be required to reconfigure the multi-path host driver. You might also need to make operating system modifications to recognize the new I/O path to the volumes.

== Minimum firmware level

5.20
