---
permalink: commands-a-z/reset-storagearray-diagnosticdata.html
sidebar: sidebar
keywords: reset ,storage, array, diagnostic, data
summary: "The reset storageArray diagnosticData command resets the NVSRAM that contains the diagnostic data for the storage array."
---
= Reset storage array diagnostic data
:icons: font
:imagesdir: ./media/

[.lead]
The `reset storageArray diagnosticData` command resets the NVSRAM that contains the diagnostic data for the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This command does not delete the diagnostic data. This command replaces the Needs Attention status with the Diagnostic Data Available status. The old diagnostic data is written over automatically when new data is captured. The memory that contains the diagnostic data is also cleared when the controllers reboot. Before you reset the diagnostic data, use the `save storageArray diagnosticData` command to save the diagnostic data to a file.

[NOTE]
====
Run this command only with the assistance of technical support.
====

== Syntax

----
reset storageArray diagnosticData
----

== Parameters

None.

== Minimum firmware level

6.16
