---
permalink: commands-a-z/resume-snapvolume.html
sidebar: sidebar
keywords: resume, snapshot, volume
summary: "The resume snapVolume command resumes a snapshot volume operation that was stopped."
---
= Resume snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `resume snapVolume` command resumes a snapshot volume operation that was stopped.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
resume snapVolume pass:quotes[[_"snapVolumeName"_]] snapImage=pass:quotes[_"snapCGID:imageID"_]
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`snapVolume`
a|
The name of the snapshot volume for which you want to resume operations. Enclose the snapshot volume name in double quotation marks (" ") inside square brackets ([ ]).
a|
`snapImage`
a|
The name of the snapshot image for which you want to resume snapshot volume operations. The name of a snapshot image is comprised of two parts:

* The name of the snapshot group
* An identifier for the snapshot image in the snapshot group

The identifier for the snapshot image can be one of these:

* An integer value that is the sequence number of the snapshot in the snapshot group.
* `NEWEST` - Use this option when you want to show the latest snapshot image created in the snapshot group.
* `OLDEST` - Use this option when you want to show the earliest snapshot image created in the snapshot group.

Enclose the snapshot image name in double quotation marks (" ").

|===

== Notes

The name of a snapshot image has two parts separated by a colon (:):

* The identifier of the snapshot group
* The identifier of the snapshot image

For example, if you want to resume snapshot volume operations for snapshot image 12345 in a snapshot group that has the name snapGroup1, you would use this command:

----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:12345";
----

To resume snapshot volume operations for the most recent snapshot image in a snapshot group that has the name snapGroup1, you would use this command:

----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:newest";
----

== Minimum firmware level

7.83
