---
permalink: commands-a-z/resume-ssdcache.html
sidebar: sidebar
keywords: resume, ssd, cache
summary: "The resume ssdCache command restarts the caching for all of the volumes using the SSD cache that was temporarily stopped with the suspend ssdCache command."
---
= Resume SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `resume ssdCache` command restarts the caching for all of the volumes using the SSD cache that was temporarily stopped with the `suspend ssdCache` command.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Syntax
[subs=+macros]
----
resume ssdCache pass:quotes[[_ssdCacheName_]]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache for which you want to resume caching operations. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or consists only of numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
|===

== Minimum firmware level

7.84
