---
permalink: commands-a-z/revive-snapgroup.html
sidebar: sidebar
keywords: revive, snapshot, group
summary: "The revive snapGroup command forces the specified snapshot group to the Optimal state."
---
= Revive snapshot group
:icons: font
:imagesdir: ./media/

[.lead]
The `revive snapGroup` command forces the specified snapshot group to the Optimal state.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

If the snapshot group is not in a Failed state, the firmware displays an error message and does not run this command.

== Syntax
[subs=+macros]
[source,cli]
----
revive snapGroup pass:quotes[[_snapGroupName_]]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`snapGroup`
a|
The name of the snapshot group that you want to set to the Optimal state. Enclose the snapshot group name in square brackets ([ ]). If the snapshot group name has special characters or consists only of numbers, you must enclose the snapshot group name in double quotation marks (" ") inside square brackets.
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

7.83
