---
permalink: commands-a-z/revive-snapvolume.html
sidebar: sidebar
keywords: revive, snapshot, volume
summary: "The revive snapVolume command forces a specified snapshot volume to the Optimal state."
---
= Revive snapshot volume
:icons: font
:imagesdir: ./media/

[.lead]
The `revive snapVolume` command forces a specified snapshot volume to the Optimal state.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

The snapshot volume can be one of the following:

* A standalone snapshot volume
* A snapshot volume that is a member of a consistency group

If the snapshot volume is not in a Failed state, the firmware displays an error message and does not run this command.

[NOTE]
====
You cannot use this command for a snapshot volume that is used in online volume copy.
====

== Syntax
[subs=+macros]
----
revive snapVolume pass:quotes[[_snapVolumeName_]]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`snapVolume`
a|
The name of the snapshot volume that you want to set to the Optimal state. Enclose the snapshot volume name in square brackets ([ ]). If the snapshot volume name has special characters or consists only of numbers, you must enclose the snapshot volume name in double quotation marks (" ") inside square brackets.
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

7.83
