---
permalink: commands-a-z/revive-volumegroup.html
sidebar: sidebar
keywords: revive, volume, group
summary: "The revive volumeGroup command forces the specified volume group and its associated failed drives to the Optimal state."
---
= Revive volume group
:icons: font
:imagesdir: ../media/

[.lead]
The `revive volumeGroup` command forces the specified volume group and its associated failed drives to the Optimal state.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

[NOTE]
====
*Possible loss of data access* -- Correct use of this command depends on the data configuration on all of the drives in the volume group. Never try to revive a drive unless you are supervised by technical support.
====

== Syntax
[subs=+macros]
[source,cli]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----

== Parameter
[options="header"]
|===
| Parameter| Description
a|
`volumeGroup`
a|
The name of the volume group to be set to the Optimal state. Enclose the volume group name in square brackets ([ ]).
|===

== Minimum firmware level

6.10
