---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html
sidebar: sidebar
keywords: retrieve, installed, server, certificate, sign, request, csr
summary: "The save controller arrayManagementCSR command retrieves the installed server Certificate Signing Request (CSR) for the controller so you can view certificate details."
---
= Retrieve installed server certificate
:icons: font
:imagesdir: ../media/

[.lead]
The `save controller arrayManagementCSR` command retrieves the installed server Certificate Signing Request (CSR) for the controller so you can view certificate details.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

[subs=+macros]
[source,cli]
----

save controller [(a|b)] arrayManagementCSR file=pass:quotes["_filename_"]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`controller`
a|
Allows you to specify the controller on which you want to download the signed certificate from. Valid controller identifiers are a or b, where a is the controller in slot A, and b is the controller in slot B. Enclose the controller identifier in square brackets ([ ]).
a|
`file`
a|
Allows you to specify the file for which to save the controller's signed certificate file.
|===

== Examples

----

SMcli -n Array1 -c "save controller [a] aarrayManagementCSR
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementCSR
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----

== Minimum firmware level

8.40
