---
permalink: commands-a-z/save-storagearray-autosupport-log.html
sidebar: sidebar
keywords: retrieve, autosupport, log, individual, E2800, E5700, arrays
summary: "The save storageArray autoSupport log command allows you to view an AutoSupport log file. This file provides information about status, history of transmission activity, and any errors encountered during delivery of the AutoSupport messages. The log is available for all AutoSupport-capable and AutoSupport-enabled storage arrays."
---
= Retrieve an AutoSupport log
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray autoSupport log` command allows you to view an AutoSupport log file. This file provides information about status, history of transmission activity, and any errors encountered during delivery of the AutoSupport messages. The log is available for all AutoSupport-capable and AutoSupport-enabled storage arrays.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

This command allows you to view two types of logs:

* Current log -- View the log captured at this point in time.
* Archive log -- View the log from an archived file.

== Syntax
[subs=+macros]
[source,cli]
----
save storageArray autoSupport log [inputArchive=n]
file=pass:quotes["_filename_"]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`inputArchive`
a|
Allows you to specify the archived AutoSupport log, where the archive file is `n`, an integer starting at 0.

[NOTE]
====
Omitting this parameter means you select the current AutoSupport log (captured at this point in time).
====

a|
`file`
a|
Allows you to specify the output ASUP transmission log filename.
[NOTE]
====
This parameter is required.
====

|===

=== Examples

----

SMcli -n Array1 -c "save storageArray autoSupport log inputArchive=0 file=\"ASUPTransmissionLog\";"

SMcli completed successfully.
----

== Minimum Firmware Level

8.40
