---
permalink: /commands-a-z/save-storagearray-keymanagementclientcsr.html
sidebar: sidebar
keywords: 
summary: 'The save storageArray keyManagementClientCSR command requests a generated CSR for the storage array that you can save to a file.'
---
= Generate Key Management Certificate Signing Request (CSR)
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray keyManagementClientCSR` command requests a generated CSR for the storage array that you can save to a file.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command applies only to external key management.
====

== Syntax

----

save storageArray keyManagementClientCSR commonName="common_name"
organization="organization"
locality="locality"
country="country"
file="file"
[organizationalUnit="organizational_unit"]
[stateProvince="state_province"]
----

== Parameters

|===
| Parameter| Description
a|
`commonName`
a|
The value entered for this parameter must match one of the user names defined on the KMIP server.
a|
`organization`
a|
Allows you to specify the organization's full legal name that the storage array belongs to. Do not abbreviate it and include any suffixes such as Inc, Corp, or LLC.
a|
`locality`
a|
Allows you to specify the city or locality where the storage array is located,
a|
`country`
a|
Allows you to specify your country's two-digit ISO (International Organization for Standardization) 3166-1 alpha-2 code, such as US.
a|
`file`
a|
Allows you to specify the file and file location where you will save the controller's signed certificate file.
a|
`organizationalUnit`
a|
Allows you to specify the organization's division that handles the certificate.
a|
`stateProvince`
a|
Allows you to specify the state or region where the storage array is located. This should not be abbreviated.
|===

== Example

----

SMcli -n Array1 -c "save storageArray keyManagementClientCSR commonName="192.0.2.1 "
organization="Widgets Are Us, Inc."
locality="sedgwick"
country="US"
file="latestCertificate"
organizationalUnit="Products Unit"
stateProvince="Kansas";"

SMcli completed successfully.
----

== Minimum firmware level

8.40
