---
permalink: commands-a-z/save-storagearray-trustedcertificate.html
sidebar: sidebar
keywords: retrieve, installed, trusted, ca, certificates
summary: "The save storageArray trustedCertificate command retrieves the installed trusted CA certificates for the array. Included in the retrieved files are any requested CA certificates from the array’s web servers."
---
= Retrieve installed trusted CA certificates
:icons: font
:imagesdir: ../media/

[.lead]
The `save storageArray trustedCertificate` command retrieves the installed trusted CA certificates for the array. Included in the retrieved files are any requested CA certificates from the array's web servers.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
save storageArray trustedCertificate [allUserInstalled |
aliases=pass:quotes[("_alias1_" ... "_aliasN_")]] path=pass:quotes["_fileLocation_"]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`allUserInstalled`
a|
Allows you to specify the retrieval of user installed certificates. The default option is `allUserInstalled` if you didn't specify any aliases.
a|
`aliases`
a|
Allows you to specify which user installed trusted certificate to retrieve by alias. Enclose all the aliases in parentheses. If you enter more than one alias, separate them with a space.
a|
`path`
a|
Allows you to specify the local location for which to save the controller's trusted certificates.
|===

== Examples

----

SMcli -n Array1 -c "save storageArray trustedCertificate allUserInstalled path="C:\";"

SMcli -n Array1 -c "save storageArray trustedCertificate aliases=("myAlias" "anotherAlias") path="C:\";"

SMcli completed successfully.
----

== Minimum firmware level

8.40
