---
permalink: commands-a-z/save-drivechannel-faultdiagnostics-file.html
sidebar: sidebar
keywords: save, drive, channel, fault, isolation, diagnostic, status
summary: "The save driveChannel faultDiagnostics file command saves the drive channel fault isolation diagnostic data that is returned from the start driveChannel faultDiagnostics command."
---
= Save drive channel fault isolation diagnostic status
:icons: font
:imagesdir: ../media/

[.lead]
The `save driveChannel faultDiagnostics file` command saves the drive channel fault isolation diagnostic data that is returned from the `start driveChannel faultDiagnostics` command.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
With firmware version 8.10, the `save driveChannel faultDiagnostics` command is deprecated.
====

You can save the diagnostic data to a file as standard text or as XML.

== Syntax
[subs=+macros]
[source,cli]
----
save driveChannel faultDiagnostics file=pass:quotes["_filename_"]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`file`
a|
The file path and the file name to which you want to save the results of the fault isolation diagnostics test on the drive channel. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\sup\fltdiag.txt"`

This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

|===

== Notes

A file extension is not automatically appended to the saved file. You must specify the applicable format file extension for the file. If you specify a file extension of `.txt`, the output will be in a text file format. If you specify a file extension of `.xml` , the output will be in an XML file format.

== Minimum firmware level

7.15 introduces this new capability for legacy controller trays.
