---
permalink: commands-a-z/save-storagearray-sasphycounts.html
sidebar: sidebar
keywords: save, storage, array, sas, phy, counts
summary: "The save storageArray SASPHYCounts command saves the SAS physical layer (SAS PHY) counters to a file."
---
= Save storage array SAS PHY counts
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray SASPHYCounts` command saves the SAS physical layer (SAS PHY) counters to a file.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

To reset the SAS PHY counters, run the `reset storageArray SASPHYBaseline` command.

== Syntax

[subs=+macros]
----
save storageArray SASPHYCounts file=pass:quotes["_filename_"]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`file`
a|
The file path and the file name to which you want to save the SAS PHY counters. Enclose the file path and the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\sasphy.csv"`

The default name of the file that contains the SAS PHY error statistics is `sas-phy-error-log.csv`. You can use any file name, but you must use the `.csv` extension.

|===

== Minimum firmware level

6.10
