---
permalink: commands-a-z/save-storagearray-dbmdatabase.html
sidebar: sidebar
keywords: save, storage, array, dbm, database
summary: "The save storageArray dbmDatabase command backs up RAID configuration data or all data to a file on the host. You can specify multiple data locations and controllers."
---
= Save storage array DBM database
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray dbmDatabase` command backs up RAID configuration data or all data to a file on the host. You can specify multiple data locations and controllers.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----
save storageArray dbmDatabase
[sourceLocation=(disk | onboard)]
[controller [(a|b)]]
[contentType= all]
 file="fileName"
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*file*`
a|
The file path and the file name to which you want to save the database. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\dbmdata.zip"`

This parameter must appear last, after any of the optional parameters.

This command creates a .zip file and you do not need to specify a file extension.

a|
`*sourceLocation*`
a|
This parameter specifies the location from which to obtain backup database information.

* `disk` indicates that data comes directly from the database on the drive
* `onboard` indicates that data comes from the RPA memory location

The default location is `onboard`.
a|
`*controller*`
a|
This parameter specifies the controller from which data will be exclusively retrieved, if `*sourceLocation*` is set to `onboard`. If the `*controller*` parameter is not specified, data might be retrieved from either controller.

Valid controller identifiers are `a` or `b`, where `a` is the controller in slot A, and `b` is the controller in slot B.

a|
`*contentType*`
a|
This parameter specifies the content type of the data that will be retrieved.

This parameter is set to `all` by default, so that all of the data including disk pool configuration data is retrieved.

|===

== Notes

The data that you save to the host using this command can, if needed, be restored to the controller. A validator, however, is required to restore data from the file on the host.

== Minimum firmware level

7.75

7.83 adds these parameters:

* sourceLocation
* controller
* contentType
