---
permalink: commands-a-z/save-auditlog.html
sidebar: sidebar
keywords: 
summary: 'The save auditLog command retrieves the audit log records.'
---
= Save audit log records
:icons: font
:imagesdir: ./media/

[.lead]
The `save auditLog` command retrieves the audit log records.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

save auditLog (all | (beginDate=date | endDate=date)
|(beginRecord=timestamp | endRecord=timestamp)) file="filename"
----

== Parameters

|===
| Parameter| Description
a|
`all`
a|
Allows you to retrieve all audit log records.
a|
`beginDate`
a|
Allows you to specify the beginning date to retrieve. The format for entering the date is MM:DD:YY in the client time zone. The first audit log record retrieved will be the first record that was posted on or after the specified date.
[NOTE]
====
The midnight-to-midnight range is based on the client's time zone.
====

a|
`endDate`
a|
Allows you to specify the ending date to retrieve. If not specified, then the last record in the log will be retrieved. The format for entering the date is MM:DD:YY in the client time zone. The last audit log record retrieved will be the last record that was posted on or before the specified date.
[NOTE]
====
The midnight-to-midnight range is based on the client's time zone.
====

a|
`beginRecord`
a|
Allows you to specify the beginning record to retrieve. The value is the integral value that represents the time stamp of the first audit log record, inclusive. If not specified, the first record in the log will be retrieved.
a|
`endRecord`
a|
Allows you to specify the ending record to retrieve. The value is the integral value that represents the time stamp of the last audit log record, inclusive. If not specified, then the last record in the log will be retrieved.
a|
`file`
a|
Allows you to specify the audit log's output filename.
[NOTE]
====
The audit log records are saved in the file in descending order, from newest to oldest.
====

|===

== Examples

----

SMcli -n Array1 -c "save auditLog all file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog endRecord=1493070393313 file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog beginDate=12:12:16 endDate=04:01:17 file="myAuditLog.txt";"


SMcli completed successfully.
----

== Minimum firmware level

8.40
