---
permalink: commands-a-z/save-alldrives-logfile.html
sidebar: sidebar
keywords: save, drive log
summary: "The save allDrives logFile command saves the drive logs to a file."
---
= Save drive log
:icons: font
:imagesdir: ../media/

[.lead]
The `save allDrives logFile` command saves the drive logs to a file.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

Drive log data is maintained by the storage array for each drive.

[NOTE]
====
Do not run this command unless you are instructed to do so by technical support.
====

== Syntax

[subs=+macros]
[source,cli]
----
save allDrives logFile=pass:quotes["_filename_"]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*logFile*`
a|
The file path and the file name to which you want to save the drive logs. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\drive01.zip"`

[NOTE]
====
This command does not automatically append a file extension to the saved file. You must specify the .zip file extension when entering the file name.
====

|===

== Minimum firmware level

6.10
