---
permalink: commands-a-z/save-storagearray-warningevents.html
sidebar: sidebar
keywords: save, storage, array, events
summary: "The save storageArray warningEvents command saves events from the Major Event Log to a file."
---
= Save storage array events
:icons: font
:imagesdir: ../media/

[.lead]
The `save storageArray warningEvents` command saves events from the Major Event Log to a file.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This command saves events from the Major Event Log to a file. You can save these events:

* *Critical events* -- An error occurred on the storage array that needs to be addressed immediately. Loss of data access might occur if you do not immediately correct the error.
* *Warning events* -- An error occurred on the storage array that results in degraded performance or reduced ability to recover from another error. Access to data has not been lost, but you must correct the error to prevent possible loss of data access if another error would occur.
* *Informational events* -- An event occurred on the storage array that does not impact normal operations. The event is reporting a change in configuration or other information that might be useful in evaluating how well the storage array is performing.
* *Debug events* -- An event occurred on the storage array that provides information that you can use to help determine the steps or states that led to an error. You can send a file with this information to technical support to help determine the cause of an error.

[NOTE]
====
Some storage arrays might not be able to support all four types of events.
====

== Syntax
[subs=+macros]
[source,cli]
----
save storageArray (allEvents | criticalEvents |
warningEvents | infoEvents | debugEvents)
file=pass:quotes["_filename_"]
[count=pass:quotes[_numberOfEvents_]]
[forceSave=(TRUE | FALSE)]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`allEvents`
a|
The parameter to save all of the events to a file.
a|
`criticalEvents`
a|
The parameter to save only the critical events to a file.
a|
`warningEvents`
a|
The parameter to save only the warning events to a file.
a|
`infoEvents`
a|
The parameter to save only the informational events to a file.
a|
`debugEvents`
a|
The parameter to save only the debug events to a file.
a|
`file`
a|
The file path and the file name to which you want to save the events. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\events.txt"`

The default name of the file that contains the contents of the Major Event Log is `major-event-log.txt`. This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

a|
`count`
a|
The number of events that you want to save to a file. If you do not enter a value for the count, all events matching the type of event you specify are saved to the file. If you enter a value for the count, only that number of events (starting with the last event entered) are saved to the file. Use integer values.
a|
`forceSave`
a|
The parameter to force saving the debug events you may have filtered from view to a file. To force saving the events, set this parameter to `TRUE`. The default value is `FALSE`.
[NOTE]
====
Using this parameter saves debug events that have been filtered out of the SANtricity Event Viewer.
====

|===

== Minimum firmware level

7.77 add these parameters:

* `warningEvents`
* `infoEvents`
* `debugEvents`
* `forceSave`
