---
permalink: commands-a-z/save-storagearray-autoloadbalancestatistics-file.html
sidebar: sidebar
keywords: save, auto-load, balance, statistics
summary: "The save storageArray autoLoadBalanceStatistics file command provides automated I/O workload balancing and ensures that incoming I/O traffic from the hosts is dynamically managed and balanced across both controllers."
---
= Save auto-load balancing statistics
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray autoLoadBalanceStatistics file` command provides automated I/O workload balancing and ensures that incoming I/O traffic from the hosts is dynamically managed and balanced across both controllers.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This command saves the automatic load balancing statistics of the storage array to a file. These statistics show the ownership change history on each volume in the array.

[NOTE]
====
Send this file to technical support for interpretation.
====

== Syntax
[subs=+macros]
[source,cli]
----
 save storageArray autoLoadBalanceStatistics file=pass:quotes["_filename_"]
(numberOfDays=pass:quotes[_numberOfDays_]);
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`storageArray`
a|
Specifies that this command works on a storage array.
a|
`file`
a|
The file path and the file name to which you want to save the auto-load balancing statistics. Enclose the file name in double quotation marks (" ").

a|
`numberOfDays`
a|
The number of days worth of statistics to save. This parameter is optional and the default value is 0, which indicates all available data.
|===

== Example

----
SMcli -n Array1 -c "save storageArray autoLoadBalanceStatistics file="filename" numberOfDays=30;"
----

[NOTE]
====
An active "Drive Lost Primary Path" condition will result in the Automatic Load Balancing incapable of balancing workloads. This condition must be inactive to ensure workloads are balanced through the Automatic Load Balancing feature.
====

== Minimum firmware level

8.30
