---
permalink: commands-a-z/save-storagearray-configuration.html
sidebar: sidebar
keywords: save, storage, array, configuration
summary: "The save storageArray configuration command creates a script file that you can use to re-create the current storage array volume configuration."
---
= Save storage array configuration
:icons: font
:imagesdir: ./media/

[.lead]
The `save storageArray configuration` command creates a script file that you can use to re-create the current storage array volume configuration.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role. However, the use of this command with the LDAP parameter is restricted to those with the Security Admin role.

== Context

[NOTE]
====
This command does not save remote mirroring or volume copy configuration data on the current storage array to a file.
====

== Syntax

[subs=+macros]
----
save storageArray configuration file=pass:quotes["_filename_"]
(allconfig|[globalSettings=(TRUE | FALSE)]
[volumeConfigAndSettings=(TRUE | FALSE)]
[hostTopology=(TRUE | FALSE)]
[lunMappings=(TRUE | FALSE)])
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*file*`
a|
The file path and the file name to which you want to save the configuration settings. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\saconf.cfg"`

The default name of the file that contains the configuration settings is `storage-array-configuration.cfg`. This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

a|
`*allConfig*`
a|
The setting to save all of the configuration values to the file. (If you choose this parameter, all of the configuration parameters are set to `TRUE` .)
a|
`*globalSettings*`
a|
The setting to save the global settings to the file. To save the global settings, set this parameter to `TRUE`. To prevent saving the global settings, set this parameter to `FALSE`. The default value is `TRUE`.
a|
`*volumeConfigAndSettings*`
a|
The setting to save the volume configuration settings and all of the global settings to the file. To save the volume configuration settings and global settings, set this parameter to `TRUE`. To prevent saving the volume configuration settings and global settings, set this parameter to `FALSE`. The default value is `TRUE`.
a|
`*hostTopology*`
a|
The setting to save the host topology to the file. To save the host topology, set this parameter to `TRUE`. To prevent saving the host topology, set this parameter to `FALSE`. The default value is `FALSE`.
a|
`*lunMappings*`
a|
The setting to save the LUN or NSID mapping to the file. To save the LUN or NSID mapping, set this parameter to `TRUE`. To prevent saving the LUN or NSID mapping, set this parameter to `FALSE`. The default value is `FALSE`.
|===

== Notes

When you use this command, you can specify any combination of the parameters for the global setting, the volume configuration setting, the host topology, or the LUN mapping. If you want to enter all settings, use the `allConfig` parameter. You must either use the `allConfig` parameter, or one or more of the other four parameters.

== Minimum firmware level

6.10
