---
permalink: commands-a-z/save-alltrays-logfile.html
sidebar: sidebar
keywords: save, tray log
summary: "The save allTrays logFile command saves the log sense data to a file."
---
= Save tray log
:icons: font
:imagesdir: ../media/

[.lead]
The `save allTrays logFile` command saves the log sense data to a file.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

Log sense data is maintained by the environmental cards for each tray. Not all of the environmental cards contain log sense data.

== Syntax

[subs=+macros]
[source,cli]
----
save allTrays logFile=pass:quotes["_filename_"]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*logFile*`
a|
The file path and the file name to which you want to save the log sense data. Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\traylogdat.txt"`

This command does not automatically append a file extension to the saved file. You must specify a file extension when entering the file name.

|===

== Minimum firmware level

6.50
