---
permalink: commands-a-z/set-storagearray.html
sidebar: sidebar
keywords: set, storage, array
summary: "The set storageArray command defines the properties of the storage array."
---
= Set storage array
:icons: font
:imagesdir: ../media/

[.lead]
The `set storageArray` command defines the properties of the storage array.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
With firmware version 8.10 the `cacheFlushStop` parameter is deprecated and will be removed in a future release of storage management software.
====

== Syntax
[source,cli]
----
set storageArray
([autoLoadBalancingEnable=(TRUE | FALSE)]|
[autoSupportMaintenanceWindow AutoSupport Maintenance Window parameters]
[autoSupport schedule AutoSupport Schedule Parameters]|
[autoSupportConfig (enable | disable)]|
[autoSupportOnDemand (enable | disable)]|
[autoSupportRemoteDiag (enable |disable)]|
[cacheBlockSize=cacheBlockSizeValue]|
[cacheFlushStart=cacheFlushStartSize]|
[cacheMirrorDataAssuranceCheckEnable=(TRUE | FALSE)]|
[controllerHealthImageAllowOverWrite]|
[defaultHostType=("hostTypeName" |"hostTypeIdentifier")] |
[directoryServer directory server parameters]|
[externalKeyManagement external key management parameters]|
[failoverAlertDelay=delayValue]|
[hostConnectivityReporting (enable | disable)]|
[icmpPingResponse=(TRUE | FALSE)]|
[isnsIPV4ConfigurationMethod isns IPv4 Config Method Parameters]|
[isnsIPv6Address=ipAddress]|
[isnsListeningPort=listeningPortIPAddress]|
[isnsRegistration=(TRUE | FALSE)]|
[learnCycleDate learn cycle parameters]|
[localUsername=local user name parameters]|
[loginBanner file="path_to_login_banner"]|
[managementInterface restOnly={true | false}]|
[mediaScanRate=(disabled | 1-210)]|
[odxEnabled=(TRUE | FALSE)]|
[password="password"]|
[passwordLength=<INTEGER>]|
[pqValidateOnReconstruct P/Q Validate on Reconstruct parameters]|
[redundancyMode=(simplex | duplex)]|
[revocationCheckSettings revocation check settings parameters]|
[securityKey]|
[symbol SYMbol user name and password parameters]|
[syslog syslog parameters]|
[time]|
[trayPositions=(controller | trayID ... trayIDn)]|
[unnamedDiscoverySession=(TRUE | FALSE)]|
[userLabel="storageArrayName"]|
[userSession sessionTimeout=n]|
[vaaiEnabled=(TRUE | FALSE)])
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`autoLoadBalancingEnable`
a|
This parameter enables auto-load balancing on the controller. To enable the option, set this parameter to `TRUE`. To disable the option, set this parameter to `FALSE`.

[NOTE]
====
When the Automatic Load Balancing feature is enabled, the Host Connectivity Reporting feature will also be enabled.
====

a|
`autoSupport schedule`
a|
Sets the daily and weekly times and days of the week that AutoSupport messages are sent.
a|
`autoSupportConfig`
a|
The setting for automatically collecting support data each time the firmware detects a critical MEL event. This parameter has these values:

* `enable` -- Turns on the collection of support data
* `disable` -- Turns off the collection of support data

Use this parameter under these conditions only:

* The AutoSupport (ASUP) feature is not available on the storage array
* To support configurations on storage arrays that previously used this parameter

[NOTE]
====
You cannot use this parameter with the ASUP commands.
====

a|
`autoSupportMaintenanceWindow`
a|
Turns on or turns off the AutoSupport maintenance window feature and configures the feature.
a|
`cacheBlockSize`
a|
The cache block size that is used by the controller for managing the cache. Valid values are `4` (4 KB), `8` (8 KB), `16` (16 KB), or `32` (32 KB).
a|
`cacheMirrorDataAssuranceCheckEnable`
a|
This parameter enables cache mirror data assurance check on the controller. To enable the option, set this parameter to `TRUE`. To disable the option, set this parameter to `FALSE`.
a|
`cacheFlushStart`
a|
The percentage of unwritten data in the cache that causes a cache flush. Use integer values from `0` to `100` to define the percentage. The default value is `80`.

a|
`cacheFlushStop`
a|

[NOTE]
====
This parameter is deprecated and will be removed in a future release.
====

The percentage of unwritten data in the cache that stops a cache flush. Use integer values from `0` to `100` to define the percentage. This value must be less than the value of the `cacheFlushStart` parameter.

a|
`controllerHealthImageAllowOverWrite`
a|
Sets a flag on a controller to allow a new controller health image to overwrite an existing controller health image on storage arrays that support the controller health image feature.
a|
`defaultHostType`
a|
The default host type of any unconfigured host port to which the controllers are connected. To generate a list of valid host types for the storage array, run the `show storageArray hostTypeTable` command. Host types are identified by a name or a numerical index. Enclose the host type name in double quotation marks (" "). Do not enclose the host type numerical identifier in double quotation marks.
a|
`directoryServer`
a|
Updates the directory server configuration, including role mappings.
a|
`externalKeyManagement`
a|
Configures the external key management server address and port number
a|
`failoverAlertDelay`
a|
The failover alert delay time in minutes. The valid values for the delay time are `0` to `60` minutes. The default value is `5`.
a|
`hostConnectivityReporting`
a|
This parameter enables host connectivity reporting on the controller. To enable the option, set this parameter to `enable`. To disable the option, set this parameter to `disable`.
[NOTE]
====
If you attempt to disable Host Connectivity Reporting when Automatic Load Balancing is enabled, you receive an error. First disable the Automatic Load Balancing feature, then disable the Host Connectivity Reporting feature.
====

[NOTE]
====
You can keep Host Connectivity Reporting enabled when Automatic Load Balancing is disabled.
====

a|
`icmpPingResponse`
a|
This parameter turns on or turns off Echo Request messages. Set the parameter to `TRUE` to turn on Echo Request messages. Set the parameter to `FALSE` to turn off Echo Request messages.
a|
`isnsIPv4ConfigurationMethod`
a|
The method that you want to use to define the iSNS server configuration. You can enter the IP address for the IPv4 iSNS servers by selecting `static`. For IPv4, you can choose to have a Dynamic Host Configuration Protocol (DHCP) server select the iSNS server IP address by entering `dhcp`. To enable DHCP, you must set the `isnsIPv4Address` parameter to `0.0.0.0`.
a|
`isnsIPv6Address`
a|
The IPv6 address that you want to use for the iSNS server.
a|
`isnsListeningPort`
a|
The IP address that you want to use for the iSNS server listening port. The range of values for the listening port is `49152` to `65535`. The default value is `53205`.

The listening port resides on the server and performs these activities:

* Monitors incoming client connection requests
* Manages traffic to the server

When a client requests a network session with a server, the listener receives the actual request. If the client information matches the listener information, then the listener grants a connection to the database server.

a|
`isnsRegistration`
a|
This parameter lists the storage array as an iSCSI target on the iSNS server. To register the storage array on the iSNS server, set this parameter to `TRUE`. To remove the storage array from the iSNS server, set this parameter to `FALSE`.

[NOTE]
====
You cannot use the `isnsRegistration` parameter with any other parameter when running the `set storageArray` command.
====

For more information about iSNS registration, refer to the `set storageArray isnsRegistration` command.

a|
`learnCycleDate`
a|
Sets controller battery learn cycles.
a|
`localUsername`
a|
Allows you to set a local user name password or a SYMbol password for a particular role.
a|
`loginBanner`
a|
Allows you to upload a text file to be used as a login banner. The banner text can include an advisory notice and consent message, which is presented to users before they establish sessions in SANtricity System Manager or before they run commands
a|
`managementInterface`
a|
Changes the management interface of the controller. Change the management interface type to enforce confidentiality between the storage array and its management software or to access external tools.
a|
`mediaScanRate`
a|
The number of days over which the media scan runs. Valid values are `disabled` , which turns off the media scan, or `1` day to `210` days, where `1` day is the fastest scan rate, and `210` days is the slowest scan rate. A value other than `disabled` or `1` through `210` does not allow the media scan to function. 
a|
`odxEnabled`
a|
Turns on or turns off Offloaded Data Transfer (ODX) for a storage array.
a|
`password`
a|
The password for the storage array. Enclose the password in double quotation marks (" ").
[NOTE]
====
With the 8.40 release, this parameter is deprecated. Use the `localUsername` or the symbol `symbol` parameters, along with the `password` or `adminPassword` parameters, instead.
====

a|
`passwordLength`
a|
Allows you to set the minimum required length for all new or updated passwords. Use a value between 0 and 30.
a|
`pqValidateOnReconstruct`
a|
Modifies the P/Q validate on reconstruction capability.
a|
`redundancyMode`
a|
Use `simplex` mode when you have a single controller. Use `duplex` mode when you have two controllers.
a|
`revocationCheckSettings`
a|
Allows you to enable or disable revocation checking, and configure an Online Certificate Status Protocol (OCSP) server.
a|
`securityKey`
a|
Sets the internal security key that is used throughout the storage array to implement the Drive Security feature.
[NOTE]
====
Used for an internal security key. When an external key management server is used, use the `create storageArray securityKey` command.
====

a|
`symbol`
a|
Allows you to set a SYMbol password for a particular role.
a|
`syslog`
a|
Allows you to change the syslog server address, protocol, or port number.
a|
`time`
a|
Sets the clocks on both controllers in a storage array by synchronizing the controller clocks with the clock of the host from which you run this command.
a|
`trayPositions`
a|
A list of all of the tray IDs. The sequence of the tray IDs in the list defines the positions for the controller tray and the drive trays in a storage array. Valid values are `0` to `99`. Enter the tray ID values separated with a space. Enclose the list of tray ID values in parentheses. For storage arrays where the controller tray has a predefined identifier that is not in the range of valid tray position values, use the `controller` value.
[NOTE]
====
The `controller` option is not valid after firmware release 6.14.
====

a|
`unnamedDiscoverySession`
a|
Enables the storage array to participate in unnamed discovery sessions.
a|
`userLabel`
a|
The name for the storage array. Enclose the storage array name in double quotation marks (" ").
a|
`userSession`
a|
Allows you to set a timeout in System Manager, so that users' inactive sessions are disconnected after a specified time.
a|
`vaaiEnabled`
a|
Turns on or turns off VMware vStorage API Array Architecture (VAAI) for a storage array
|===

== Notes

Except for the `isnsRegistration`, when you use this command you can specify one or more of the optional parameters.

== Auto Support data

[NOTE]
====
You cannot use this parameter with the ASUP commands.
====

When enabled, the `set storageArray autoSupportConfig` command causes all configuration and state information for the storage array to be returned each time a critical Major Event Log (MEL) event is detected. The configuration and state information is returned in the form of an object graph. The object graph contains all relevant logical and physical objects and their associated state information for the storage array.

The `set storageArray autoSupportConfig` command collects configuration and state information in this way:

* Automatic collection of the configuration and state information occurs every 72 hours. The configuration and state information is saved to the storage array zip archive file. The archive file has a time stamp that is used to manage the archive files.
* Two storage array zip archive files are maintained for each storage array. The zip archive files are kept on a drive. After the 72-hour time period is exceeded, the oldest archive file is always overwritten during the new cycle.
* After you enable automatic collection of the configuration and state information using this command, an initial collection of information starts. Collecting information after the you issue the command makes sure that one archive file is available and starts the time stamp cycle.

You can run the `set storageArray autoSupportConfig` command on more than one storage array.

== Cache block size

When you define cache block sizes, use the 4-KB cache block size for storage arrays that require I/O streams that are typically small and random. Use the 8-KB cache block size when the majority of your I/O streams are larger than 4 KB but smaller than 8 KB. Use the 16-KB cache block size or the 32-KB cache block size for storage arrays that require large data transfer, sequential, or high-bandwidth applications.

The `cacheBlockSize` parameter defines the supported cache block size for all of the volumes in the storage array. Not all controller types support all cache block sizes. For redundant configurations, this parameter includes all of the volumes that are owned by both controllers within the storage array.

== Cache flush start

When you define values to start a cache flush, a value that is too low increases the chance that data needed for a host read is not in the cache. A low value also increases the number of drive writes that are necessary to maintain the cache level, which increases system overhead and decreases performance.

== Default host type

When you define host types, if Storage Partitioning is enabled, the default host type affects only those volumes that are mapped in the default group. If Storage Partitioning is not enabled, all of the hosts that are attached to the storage array must run the same operating system and be compatible with the default host type.

== Media scan rate

Media scan runs on all of the volumes in the storage array that have Optimal status, do not have modification operations in progress, and have the `mediaScanRate` parameter enabled. Use the `set volume` command to enable or disable the `mediaScanRate` parameter.

== Password

Passwords are stored on each storage array. For best protection, the password must meet these criteria:

* The password must be between eight and 30 characters long.
* The password must contain at least one uppercase letter.
* The password must contain at least one lowercase letter.
* The password must contain at least one number.
* The password must contain at least one non-alphanumeric character, for example, < > @ +.

[NOTE]
====
If you are using full disk encryption drives in your storage array, you must use these criteria for your storage array password.
====

[NOTE]
====
You must set a password for your storage array before you can create a security key for encrypted full disk encryption drives.
====

== Minimum firmware level

5.00 adds the `defaultHostType` parameter.

5.40 adds the `failoverAlertDelay` parameter.

6.10 adds the `redundancyMode`, `trayPositions`, and `time` parameters.

6.14 adds the `alarm` parameter.

7.10 adds the `icmpPingResponse`, `unnamedDiscoverySession`, `isnsIPv6Address`, and `isnsIPv4ConfigurationMethod` parameters.

7.15 adds more cache block sizes and the `learnCycleDate` parameter.

7.86 removes the `alarm` parameter because it is no longer used, and adds the `coreDumpAllowOverWrite` parameter.

8.10 deprecates the `cacheFlushStop` parameter.

8.20 adds the `odxEnabled` and `vaaiEnabled` parameters.

8.20 updates the `cacheBlockSize` parameter to add the `cacheBlockSizeValue` of 4 (4 KB).

8.20 replaces the `coreDumpAllowOverWrite` parameter with the `controllerHealthImageAllowOverWrite` parameter.

8.30 adds the `autoLoadBalancingEnable` parameter.

8.40 adds the `localUsername` parameter (used with a user name variable and either the `password` or `adminPassword` parameter. Also adds the `symbol` parameter (used with a user name variable and either the `password` or `adminPassword` parameter.

8.40 deprecates the `password` and `userRole` standalone parameters.

8.40 adds the `managementInterface` parameter.

8.40 adds the `externalKeyManagement` parameter.

8.41 adds the `cacheMirrorDataAssuranceCheckEnable`, `directoryServer`, `userSession`, `passwordLength`, and `loginBanner` parameters.

8.42 adds the `pqValidateOnReconstruct`, `syslog`, `hostConnectivityReporting`, and `revocationCheckSettings` parameters.
