---
permalink: commands-a-z/set-email-smtp-delivery-method.html
sidebar: sidebar
keywords: specify, email, smtp, delivery method, individual, E2800, E5700, arrays
summary: "The set storageArray autoSupport deliveryMethod command sets up the delivery method for sending AutoSupport messages to email (SMTP)."
---
= Specify the Email (SMTP) delivery method
:icons: font
:imagesdir: ../media/

[.lead]
The `set storageArray autoSupport deliveryMethod` command sets up the delivery method for sending AutoSupport messages to email (SMTP).

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set storageArray autoSupport deliveryMethod=email
mailRelayServer=pass:quotes["_serverAddress_" senderEmail="_emailAddress_"] destinationAddress="destination1@example.com" destinationAddress="destination2@example.com";
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`deliveryMethod`
a|
Allows the user to specify the delivery method for AutoSupport collection. Valid choices are:

* email
* HTTPS

[NOTE]
====
If the email method is configured, then the AutoSupport OnDemand and Remote Diagnostics will be disabled.
====

a|
`mailRelayServer`
a|
Allows the user to specify the mail relay server for the AutoSupport collection.
a|
`senderEmail`
a|
Allows the user to specify send email address for the AutoSupport collection.
a|
`destinationAddress`
a|
Email address where AutoSupport dispatches will be sent. This parameter may be provided multiple times to allow dispatches to be sent to multiple addresses.

|===

=== Examples

----

SMcli -n Array1 -c "set storageArray autoSupportConfig deliveryMethod=email mailRelayServer=\"mailserver.company.com\" senderEmail=\"user@company.com\";"

SMcli completed successfully.
----

=== Verification

Send a test message using the `_start storageArray autoSupport deliveryTest_` command to verify that your delivery methods are set up correctly.

== Minimum Firmware Level

8.40
