---
permalink: /commands-a-z/set-storagearray-directoryserver.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray directoryServer command updates the directory server configuration.'
---
= Set storage array directory server
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray directoryServer` command updates the directory server configuration.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

set storageArray directoryServer ["domainId"]
    (domainNames=("domainName1"..."domainNameN") |
     addDomainNames=("domainName1"..."domainNameN") |
     serverUrl="serverUrl" |
     bindAccount="username" bindPassword="password" |
     searchBaseDN="distinguishedName" |
     usernameAttribute="attributeName" |
     groupAttributes=("attrName1"..."attrNameN") |
     addGroupAttributes=("attrName1"..."attrNameN"))
    [skipConfigurationTest={true | false}]
----

== Parameters

|===
| Parameter| Description
a|
`directoryServer`
a|
Allows you to specify the domain ID to update the settings.
a|
`domainNames`
a|
Allows you to set one or more valid domain names for the directory server. If you enter more than one name, separate the values with a space. Using this set option will clear out existing domain names.
a|
`addDomainNames`
a|
Allows you to add one or more valid domain names for the directory server. If you enter more than one name, separate the values with a space.
a|
`serverUrl`
a|
Allows you to specify the server URL.
a|
`bindAccount`
a|
Allows you to specify the username to be used as the binding account.
a|
`bindPassword`
a|
Allows you to specify the password to be used as the binding password.
a|
`searchBaseDN`
a|
Allows you to specify the search base distinguished name to search for LDAP user objects for determining group membership.
a|
`usernameAttribute`
a|
Allows you to specify the attribute to be used to search for user objects for determining group membership. If specified, the string must contain the variable `+{uid}+` that will be replaced with the username used during login. Example: `+sAMAccountName={uid}+`

a|
`groupAttributes`
a|
Allows you to set one or more group attributes to be used to look for group Distinguished Names. Distinguished names are used to determine group membership for role mapping.
[NOTE]
====
If you enter more than one group, separate the values with a space.
====

[NOTE]
====
Using this parameter will clear out existing groups.
====

a|
`addGroupAttributes`
a|
Allows you to add one or more group attributes to be used to look for group Distinguished Names. Distinguished names are used to determine group membership for the purposes of role mapping.
[NOTE]
====
If you enter more than one group, separate the values with a space.
====

a|
`skipConfigurationTest`
a|
Allows you to skip the configuration test before the configuration is saved. The default is `false`.
|===

== Examples

----
SMcli -n Array1 -c "set storageArray directoryServer ["domain1"]
     serverUrl="ldaps://hqldap.eng.mycompany.com:636";"

SMcli -n Array1 -c "set storageArray directoryServer ["domain1"]
                    bindAccount="bindDN2" bindPassword="thePassword2"
                    searchBaseDN="OU=_Users,DC=hq,DC=mycompany,DC=com"
                    usernameAttribute="sAMAccountName" groupAttributes=("memberOf");"

SMcli completed successfully.
----
