---
permalink: commands-a-z/set-storagearray-isnsserverrefresh.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray isnsServerRefresh command refreshes the network address information for the iSNS server.'
---
= Set storage array iSNS server refresh
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray isnsServerRefresh` command refreshes the network address information for the iSNS server.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This command is valid for only IPv4.

== Syntax

----
set storageArray isnsServerRefresh
----

== Parameters

None.

== Notes

If the DHCP server is not operating at full capability, or if the DHCP server is unresponsive, the refresh operation can take between two and three minutes to complete.

The `set storageArray isnsServerRefresh` command returns an error if you did not set the configuration method to DHCP. To set the configuration method to DHCP, use the `set storageArray isnsIPV4ConfigurationMethod` command.

== Minimum firmware level

7.10
