---
permalink: commands-a-z/set-drive-serviceallowedindicator.html
sidebar: sidebar
keywords: set, drive, service, action, allowed, indicator
summary: "The set drive serviceAllowedIndicator command turns on or turns off the Service Action Allowed indicator light on a drive or drives in drive trays that support the Service Action Allowed indicator light feature."
---
= Set drive service action allowed indicator
:icons: font
:imagesdir: ./media/

[.lead]
The `set drive serviceAllowedIndicator` command turns on or turns off the Service Action Allowed indicator light on a drive or drives in drive trays that support the Service Action Allowed indicator light feature.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the storage array does not support the Service Action Allowed indicator light feature, this command returns an error. If the storage array supports the command, but is unable to turn on or turn off the indicator light, this command returns an error.

== Syntax
[subs=+macros]
[source,cli]
----
set (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
serviceAllowedIndicator=(on | off)
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`drive` or `drives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`serviceAllowedIndicator`
a|
The setting to turn on or turn off the Service Action Allowed indicator light. To turn on the Service Action Allowed indicator light, set this parameter to `on`. To turn off the Service Action Allowed indicator light, set this parameter to `off`.
|===

== Notes

The `drive` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0`, and specify the ID of the slot in which a drive resides.

== Minimum firmware level

6.16

7.60 adds the `drawerID` user input.
