---
permalink: /commands-a-z/set-storagearray-pqvalidateonreconstruct.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray pqValidateOnReconstruct command sets the storage array P/Q validation state on reconstruction. When this capability is enabled, data is reconstructed using both data+P and data+Q, and the results checked for consistency before determining how to proceed.'
---
= Set storage array PQ validation on reconstruct
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray pqValidateOnReconstruct` command sets the storage array P/Q validation state on reconstruction. When this capability is enabled, data is reconstructed using both data+P and data+Q, and the results checked for consistency before determining how to proceed.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

This feature applies to disk pools and RAID 6 volume groups, which have dual parity. In this case, there is still redundancy in the volume group or disk pool when a drive fails, so it is possible to check data and parity consistency during reconstruction. If an inconsistency is found during reconstruction and Data Assurance is enabled for the volume, it may be possible to identify the source of the inconsistency so that data can be reconstructed using the remaining drives. If this feature is enabled, and Data Assurance is not enabled for the volume, or if the inconsistency cannot be isolated to a single drive, then the block being reconstructed is marked as unreadable.

The validation may increase reconstruction times for SSD drives, so this feature can be enabled or disabled based on media type. If enabled for a given media type, the feature is applied to all pools and RAID 6 volume groups using that media type.

== Syntax

----
set storageArray pqValidateOnReconstruct (enable | disable) driveMediaType=(hdd | ssd | allMedia)
----

== Parameters

|===
| Parameter| Description
a|
`pqValidateOnReconstruct`
a|
Modifies the P/Q validate on reconstruction capability.
a|
`enable` or `disable`
a|
Enables or disables P/Q validation on reconstruction.
a|
`driveMediaType`
a|
The drive media type on which to set the P/Q validate on reconstruction capability. The following drive media types are supported:

* `hdd` indicates that you want to set the validation state on hard disk drives
* `ssd` indicates that you want to set the validation state on solid state disks
* `allMedia` indicates that you want to set the validation state on all media in the storage array.

|===

== Example with drive media type specified as hard disk drives

----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct enable driveMediaType=hdd;"

SMcli completed successfully.
----

== Example with drive media type specified as solid-state drives

----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct disable driveMediaType=ssd;"

SMcli completed successfully.
----

== Minimum firmware level

8.42
