---
permalink: commands-a-z/set-snapgroup-enableschedule.html
sidebar: sidebar
keywords: set, snapshot, group, schedule
summary: "The set snapGroup enableSchedule command defines the schedule for taking snapshot images for a snapshot group."
---
= Set snapshot group schedule
:icons: font
:imagesdir: ./media/

[.lead]
The `set snapGroup enableSchedule` command defines the schedule for taking snapshot images for a snapshot group.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
enableSchedule=(TRUE | FALSE)
schedule (immediate | snapshotSchedule)
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`snapGroup`
a|
The name of the snapshot group for which you are setting properties. Enclose the snapshot group name in double quotation marks (" ") inside of square brackets ([ ]).
a|
`enableSchedule`
a|
Use this parameter to turn on or to turn off the ability to schedule a snapshot operation. To turn on snapshot scheduling, set this parameter to `TRUE`. To turn off snapshot scheduling, set this parameter to `FALSE`.
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

The `enableSchedule` parameter and the `schedule` parameter provide a way for you to schedule creating snapshot images for a snapshot group. Using these parameters, you can schedule snapshots daily, weekly, or monthly (by day or by date). The `enableSchedule` parameter turns on or turns off the ability to schedule snapshots. When you enable scheduling, you use the `schedule` parameter to define when you want the snapshots to occur.

This list explains how to use the options for the `schedule` parameter:

* `immediate` -- As soon as you enter the command, a snapshot image is created, and a copy-on-write operation begins.
* `startDate` -- A specific date on which you want to create a snapshot image and perform a copy-on-write operation. The format for entering the date is `MM:DD:YY` . If you do not provide a start date, the current date is used. An example of this option is `startDate=06:27:11`.
* `scheduleDay` -- A day of the week on which you want to create a snapshot image and perform a copy-on-write operation. You can enter these values: `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`, and `all`. An example of this option is `scheduleDay=wednesday`.
* `startTime` -- The time of a day that you want to create a snapshot image and start performing a copy-on-write operation. The format for entering the time is `HH:MM`, where `HH` is the hour and `MM` is the minute past the hour. Use a 24-hour clock. For example, 2:00 in the afternoon is 14:00. An example of this option is `*startTime=14:27*`.
* `scheduleInterval` -- An amount of time, in minutes, that you want to have as a minimum between copy-on-write operations. You can possibly create a schedule in which you have overlapping copy-on-write operations because of the duration of a copy operation. You can make sure that you have time between copy-on-write operations by using this option. The maximum value for the `scheduleInterval` option is 1440 minutes. An example of this option is `*scheduleInterval=180*`.
* `endDate` -- A specific date on which you want to stop creating a snapshot image and end the copy-on-write operation. The format for entering the date is `MM:DD:YY`. An example of this option is `*endDate=11:26:11*`.
* `noEndDate` -- Use this option if you do not want your scheduled copy-on-write operation to end. If you later decide to end the copy-on-write operations you must re-enter the `set snapGroup` command and specify an end date.
* `timesPerDay` -- The number of times that you want the schedule to run in a day. An example of this option is `timesPerDay=4`.
* `timeZone` -- Use this parameter to define the time zone in which the storage array is operating. You can define the time zone in one of two ways:
 ** `GMT±HH:MM` -- The time zone offset from GMT. Enter the offset in hours and minutes. For example GMT-06:00 is the central time zone in the United States.
 ** `Text string` -- Standard time zone text strings. For example: "America/Chicago" or "Australia/Brisbane". Time zone text strings are case sensitive. If you enter an incorrect text string, GMT time is used. Enclose the text string in double quotation marks.

The code string for defining a schedule is similar to these examples:

----
enableSchedule=true schedule startTime=14:27
----

----
enableSchedule=true schedule scheduleInterval=180
----

----
enableSchedule=true schedule timeZone=GMT-06:00
----

----
enableSchedule=true schedule timeZone="America/Chicago"
----

If you also use the `scheduleInterval` option, the firmware chooses between the `timesPerDay` option and the `scheduleInterval` option by selecting the lowest value of the two options. The firmware calculates an integer value for the `scheduleInterval` option by dividing 1440 by the `scheduleInterval` option value that you set. For example, 1440/180 = 8. The firmware then compares the `timesPerDay` integer value with the calculated `scheduleInterval` integer value and uses the smaller value.

To remove a schedule, use the `delete volume` command with the `schedule` parameter. The `delete volume` command with the `schedule` parameter deletes only the schedule, not the snapshot volume.

== Minimum firmware level

7.83

7.86 adds the `scheduleDate` option and the `month` option.
