---
permalink: commands-a-z/set-event-alert.html
sidebar: sidebar
keywords: set, event, alert, filter
summary: "The set event alert commands manage alert event notification by either disabling or enabling notification related to a specific alertable event. To prevent notification about a specific alertable event, you block it. To enable notification about a specific alertable event, you unblock it."
---
= Set event alert filtering
:icons: font
:imagesdir: ./media/

[.lead]
The `set event alert` commands manage alert event notification by either disabling or enabling notification related to a specific alertable event. To prevent notification about a specific alertable event, you _block_ it. To enable notification about a specific alertable event, you _unblock_ it.

== Supported Arrays

This command applies only to the E2700 and E5600 storage arrays.

== Context

[NOTE]
====
This command is an SMcli command, not a script command. You must run this command from a command line. You cannot run this command from the script editor in the storage management software
====

== Context

When you define your storage array, you can configure alerts and define how the event alerts are managed. If you have configured the storage array to send alerts, a notification is sent to a designated recipient when an alertable event occurs. That notification can be one or all of the following types:

* email
* syslog
* SNMP trap notifications

The set event alert CLI commands work on a single storage array. When you run the commands on a storage array, only that storage array is affected by the commands. Other storage arrays that have not had the CLI command run against them have the default behavior.

[NOTE]
====
Blocking an event alert does not prevent the event from being posted to the system event log. All events continue to be posted to the event log.
====

[NOTE]
====
Non-alertable events cannot be made alertable using this command.
====

== Syntax to block an event alert
[subs=+macros]
[source,cli]
----
set blockEventAlert pass:quotes[_eventType_]
----

== Syntax to unblock an event alert
[subs=+macros]
[source,cli]
----
set unBlockEventAlert pass:quotes[_eventType_]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`_eventType_`
a|
This parameter is the integer value for the event. Enter the event value in a hexadecimal format, for example, 0x280D. Always begin the hexadecimal value with *0x* to indicate that it is in hexadecimal format. If you do not use 0x, the value is interpreted as a decimal and converted to a hexadecimal value, before applying the block or unblock command. This can cause an incorrect event to be blocked or unblocked.

An error is displayed if you enter an invalid event.

|===

== Minimum firmware level

8.10
