---
permalink: commands-a-z/set-tray-serviceallowedindicator.html
sidebar: sidebar
keywords: set, tray, service, action, allowed, indicator
summary: "The set tray serviceAllowedIndicator command turns on or turns off the Service Action Allowed indicator light on a power-fan canister, an interconnect-battery canister, or an environmental services module (ESM) canister."
---
= Set tray service action allowed indicator
:icons: font
:imagesdir: ./media/

[.lead]
The `set tray serviceAllowedIndicator` command turns on or turns off the Service Action Allowed indicator light on a power-fan canister, an interconnect-battery canister, or an environmental services module (ESM) canister.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

If the storage array does not support the Service Action Allowed indicator light feature, this command returns an error. If the storage array supports the command but is unable to turn on or turn off the indicator light, this command returns an error.

To turn on or turn off the Service Action Allowed indicator light on the controller canister, use the `set controller serviceAllowedIndicator` command.

== Syntax
[subs=+macros]
[source,cli]
----
set tray pass:quotes[[_trayID_]]
(powerFan [(left | right | top | bottom)] |
interconnect |
esm [(left | right | top | bottom)]) |
battery [(left | right)] |
fanCanister [(left | right)]  |
powerCanister [(top | bottom)] |
serviceAllowedIndicator=(on | off)
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`tray`
a|
The tray where the power-fan canister, the interconnect canister, the ESM canister, or the battery canister resides. Tray ID values are `0` to `99`. Enclose the tray ID value in square brackets ([ ]). If you do not enter a tray ID value, the tray ID of the controller tray is the default value.
a|
`powerFan`
a|
The Service Action Allowed indicator light on the power-fan canister that you want to turn on or turn off. Valid power-fan canister identifiers are `left`, `right`, `top`, or `bottom`. Enclose the power-fan canister identifier in square brackets ([ ]).
a|
`interconnect`
a|
The Service Action Allowed indicator light for the interconnect-battery canister.
a|
`esm`
a|
The Service Action Allowed indicator light for an ESM canister. Valid ESM canister identifiers are `left`, `right`, `top`, or `bottom`.
a|
`battery`
a|
The Service Action Allowed indicator light for a battery. Valid battery identifiers are `left` or `right`.
a|
`fanCanister`
a|
The Service Action Allowed indicator light for a fan canister. Valid fan canister identifiers are `left` or `right`.
a|
`powerCanister`
a|
The Service Action Allowed indicator light for a power canister. Valid power canister identifiers are `top` or `bottom`.
a|
`serviceAllowedIndicator`
a|
The setting to turn on or turn off the Service Action Allowed indicator light. To turn on the Service Action Allowed indicator light, set this parameter to `on`. To turn off the Service Action Allowed indicator light, set this parameter to `off`.
|===

== Notes

This command was originally defined for use with the CE6998 controller tray. This command is not supported by controller trays that were shipped before the introduction of the CE6998 controller tray.

== Example

This command turns on the Service Action Allowed indicator light for the left ESM in tray 5 with the IP address of 155.155.155.155.

----
SMcli 123.145.167.214 123.145.167.215 -c "set tray [5]
ESM [left] serviceAllowedIndicator=on;"
----

== Minimum firmware level

6.14 adds these parameters:

* `powerFan`
* `interconnect`

6.16 adds these parameters:

* `tray`
* `esm`

7.60 adds the identifiers `top` and `bottom`.

7.60 adds the `powerCanister` and `fanCanister` parameters.
