---
permalink: /commands-a-z/set-host.html
sidebar: sidebar
keywords: 
summary: 'The set host command assigns a host to a host group or moves a host to a different host group.'
---
= Set host
:icons: font
:imagesdir: ./media/

[.lead]
The `set host` command assigns a host to a host group or moves a host to a different host group.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

You can also create a new host group and assign the host to the new host group with this command. The actions performed by this command depend on whether the host has individual mappings or does not have individual mappings.

== Syntax

----
set host [hostName]
hostGroup=("hostGroupName" | none | defaultGroup)
userLabel="newHostName"
hostType=(hostTypeIndexLabel | hostTypeIndexNumber)
----

== Parameters

|===
| Parameter| Description
a|
`host`
a|
The name of the host that you want to assign to a host group. Enclose the host name in square brackets ([ ]). If the host name has special characters or numbers, you must enclose the host name in double quotation marks (" ") inside square brackets.
a|
`hostGroup`
a|
The name of the host group to which you want to assign the host. (The following table defines how the command runs if the host does or does not have individual mappings.) Enclose the host group name in double quotation marks (" "). The `defaultGroup` option is the host group that contains the host to which the volume is mapped.
a|
`userLabel`
a|
The new host name. Enclose the host name in double quotation marks (" ").
a|
`hostType`
a|
The index label or number of the host type for the host port. Use the `show storageArray hostTypeTable` command to generate a list of available host type identifiers. If the host type has special characters, enclose the host type in double quotation marks (" ").
|===
 

|===
| Host Group Parameter| Host Has Individual Mappings| Host Does Not Have Individual Mappings
a|
`hostGroupName`

a|
The host is removed from the present host group and is placed under the new host group defined by `hostGroupName`.

a|
The host is removed from the present host group and is placed under the new host group defined by `hostGroupName`.

a|
`none`
a|
The host is removed from the host group as an independent partition and is placed under the root node.
a|
The host is removed from the present host group and is placed under the default group.
a|
`defaultGroup`
a|
The command fails.
a|
The host is removed from the present host group and is placed under the default group.
|===

== Notes

When you use this command, you can specify one or more of the optional parameters.

For the names, you can use any combination of alphanumeric characters, hyphens, and underscores. Names can have a maximum of 30 characters.

== Minimum firmware level

6.10
