---
permalink: commands-a-z/set-hostgroup.html
sidebar: sidebar
keywords: set, host, group
summary: "The set hostGroup command renames a host group."
---
= Set host group
:icons: font
:imagesdir: ./media/

[.lead]
The `set hostGroup` command renames a host group.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set hostGroup pass:quotes[[_hostGroupName_]]
userLabel=pass:quotes["_newHostGroupName_"]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`hostGroup`
a|
The name of the host group that you want to rename. Enclose the host group name in square brackets ([ ]). If the host group name has special characters or numbers, you must enclose the host group name in double quotation marks (" ") inside square brackets.
a|
`userLabel`
a|
The new name for the host group. Enclose the new host group name in double quotation marks (" ").
|===

== Notes

You can use any combination of alphanumeric characters, hyphens, and underscores for the names. Names can have a maximum of 30 characters.

== Minimum firmware level

6.10
