---
permalink: /commands-a-z/set-storagearray-autosupportmaintenancewindow.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray autoSupportMaintenanceWindow command turns on or turns off the AutoSupport maintenance window feature.'
---
= Enable or disable AutoSupport maintenance window (for individual E2800 or E5700 arrays)
:icons: font
:imagesdir: ./media/

[.lead]
The ``set storageArray autoSupportMaintenanceWindow``command turns on or turns off the AutoSupport maintenance window feature.

Use a maintenance window to suppress automatic ticket creation on error events. Under normal operation mode the storage array will use AutoSupport to open a case with Technical Support if there is an issue. When AutoSupport is placed in a maintenance window this feature is suppressed.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax

----
set storageArray autoSupportMaintenanceWindow (enable | disable)
    emailAddresses=("emailAddress1" "emailAddress2" ...)
    [duration=<duration_in_hours>];
----

== Parameters

|===
| Parameter| Description
a|
`emailAddresses`
a|
The list of email addresses to receive a confirmation email that the maintenance window request has been processed. You can specify up to five email addresses.
a|
`duration`
a|
Optional. The duration (in hours) to enable maintenance window. If omitted, the maximum supported duration (72 hours) is used.
|===

== Examples

----

SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow enable
      emailAddresses=\"me@company.com\" duration=5;"

SMcli completed successfully.
----

----
SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow enable
      emailAddresses=(\"me1@company.com\" \"me2@company.com\");"

SMcli completed successfully.
----

----
SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow disable
      emailAddresses=(\"me1@company.com\" \"me2@company.com\" \"me3@company.com\"
      \"me4@company.com\" \"me5@company.com\");"

SMcli completed successfully.
----

== Minimum Firmware Level

8.42
