---
permalink: commands-a-z/set-storagearray-isnsregistration.html
sidebar: sidebar
keywords: set, storage, array, isns, registration
summary: "The set storageArray isnsRegistration command enables you to list a storage array on either an IPv4 or an IPv6 Internet Storage Name Service (iSNS) server."
---
= Set storage array iSNS registration
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray isnsRegistration` command enables you to list a storage array on either an IPv4 or an IPv6 Internet Storage Name Service (iSNS) server.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax for IPv4

[subs=+macros]
----
set storageArray isnsRegistration=(TRUE | FALSE)
isnsIPv4ConfigurationMethod=[static | dhcp]
isnsIPv4Address=pass:quotes[_ipAddress_]
[isnsListeningPort]
----

== Syntax for IPv6

[subs=+macros]
----
set storageArray isnsRegistration=(TRUE | FALSE)
isnsIPv6Address=pass:quotes[_ipAddress_]
[isnsListeningPort]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameters| Description
a|
`isnsRegistration`
a|
The means of registering the iSCSI target on the iSNS server. Set the parameter to `TRUE` to list an iSCSI target.

When you set this parameter to `TRUE` you must also use these parameters for IPV4 configurations:

* `isnsIPV4ConfigurationMethod`
* `isnsIPV4Address`

When you set this parameter to `TRUE` you must also use these parameters for IPV6 configurations:

* `isnsIPV6Address`

Optionally, you can also use the `isnsListeningPort` parameter to define the port monitor and manage traffic to the server.

To remove the registration for the storage array from the iSNS server set this parameter to `FALSE`.

a|
`isnsIPv4ConfigurationMethod`
a|
The method that you want to use to define the iSNS server configuration. You can enter the IP address for the IPv4 iSNS servers by selecting `static`. For IPv4, you can choose to have a Dynamic Host Configuration Protocol (DHCP) server select the iSNS server IP address by entering `dhcp`. To enable DHCP, you must set the `isnsIPv4Address` parameter to `0.0.0.0`.
a|
`isnsIPv4Address`
a|
The IPv4 address used to connect to the iSNS server. Use this parameter with the `static` value for IPv4 configurations. If you choose to have a DHCP server set the IP address for an IPv4 Internet iSNS server, you must set the `isnsIPv4Address` parameter to `0.0.0.0`.
a|
`isnsIPv6Address`
a|
The IPv6 address used to connect to the iSNS server.
a|
`isnsListeningPort`
a|
The port number that you want to use for the iSNS server listening port. The range of values for the listening port is `49152` to `65535`. The default value is `3205`.

The listening port resides on the server and performs these activities:

* Monitors incoming client connection requests
* Manages traffic to the server

When a client requests a network session with a server, the listener receives the actual request. If the client information matches the listener information, then the listener grants a connection to the database server.

|===

== Notes

The iSNS protocol facilitates the automated discovery, management, and configuration of iSCSI devices and Fibre Channel devices on a TCP/IP network. iSNS provides intelligent storage discovery and management services comparable to those found in Fibre Channel networks, which allow a commodity IP network to function in a similar capacity as a storage area network. iSNS also facilitates a seamless integration of IP networks and Fibre Channel networks, due to its ability to emulate Fibre Channel fabric services and manage both iSCSI devices and Fibre Channel devices.

The DHCP server passes configuration parameters, such as network addresses, to IP nodes. DHCP enables a client to acquire all of the IP configuration parameters that it needs to operate. DHCP lets you automatically allocate reusable network addresses.

== Minimum firmware level

7.10
