---
permalink: commands-a-z/set-drive-securityid.html
sidebar: sidebar
keywords: set, fips, drive, security, identifier
summary: "The set drive securityID command is used to reset a FIPS drive back to the original manufacturer settings."
---
= Set FIPS drive security identifier
:icons: font
:imagesdir: ../media/

[.lead]
The `set drive securityID` command is used to reset a FIPS drive back to the original manufacturer settings.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command resets a FIPS drive back to the original manufacturer settings and erases all existing drive data. This operation is completely irreversible. This may be necessary if the drive is locked due to an invalid or missing security key file or unknown pass phrase. All existing drive data will be erased.
====

To erase an FDE drive, use the `start secureErase` command.

== Syntax
[subs=+macros]
[source,cli]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`drive`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

a|
`securityID`
a|
The security ID of the drive to erase, in string form. This string can have a maximum of 32 characters. The form of the security ID will vary by manufacturer.

[NOTE]
====
To find the security ID, remove the drive and read the security ID on the canister label.
====

|===

== Notes

The `drive` parameter supports both high-capacity drive trays and low-capacity drive trays. A high-capacity drive tray has drawers that hold the drives. The drawers slide out of the drive tray to provide access to the drives. A low-capacity drive tray does not have drawers. For a high-capacity drive tray, you must specify the identifier (ID) of the drive tray, the ID of the drawer, and the ID of the slot in which a drive resides. For a low-capacity drive tray, you need only specify the ID of the drive tray and the ID of the slot in which a drive resides. For a low-capacity drive tray, an alternative method for identifying a location for a drive is to specify the ID of the drive tray, set the ID of the drawer to `0`, and specify the ID of the slot in which a drive resides.

== Example

----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----

== Minimum firmware level

8.25
