---
permalink: commands-a-z/set-storagearray-odxenabled.html
sidebar: sidebar
keywords: enable, disable, odx
summary: "The set storageArray odxEnabled command turns on or turns off Offloaded Data Transfer (ODX) for a storage array."
---
= Enable or disable ODX
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray odxEnabled` command turns on or turns off Offloaded Data Transfer (ODX) for a storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Context

The storage array comes with ODX turned on. Use this command to turn off ODX if you do not want to run ODX, or if ODX is causing issues with the storage array. The only storage array that is affected is the storage array on which the command is run.

== Syntax

----
set storageArray odxEnabled=(TRUE | FALSE)
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`odxEnabled`
a|
The setting to turn on or turn off ODX. To turn on ODX set this parameter to `TRUE`. To turn off ODX set this parameter to `FALSE`. The default setting is that ODX is turned on.
|===

== Notes

ODX provides a way to transfer data without using buffered read and buffered write operations and does not require direct host involvement with the data transfer operation. When ODX is not enabled, data is read from the source storage to the host, and then written to the target storage from the host. With ODX enabled, the data transfer operations are directly managed by the storage infrastructure. The data is moved directly from the source storage to the target storage without going through the host.

== Minimum firmware level

8.20
