---
permalink: commands-a-z/set-storagearray-isnsipv4configurationmethod.html
sidebar: sidebar
keywords: set, storage, array, isns, server, ipv4, address
summary: "The set storageArray isnsIPv4ConfigurationMethod command sets the configuration method and address for an IPv4 Internet Storage Name Service (iSNS)."
---
= Set storage array iSNS server IPv4 address
:icons: font
:imagesdir: ../media/

[.lead]
The `set storageArray isnsIPv4ConfigurationMethod` command sets the configuration method and address for an IPv4 Internet Storage Name Service (iSNS).

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
set storageArray isnsIPv4ConfigurationMethod=(static | dhcp)
isnsIPv4Address=pass:quotes[_ipAddress_]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameters| Description
a|
`isnsIPv4ConfigurationMethod`
a|
The method that you want to use to define the iSNS server configuration. You can enter the IP address for the IPv4 iSNS servers by selecting `static`. For IPv4, you can choose to have a Dynamic Host Configuration Protocol (DHCP) server select the iSNS server IP address by entering `dhcp`. To enable DHCP, you must set the `isnsIPv4Address` parameter to `0.0.0.0`.
a|
`isnsIPv4Address`
a|
The IP address that you want to use for the iSNS server. Use this parameter with the `static` value for IPv4 configurations. If you choose to have a DHCP server set the IP address for an IPv4 Internet iSNS server, you must set the `*isnsIPv4Address*` parameter to `0.0.0.0`.
|===

== Notes

The iSNS protocol facilitates the automated discovery, management, and configuration of iSCSI devices and Fibre Channel devices on a TCP/IP network. iSNS provides intelligent storage discovery and management services comparable to those found in Fibre Channel networks, which allow a commodity IP network to function in a similar capacity as a storage area network. iSNS also facilitates a seamless integration of IP networks and Fibre Channel networks, due to its ability to emulate Fibre Channel fabric services and manage both iSCSI devices and Fibre Channel devices.

The DHCP server passes configuration parameters, such as network addresses, to IP nodes. DHCP enables a client to acquire all of the IP configuration parameters that it needs to operate. DHCP lets you automatically allocate reusable network addresses.

== Minimum firmware level

7.10
