---
permalink: /commands-a-z/set-storagearray-externalkeymanagement.html
sidebar: sidebar
keywords: 
summary: 'The set storageArray externalKeyManagement command configures the external key management server address and port number.'
---
= Set external key management settings
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray externalKeyManagement` command configures the external key management server address and port number.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command applies only to external key management.
====

== Syntax

----

set storageArray externalKeyManagement serverAddress=serverAddress
serverPort=portNumber
----

== Parameters

|===
| Parameter| Description
a|
`serverAddress`
a|
Allows you to specify the external key management server address. The server address can be a fully qualified domain name, IPv4 address, or IPv6 address.
a|
`serverPort`
a|
Allows you to specify the port number of the external key management server.
|===

== Example

----
SMcli -n Array1 -c "set storageArray externalKeyManagement serverAddress=192.0.2.1 serverPort=8081;"

   SMcli completed successfully.
----

== Minimum firmware level

8.40
