---
permalink: commands-a-z/set-storagearray-resourceprovisionedvolumes.html
sidebar: sidebar
keywords: set, storage, array, resource, provisioned, volumes
summary: "The set storageArray resourceProvisionedVolumes command disables the DULBE feature."
---
= Set Storage Array Resource Provisioned Volumes
:icons: font
:imagesdir: ../media/

[.lead]
The `set storageArray resourceProvisionedVolumes` command disables the DULBE feature.

== Supported Arrays

This command applies to any individual storage array, including the EF600 and EF300 arrays; as long as all SMcli packages are installed.

== Roles

To execute this command on an EF600 and EF300 storage array, you must have the Storage Admin role.

== Context

Resource provisioning is an available feature that allows large volumes to be initialized quickly.

A resource provisioned volume is a thick volume in an SSD volume group or pool, where drive capacity is allocated (assigned to the volume) when the volume is created, but the drive blocks are deallocated (unmapped). With a resource provisioned volume, there is no time-bound background initialization. Instead, each RAID stripe is initialized upon the first write to a volume block in the stripe

Resource provisioned volumes are supported only on SSD volume groups and pools, where all drives in the group or pool support the NVMe Deallocated or Unwritten Logical Block Error Enable (DULBE) error recovery capability. When a resource provisioned volume is created, all drive blocks assigned to the volume are deallocated (unmapped). Deallocating blocks can improve SSD wear life and increase maximum write performance. The improvement varies with each drive model and capacity.

== Syntax
[source,cli]
----
set storageArray resourceProvisionedVolumes=(enable|disable)
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`resourceProvisionedVolumes`
a|
The setting to specify if resource provisioning capabilities are enabled. To disable resource provisioning, set this parameter to `disable`. The default value is `enable`.

[NOTE]
====
Changing this value only applies to volume groups and pools that are created in the future. It does not change the value of any existing volume groups and pools.
====

|===

== Minimum firmware level

8.63
