---
permalink: commands-a-z/set-volumegroup-forcedstate.html
sidebar: sidebar
keywords: set, volume, group, forced, state
summary: "The set volumeGroup forcedState command moves a volume group into a Forced state."
---
= Set volume group forced state
:icons: font
:imagesdir: ./media/

[.lead]
The `set volumeGroup forcedState` command moves a volume group into a Forced state.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

Use this command if the `start volumeGroup import` command does not move the volume group to an Imported state or if the import operation does not work because of hardware errors. In a Forced state, the volume group can be imported, and you can then identify the hardware errors.

== Syntax

[subs=+macros]
----
set volumeGroup pass:quotes[[_volumeGroupName_]] forcedState
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*volumeGroup*`
a|
The name of the volume group that you want to place in a Forced state. Enclose the volume group name in square brackets ([ ]).
|===

== Notes

You can move the drives that comprise a volume group from one storage array to another storage array. The CLI provides three commands that let you move the drives. The commands are `start volumeGroup export`, `start volumeGroup import`, and `set volumeGroup forcedState`.

In the Forced state, you can perform an import operation on the volume group.

== Minimum firmware level

7.10
