---
permalink: commands-a-z/set-storagearray-managementinterface.html
sidebar: sidebar
keywords: set, storage, array, management, interface
summary: "The set storageArray managementInterface command changes the management interface of the controller. Change the management interface type to enforce confidentiality between the storage array and its management software or to access external tools."
---
= Set storage array management interface
:icons: font
:imagesdir: ./media/

[.lead]
The `set storageArray managementInterface` command changes the management interface of the controller. Change the management interface type to enforce confidentiality between the storage array and its management software or to access external tools.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Syntax

----

set storageArray managementInterface restOnly={true | false}
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`restOnly`
a|
When set to `true`, indicates that the RESTful interface is the only management interface allowed. This interface enforces an encrypted connection between the storage array and the management software.

When set to `false`, indicates that the legacy interface between the storage array and the management software is allowed. This interface is not encrypted.

Some tools that communicate directly with the legacy management interface, such as the SANtricity SMI-S Provider or OnCommand Insight (OCI), will not work unless the `restOnly` parameter is set to `false`. Contact technical support for more information.

|===

== Examples

----

SMcli -n Array1 -c "set storageArray managementInterface restOnly=true;"

SMcli completed successfully.
----
