---
permalink: commands-a-z/show-consistencygroup.html
sidebar: sidebar
keywords: show, consistency, group
summary: "The show consistencyGroup command returns information about one or more consistency groups."
---
= Show consistency group
:icons: font
:imagesdir: ./media/

[.lead]
The `show consistencyGroup` command returns information about one or more consistency groups.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

[subs=+macros]
----
show (allConsistencyGroups | consistencyGroup pass:quotes[[_consistencyGroupName_]] |
consistencyGroups pass:quotes[[_consistencyGroupName1_ ... _consistencyGroupNameN_]])
[(summary | schedule)]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*allConsistencyGroups*`
a|
This setting returns information about all of the consistency groups in the storage array.

a|
`*consistencyGroup*`
a|
The name of the consistency group for which you are retrieving information. Enclose the consistency group name in square brackets ([ ]). If the consistency group name has special characters or numbers, you must enclose the consistency group name in double quotation marks (" ") inside square brackets.

a|
`*consistencyGroups*`
a|
The names of several consistency groups for which you are retrieving information. All of the volumes will have the same properties. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or consist only of numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`*summary*`
a|
This setting returns a concise list of information about the consistency groups.

a|
`*schedule*`
a|
This parameter returns information about any schedules for a consistency group.

|===

== Minimum firmware level

7.83
