---
permalink: commands-a-z/show-volume-summary.html
sidebar: sidebar
keywords: show, volume
summary: "The show volume summary command returns information about a volume."
---
= Show volume
:icons: font
:imagesdir: ./media/

[.lead]
The `show volume summary` command returns information about a volume.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

For the volumes in a storage array, this command returns the following information:

* The number of volumes
* The name
* The status
* The capacity
* The RAID level
* The volume group where the volume is located
* Details:
 ** The volume ID
 ** The subsystem ID
 ** The drive type (SAS)
 ** Tray loss protection
 ** The preferred owner
 ** The current owner
 ** The segment size
 ** The modification priority
 ** The read cache status (enabled or disabled)
 ** The write cache status (enabled or disabled)
 ** The write cache without batteries status (enabled or disabled)
 ** The write cache with mirror status (enabled or disabled)
 ** The flush write cache after time
 ** The cache read prefetch setting (TRUE or FALSE)
 ** The enable background media scan status (enabled or disabled)
 ** The media scan with redundancy check status (enabled or disabled)
* The mirror repository volumes

== Syntax
[subs=+macros]
[source,cli]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`allVolumes`
a|
This parameter returns performance statistics about all of the volumes in the storage array.
a|
`volume`
a|
The name of a volume for which you want to retrieve information. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the name in double quotation marks (" ") inside square brackets.

a|
`volumes`
a|
The names of several volumes for which you want to retrieve information. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`summary`
a|
The setting to return a concise list of information about the volumes.
|===
