---
permalink: commands-a-z/show-storagearray-unreadablesectors.html
sidebar: sidebar
keywords: show, storage, array, unreadable, sectors
summary: "The show storageArray unreadableSectors command returns a table of the addresses of all of the sectors in the storage array that cannot be read."
---
= Show storage array unreadable sectors
:icons: font
:imagesdir: ../media/

[.lead]
The `show storageArray unreadableSectors` command returns a table of the addresses of all of the sectors in the storage array that cannot be read.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

The returned table is organized with column headings for the following information:

* Volume user label
* Logical unit number (LUN)
* Accessible by (host or host group)
* Date/time
* Volume-relative logical block address (hexadecimal format -- 0xnnnnnnnn)
* Drive location (tray t, slot s)
* Drive-relative logical block address (hexadecimal format -- 0xnnnnnnnn)
* Failure type

The data is sorted first by the volume user label and second by the logical block address (LBA). Each entry in the table corresponds to a single sector.

== Syntax
[source,cli]
----
show storageArray unreadableSectors
----

== Parameters

None.

== Minimum firmware level

6.10
