---
permalink: commands-a-z/show-alldrives-downloadprogress.html
sidebar: sidebar
keywords: show, drive, download, progress
summary: "The show allDrives downloadProgress command returns the status of firmware downloads for the drives that are targeted by the download drive firmware command or the download storageArray driveFirmware command."
---
= Show drive download progress
:icons: font
:imagesdir: ./media/

[.lead]
The `show allDrives downloadProgress` command returns the status of firmware downloads for the drives that are targeted by the `download drive firmware` command or the `download storageArray driveFirmware` command.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
show allDrives downloadProgress
----

== Parameters

None.

== Notes

When all of the firmware downloads have successfully completed, this command returns good status. If any firmware downloads fail, this command shows the firmware download status of each drive that was targeted. This command returns the statuses shown in this table.

[cols="2*",options="header"]
|===
| Status| Definition
a|
`Successful`
a|
The downloads completed without errors.
a|
`Not Attempted`
a|
The downloads did not start.
a|
`Partial Download`
a|
The downloads are in progress.
a|
`Failed`
a|
The downloads completed with errors.
|===

== Minimum firmware level

6.10
