---
permalink: commands-a-z/show-ssd-cache.html
sidebar: sidebar
keywords: show, ssd, cache
summary: "The show ssdCache command displays information about the SSD cache."
---
= Show SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `show ssdCache` command displays information about the SSD cache.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Syntax

[subs=+macros]
----
show ssdCache pass:quotes[[_ssdCacheName_]]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache for which you want to retrieve information. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
|===

== Notes

This command returns the SSD cache information similar to this example.

----
SSD Cache name: my_cache

Status:                              Optimal
Type:                                Read Only
I/O characteristic type:             File System
Maximum capacity allowed:            1,862.645 GB
Current capacity:                    557.792 GB
Additional capacity allowed          1,304.852 GB
Drive capacities:                    All 278.896 GB
Quality of Service (QoS) Attributes
   Security capable:                 No
   Secure:                           No
   Data Assurance (DA) capable:      No
Associated drives:

Tray     Slot
0        4
0        11
Volumes using SSD cache:             volume_test
----

== Minimum firmware level

7.84
