---
permalink: /commands-a-z/show-volumecopy-source-targetcandidates.html
sidebar: sidebar
keywords: 
summary: 'The show volumeCopy source targetCandidates command returns information about the candidate volumes that you can use as the target for a volume copy operation. This command is valid for snapshot volume copy pairs.'
---
= Show volume copy target candidates
:icons: font
:imagesdir: ./media/

[.lead]
The `show volumeCopy source targetCandidates` command returns information about the candidate volumes that you can use as the target for a volume copy operation. This command is valid for snapshot volume copy pairs.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Syntax

----
show volumeCopy source ["sourceName"] targetCandidates
----

== Parameter

|===
| Parameter| Description
a|
`source`
a|
The name of the source volume for which you are trying to find a candidate target volume. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the volume name in double quotation marks (" ") inside square brackets.

|===
