---
permalink: commands-a-z/show-volumegroup-exportdependencies.html
sidebar: sidebar
keywords: show, volume, group, export, dependencies
summary: "The show volumeGroup exportDependencies command shows a list of dependencies for the drives in a volume group that you want to move from one storage array to a second storage array."
---
= Show volume group export dependencies
:icons: font
:imagesdir: ./media/

[.lead]
The `show volumeGroup exportDependencies` command shows a list of dependencies for the drives in a volume group that you want to move from one storage array to a second storage array.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Syntax
[subs=+macros]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] exportDependencies
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*volumeGroup*`
a|
The name of the volume group for which you want to show export dependencies. Enclose the volume group name in square brackets ([ ]).
|===

== Notes

This command spins up the drives in a volume group, reads the DACstore, and shows a list of import dependencies for the volume group. The volume group must be in an Exported state or a Forced state.

== Minimum firmware level

7.10
