---
permalink: commands-a-z/show-iscsisessions.html
sidebar: sidebar
keywords: show, current, iscsi, sessions
summary: "The show iscsiSessions command returns information about an iSCSI session for either an iSCSI initiator or an iSCSI target."
---
= Show current iSCSI sessions
:icons: font
:imagesdir: ./media/

[.lead]
The `show iscsiSessions` command returns information about an iSCSI session for either an iSCSI initiator or an iSCSI target.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
show iscsiInitiator pass:quotes[["_initiatorName_"] | <"iqn">] iscsiSessions
----

[subs=+macros]
[source,cli]
----
show iscsiTarget pass:quotes[["_targetName_"] | <"iqn">] iscsiSessions
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`iscsiInitiator`
a|
The name of the iSCSI initiator for which you want to obtain session information.

If the iSCSI initiator uses a label or an alias, enclose the iSCSI initiator label or alias in double quotation marks (" ") inside square brackets ([ ]).

If the iSCSI initiator uses an iSCSI qualified name (IQN), enclose the IQN in double quotation marks (" ") inside angle brackets (< >).

a|
`iscsiTarget`
a|
The name of the iSCSI target for which you want to obtain session information.

If the iSCSI target uses a label or an alias, enclose the iSCSI target label or alias in double quotation marks (" ") inside square brackets ([ ]).

If the iSCSI target uses an iSCSI qualified name (IQN), enclose the IQN in double quotation marks (" ") inside angle brackets (< >).

|===

== Example

----
Retrieve initiator: 
 
SMcli -n Array1 -u admin@local -p adminPassword -k -c "show iscsiSessions;"

Initiator information:
    Host user label:               bbb000b00b0
    Host port user label:          bbb000b00b0b0
    Name:                          iqn.0b0b-0b.com:b0b0b0b0b0b0
    Alias:                         None

Host port user label:

SMcli -n Array1 -u admin@local -p adminPassword -k -c "show iscsiInitiator [\"bbb000b00b0b0\"] iscsiSessions;"


IQN:

SMcli -n Array1 -u admin@local -p adminPassword -k -c "show iscsiInitiator <\"iqn.0b0b-0b.com:b0b0b0b0b0b0\"> iscsiSessions;"
----

== Notes

If you enter this command without defining any arguments, this command returns information about all of the iSCSI sessions that are currently running. The following command returns information about all of the current iSCSI sessions:

----
show iscsiSessions
----

To limit the information that is returned, enter a specific iSCSI initiator or a specific iSCSI target. This command then returns information about the session for only the iSCSI initiator or the iSCSI target that you named.

An initiator name can be any combination of alpha or numeric characters from 1 to 30 characters in length. An IQN can be up to 255 characters in length and has this format:

----
iqn.yyyy-mm.naming-authority:unique name
----

== Minimum firmware level

7.10
