---
permalink: commands-a-z/show-drivechannel-stats.html
sidebar: sidebar
keywords: show, drive channel, statistics
summary: "The show driveChannel stats command shows the cumulative data transfer for the drive channel and error information."
---
= Show drive channel statistics
:icons: font
:imagesdir: ./media/

[.lead]
The `show driveChannel stats` command shows the cumulative data transfer for the drive channel and error information.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the controller has automatically degraded a drive channel, this command also shows interval statistics. When you use this command, you can show information about one specific drive channel, several drive channels, or all drive channels.

== Syntax

----
show (driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] |
   driveChannels [1 2 3 4 5 6 7 8] |
   allDriveChannels) stats
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*driveChannel*`
a|
The identifier number of the drive channel for which you want to show information. Valid drive channel values are `1`, `2`, `3`, `4`, `5`, `6`, `7`, or `8`. Enclose the drive channel in square brackets ([ ]).

Use this parameter when you want to show the statistics for only one drive channel.

a|
`*driveChannels*`
a|
The identifier numbers of several drive channels for which you want to show information. Valid drive channel values are `1`, `2`, `3`, `4`, `5`, `6`, `7`, or `8`. Enclose the drive channels in square brackets ([ ]) with the drive channel value separated with a space.

Use this parameter when you want to show the statistics for more than one drive channel.

a|
`*allDriveChannels*`
a|
The identifier that selects all of the drive channels.
|===

== Notes

None.

== Minimum firmware level

6.10

7.15 adds an update to the drive channel identifier.
