---
permalink: commands-a-z/show-ssd-cache-statistics.html
sidebar: sidebar
keywords: show, ssd, cache, statistics
summary: "The show ssdCache command displays data about the SSD cache usage."
---
= Show SSD cache statistics
:icons: font
:imagesdir: ./media/

[.lead]
The `show ssdCache` command displays data about the SSD cache usage.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600, and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Support Admin role.

== Syntax

[subs=+macros]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache for which you want to retrieve information. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
a|
`ssdCacheStatistics`
a|
An optional parameter to the `show ssdCache` command that indicates you want to retrieve cache statistics.
a|
`controller`
a|
Each controller stores SSD cache metadata for the volumes that it owns. Therefore, the SSD cache statistics are maintained and displayed per controller. Valid controller identifiers are `a`, `b`, or `both`, where `a` is the controller in slot A , `b` is the controller in slot B, and `both` is both controllers. Enclose the controller identifier in square brackets ([ ]). If you do not specify a controller, the default value is `both`.

a|
`file`
a|
The file path and the file name to which you want to save the SSD cache statistics. Additional statistics are available when you save the statistics to a file.

Enclose the file name in double quotation marks (" "). For example:

`file="C:\Program Files\CLI\logs\ssdcachestats.csv"`.

You can use any file name but you must use the `.csv` extension.

|===

== Notes

The following statistics are displayed on the screen:

* *Reads* -- total number of host reads of SSD cache-enabled volumes.
+
Compare the Reads relative to Writes. The Reads need to be greater than the Writes for effective SSD cache operation. The greater the ratio of Reads to Writes the better the operation of the cache.

* *Writes* -- total number of host writes to SSD cache-enabled volumes.
* *Cache Hits* -- a count of the number of cache hits.
* *Cache Hits (%)* -- derived from Cache Hits/total reads.
+
The Cache Hit percentage should be greater than 50 percent for effective SSD cache operation. A small number could be indicative of several things:

 ** Ratio of Reads to Writes is too small.
 ** Reads are not repeated.
 ** Cache capacity is too small.
+
[NOTE]
====
To help determine the ideal SSD cache capacity, you can run the Performance Modeling Tool using the `start ssdCache [ssdCacheName] performanceModeling` command.
====

* *Cache Allocation (%)* -- The amount of SSD cache storage that is allocated, expressed as a percentage of the SSD cache storage that is available to this controller. Derived from allocated bytes / available bytes.
+
Cache Allocation percentage normally shows as 100 percent. If this number is less than 100 percent, it means either the cache has not been warmed or the SSD cache capacity is larger than all the data being accessed. In the latter case, a smaller SSD cache capacity could provide the same level of performance. Note that this does not indicate that cached data has been placed into the SSD cache, it is simply a preparation step before data can be placed in the SSD cache.

* *Cache Utilization (%)* -- The amount of SSD cache storage that contains data from enabled volumes, expressed as a percentage of SSD cache storage that is allocated. This value represents the utilization or density of the SSD cache. Derived from user data bytes / allocated bytes.
+
Cache Utilization percentage normally is lower than 100 percent, perhaps much lower. This number shows the percent of SSD cache capacity that is filled with cache data. The reason this number is lower than 100 percent is that each allocation unit of the SSD cache, the SSD cache cache-block, is divided into smaller units called sub-blocks, which are filled somewhat independently. A higher number is generally better, but performance gains can be significant even with a smaller number.

These additional statistics are included when you save the data to a file:

* *Read Blocks* -- Number of blocks in host reads.
* *Write Blocks* -- Number of blocks in host writes.
* *Full Hit Blocks* -- Number of block cache hit.
+
The full hit blocks indicate the number of blocks that have been read entirely from SSD cache. The SSD cache is only beneficial to performance for those operations that are full cache hits.

* *Partial Hits* -- Number of host reads where at least one block, but not all blocks, were in the SSD cache. This is an SSD cache *miss* where the reads were satisfied from the base volume.
+
Partial cache hits and partial cache hit blocks result from an operation that has only a portion of its data in the SSD cache. In this case, the operation must retrieve the data from the cached HDD volume. The SSD cache offers no performance benefit for this type of hit. If the partial cache hit blocks count is higher than the full cache hit blocks, it is possible that a different I/O characteristic type (file system, database, or web server) could improve the performance.

* *Partial Hits -- Blocks* -- Number of blocks in Partial Hits.
+
Partial cache hits and partial cache hit blocks result from an operation that has only a portion of its data in the SSD cache. In this case, the operation must retrieve the data from the cached HDD volume. The SSD cache offers no performance benefit for this type of hit. If the partial cache hit blocks count is higher than the full cache hit blocks, it is possible that a different I/O characteristic type (file system, database, or web server) could improve the performance.

* *Misses* -- Number of host reads where none of the blocks were in the SSD cache. This is an SSD cache miss where the reads were satisfied from the base volume.
* *Misses -- Blocks* -- Number of blocks in Misses.
* *Populate Actions (Host Reads)* -- Number of host reads where data was copied from the base volume to the SSD cache.
* *Populate Actions (Host Reads) -- Blocks* -- Number of blocks in Populate Actions (Host Reads).
* *Populate Actions (Host Writes)* -- Number of host writes where data was copied from the base volume to the SSD cache.
+
The Populate Actions (Host Writes) count may be zero for the cache configuration settings that do not fill the cache as a result of a Write I/O operation.

* *Populate Actions (Host Writes) -- Blocks* -- Number of blocks in Populate Actions (Host Writes).
* *Invalidate Actions* -- Number of times data was invalidated/removed from the SSD cache. A cache invalidate operation is performed for every host write request, every host read request with Forced Unit Access (FUA), every verify request, and in some other circumstances.
* *Recycle Actions* -- Number of times that the SSD cache block has been re-used for another base volume and/or a different LBA range.
+
For effective cache operation, it is important that the number of recycles is small compared to the combined number of read and write operations. If the number of Recycle Actions is close to the combined number of Reads and Writes, then the SSD cache is thrashing. Either the cache capacity needs to be increased or the workload is not favorable for use with SSD cache.

* *Available Bytes* -- Number of bytes available in the SSD cache for use by this controller.
+
The available bytes, allocated bytes, and user data bytes are used to compute the Cache Allocation % and the Cache Utilization %.

* *Allocated Bytes* -- Number of bytes allocated from the SSD cache by this controller. Bytes allocated from the SSD cache may be empty or they may contain data from base volumes.
+
The available bytes, allocated bytes, and user data bytes are used to compute the Cache Allocation % and the Cache Utilization %.

* *User Data Bytes* -- Number of allocated bytes in the SSD cache that contain data from base volumes.
+
The available bytes, allocated bytes, and user data bytes are used to compute the Cache Allocation % and the Cache Utilization %.

== Minimum firmware level

7.84

11.80 adds EF600 and EF300 array support
