---
permalink: commands-a-z/show-volume-actionprogress.html
sidebar: sidebar
keywords: show, volume, action, progress
summary: "The show volume actionProgress command returns information about the volume action and amount of the long-running operation that is completed for a long-running operation on a volume."
---
= Show volume action progress
:icons: font
:imagesdir: ./media/

[.lead]
The `show volume actionProgress` command returns information about the volume action and amount of the long-running operation that is completed for a long-running operation on a volume.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Context

[NOTE]
====
With firmware version 7.77, the `show volume actionProgress` command is deprecated. Replace this command with `show storageArray longRunningOperations`.
====

The amount of the long-running operation that is completed is shown as a percentage (for example, 25 means that 25 percent of the long-running operation is completed).

== Syntax
[subs=+macros]
[source,cli]
----
show volume pass:quotes[[_volumeName_]] actionProgress
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`volume`
a|
The name of a volume for which you want to retrieve information about a long running operation. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the name in double quotation marks (" ") inside square brackets.

|===

== Minimum firmware level

5.43
