---
permalink: commands-a-z/show-snapgroup.html
sidebar: sidebar
keywords: show, snapshot, group
summary: "The show snapGroup command returns information about one or more snapshot image groups."
---
= Show snapshot group
:icons: font
:imagesdir: ../media/

[.lead]
The `show snapGroup` command returns information about one or more snapshot image groups.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
show (allSnapGroups | snapGroup pass:quotes[[_snapGroupName_]] |
snapGroups pass:quotes[["_snapGroupName1_" ... "_snapGroupNamen_"]])
[summary | schedule]
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`allSnapGroups`
a|
The parameter to return information about all of the snapshot groups in the storage array.
a|
`snapGroup`
a|
The name of the snapshot group for which you want to retrieve information. Enclose the snapshot group name in square brackets ([ ]). If the snapshot group name has special characters or numbers, you must enclose the snapshot group name in double quotation marks (" ") inside square brackets.

a|
`snapGroups`
a|
The names of several snapshot groups for which you want to retrieve information. Enter the names of the snapshot groups using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the snapshot group names have special characters or consist only of numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

a|
`summary`
a|
The parameter to return a concise list of information about the snapshot groups.
a|
`schedule`
a|
The parameter to return a concise list of information about the schedules for the snapshot group copy operations.
|===

== Notes

You can use any combination of alphanumeric characters, underscore (_), hyphen (-), and pound (#) for the names. Names can have a maximum of 30 characters.

This command returns snapshot group information as shown in this example:

----
SNAPSHOT GROUP DETAILS

SNAPSHOT GROUPS-----------------------------

SUMMARY
----

----
  Total Snapshot Groups: 1
  Total Snapshot Images: 0
  Enabled Snapshot Image Schedules: 0
  Status: 1 Optimal, 0 Non Optimal

  Name      Type       Status    Associated Base Volume
  2_SG_01   Standard   Optimal   2
  Total Repository Capacity  Available Repository Capacity  Snapshot Image Limit
  10.318 GB                  10.318 GB (100%)               0

  Snapshot Images   Scheduled
  0                 No
DETAILS

  Snapshot Group "2_SG_01"

   Status:  Optimal
   Type:    Standard
   Associated base volume: 2
   Cluster size: 65,536 bytes

   Repository

    Total repository volumes: 3
    Aggregate repository status: Optimal
    Total repository capacity:   10.318 GB
    Used capacity:           0.000 MB (0%)
    Available repository capacity: 10.318 GB (100%)
    Repository full policy:    Auto-purge Snapshot Images
    Utilization alert threshold: 75%

   Snapshot images

    Total Snapshot images: 0
    Auto-delete Snapshot images: Disabled
    Snapshot image schedule:   Not Applicable
----

== Minimum firmware level

7.83
