---
permalink: commands-a-z/show-volume-reservations.html
sidebar: sidebar
keywords: show, volume, reservations
summary: "The show volume reservations command returns information about the volumes that have persistent reservations."
---
= Show volume reservations
:icons: font
:imagesdir: ./media/

[.lead]
The `show volume reservations` command returns information about the volumes that have persistent reservations.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Storage Monitor role.

== Syntax
[subs=+macros]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) reservations
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`allVolumes`
a|
The parameter to return performance statistics about all of the volumes in the storage array.
a|
`volume`
a|
The name of a volume for which you want to retrieve information. Enclose the volume name in square brackets ([ ]). If the volume name has special characters or numbers, you must enclose the name in double quotation marks (" ") inside square brackets.

a|
`volumes`
a|
The names of several volumes for which you want to retrieve information. Enter the names of the volumes using these rules:

* Enclose all of the names in square brackets ([ ]).
* Separate each of the names with a space.

If the volume names have special characters or numbers, enter the names using these rules:

* Enclose all of the names in square brackets ([ ]).
* Enclose each of the names in double quotation marks (" ").
* Separate each of the names with a space.

|===

== Minimum firmware level

5.40
