---
permalink: /commands-a-z/smcli-supportbundle-schedule.html
sidebar: sidebar
keywords: 
summary: 'The SMcli -supportBundle schedule command creates or removes a schedule for saving a support bundle on one or more storage arrays. You collect system and configuration information in support bundles to transmit the information to technical support for analysis and diagnostics.'
---
= Schedule automatic support bundle collection configuration
:icons: font
:imagesdir: ./media/

[.lead]
The `SMcli -supportBundle schedule` command creates or removes a schedule for saving a support bundle on one or more storage arrays. You collect system and configuration information in support bundles to transmit the information to technical support for analysis and diagnostics.

[NOTE]
====
This command is an SMcli command, not a script command. You must run this command from a command line. You cannot run this command from the script editor in the storage management software.
====

You can create two types of schedules:

* Daily/Weekly -- Use this schedule when you need to frequently collect data to monitor new configurations or troubleshoot an existing configuration.
* Monthly/Yearly -- Use this schedule when you are collecting data for evaluating the long term operation of your storage array.

== Syntax for creating a daily/weekly schedule

----
SMcli -supportBundle schedule enable
(all | storageArrayName)
startTime=HH:MM
startDate=MM:DD:YYYY
endDate=MM:DD:YYYY
daysOfWeek=[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
data=pathName
----

== Syntax for creating a monthly/yearly schedule

----
SMcli -supportBundle schedule enable
(all | storageArrayName)
startTime=HH:MM
startDate=MM:DD:YYYY
endDate=MM:DD:YYYY
months=[January February March April May June July August September October
November December]
weekNumber=(First|Second|Third|Fourth|Last)
dayOfWeek=(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)|
onDays=[1-31] |
data=pathName
----

== Syntax for removing a schedule

[NOTE]
====
This command completely removes the schedule for the storage array. To start saving support bundle information again, you need to create a new schedule.
====

----
SMcli -supportBundle schedule disable
(all|storageArrayName)
----

== Parameters

The following table lists the parameters for a daily/weekly schedule.

|===
| Parameter| Description
a|
`enable`
a|
Enable automatic collection of support bundles when a critical MEL event is detected. This parameter resumes collecting support bundle data if it has been suspended. You must use the parameter whenever you create a new schedule or modify an existing schedule.
a|
`all`
a|
Use this parameter if you want to set a collection schedule for all of the storage arrays detected from the host.
a|
`storageArrayName`
a|
The name of a specific storage array for which you want to set a schedule.
a|
`startTime`
a|
The time of day that you want the collection of a support bundle to start. The format for entering the time is HH:MM, where HH is the hour and MM is the minute past the hour. Use a 24-hour clock.

The default time is 00:00, midnight. If you do not enter a time to start and you have enabled support bundle collection, collection of the data automatically occurs at midnight.

a|
`startDate`
a|
A specific date on which you want to start collecting support bundle data. The format for entering the date is MM:DD:YY.

The default date is the current date.

a|
`endDate`
a|
A specific date on which you want to stop collecting support bundle data. The format for entering the date is MM:DD:YY.

The default is none.

If you use this parameter, it must be at least one week after the start date and cannot occur in the past.

a|
`daysOfWeek`
a|
Specific day or days of the week on which you want to collect support bundle data. Use this parameter when you want to collect support bundle data on one or more days of week. For example:

----
daysOfWeek=[Tuesday]
----

----
daysOfWeek=[Monday Wednesday Friday]
----

Enclose the days of the week in square brackets ([ ]). If you enter more than one day, separate each day with a space.

a|
`data`
a|
The file path and the file name to which you want to save the support bundle data. For example:

----
file="C:\Program Files\CLI\sup\data.txt"
----

[NOTE]
====
You can use any file extension.
====

Enclose the file path and name in double quotation marks (" ").

|===
The following table lists the parameters for a monthly/yearly schedule.

|===
| Parameter| Description
a|
`enable`
a|
Enable automatic collection of support bundles when a critical MEL event is detected. This parameter resumes collecting support bundle data if it has been suspended. You must use the parameter whenever you create a new schedule or modify an existing schedule.
a|
`all`
a|
Use this parameter if you want to set a collection schedule for all of the storage arrays detected from the host.
a|
`storageArrayName`
a|
The name of a specific storage array for which you want to set a schedule.
a|
`startTime`
a|
The time of a day that you want the collection of a support bundle to start. The format for entering the time is HH:MM, where HH is the hour and MM is the minute past the hour. Use a 24-hour clock.

The default time is 00:00, midnight. If you do not enter a time to start and you have enabled support bundle collection, collection of the data automatically occurs at midnight.

a|
`startDate`
a|
A specific date on which you want to start collecting support bundle data. The format for entering the date is MM:DD:YY.

The default date is the current date.

a|
`endDate`
a|
A specific date on which you want to stop collecting support bundle data. The format for entering the date is MM:DD:YY.

The default is none.

a|
`months`
a|
Specific month or months of the year on which you want to collect support bundle data. Use this parameter when you want to collect support bundle data on one or more months of a year. For example:

----
months=[June]
----

----
months=[January April July October]
----

Enclose the month in square brackets ([ ]). If you enter more than one month, separate each month with a space.

a|
`weekNumber`
a|
A week in the month during which you want to collect support bundle data. For example:

----
weekNumber=first
----

a|
`dayOfWeek`
a|
A specific day of the week on which you want to collect support bundle data. Use this parameter when you want to collect support bundle data on only one day of the week. For example:

----
dayOfWeek=Wednesday
----

a|
`onDays`
a|
Specific day or days in a month on which you want to collect support bundle data. For example:

----
onDays=[15]
----

----
onDays=[7 21]
----

Enclose the day in square brackets ([ ]). If you enter more than one day, separate each day with a space.

[NOTE]
====
You cannot use the `onDays` parameter with either the `weekNumber` parameter or the `dayOfWeek` parameter.
====

a|
`data`
a|
The file path and the file name to which you want to save the support bundle data. For example:

----
file="C:\Program Files\CLI\sup\data.txt"
----

[NOTE]
====
You can use any file extension.
====

Enclose the file path and name in double quotation marks (" ").

|===
The following table lists the parameters for removing a schedule.

|===
| Parameter| Description
a|
`disable`
a|
Disables the automatic collection of support bundles and deletes any previously defined schedules immediately.

[NOTE]
====
Disabling a schedule also deletes the schedule.
====

a|
`all`
a|
Use this parameter if you want to set a collection schedule for all of the storage arrays detected from the host.
a|
`storageArrayName`
a|
The name of a specific storage array for which you want to set a schedule.
|===

== Notes

When you use the `all` parameter to set a common schedule for all of the storage arrays, the schedules for individual storage arrays are deleted. If a schedule is set for all storage arrays, newly discovered storage arrays will follow the same schedule. If a schedule is set for all storage arrays and then a schedule is set for a single storage array, newly discovered storage arrays will not have a schedule defined.

Following are examples of the usage of this command. The first example is of a daily/weekly schedule that meets these criteria for collecting support bundle data:

* The storage array name is DevKit4
* The collection start time is 02:00 (2:00 in the morning)
* The start date is 05:01:2013 (May 1, 2013)
* Data will be collected on Monday and Friday of each week
* This schedule does not have an end date, and can be stopped only by running the `SMcli -supportBundle schedule disable` command

----
SMcli -supportBundle schedule enable DevKit4 startTime=02:00
startDate=05:01:2013 endDate=05:10:2014 daysOfWeek=[Monday Friday]
----

The second example is of a monthly/yearly schedule that meets these criteria for collecting support bundle data:

* The storage array name is eng_stor1
* The collection start time is 04:00 (4:00 in the morning)
* The start date is 05:01:2013 (May 1, 2013)
* Data will be collected in March, April, May, June, and August
* Data will be collected on the first and twenty-first days of each month
* This schedule does not have an end date, and can be stopped only by running the `SMcli -supportBundle schedule disable` command

----
SMcli -supportBundle schedule enable eng_stor1 startTime=04:00
startDate=05:01:2013 months=[March April May June August] onDays=[1 21]
----

The third example is of a monthly/yearly schedule that meets these criteria for collecting support bundle data:

* The storage array name is firmware_2
* The collection start time is 22:00 (10:00 at night)
* The start date is 05:01:2013 (May 1, 2013)
* Data will be collected in March, April, May, June, and August
* Data will be collected on Friday of the first week of each month
* This schedule will end on 05:10:2014 (May 10, 2014)

----
SMcli -supportBundle schedule enable firmware_2 startTime=22:00
startDate=05:01:2013 endDate=05:10:2014 months=[March April May June August]
weekNumber=First dayOfWeek=Friday
----

== Minimum firmware level

7.83
