---
permalink: commands-a-z/smcli-autosupportconfig.html
sidebar: sidebar
keywords: specify, autosupport, delivery, method
summary: "The SMcli -autoSupportConfig command sets up the delivery method for sending AutoSupport messages."
---
= Specify the AutoSupport delivery method
:icons: font
:imagesdir: ./media/

[.lead]
The `SMcli -autoSupportConfig` command sets up the delivery method for sending AutoSupport messages.

== Supported Arrays

This command applies to all E2700 and E5600 storage arrays in the management domain at once. It does not apply to E2800 or E5700 storage arrays.

== Context

[NOTE]
====
This command is an SMcli command, not a script command. You must run this command from a command line. You cannot run this command from the script editor in the storage management software.
====

You can create two major types of delivery methods for sending AutoSupport messages:

* SMTP -- Use this method when you want to use email as the delivery method for sending AutoSupport messages.
* HTTP/HTTPS -- Use this method when you want to send AutoSupport messages using the HTTP or HTTPS protocols. You need to use HTTPS if you want to use AutoSupport OnDemand or AutoSupport Remote Diagnostics.

== Syntax for SMTP Delivery Method

----
SMcli -autoSupportConfig deliveryMethod=SMTP
mailRelayServer=<mailRelayServerName> senderMail=<senderEmailAddress>
----

== Parameters for the SMTP Delivery Method

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`deliveryMethod`
a|
Allows you to specify the delivery method of the AutoSupport messages. Valid choice is SMTP. See the next section of this topic for information about using HTTP or HTTPS, which are also valid.

a|
`mailRelayServer`
a|
Allows you to specify the mail relay server for the AutoSupport messages.

a|
`senderMail`
a|
Allows you to specify the sender email address for the AutoSupport messages.

|===

== Syntax for HTTP/HTTPs Delivery Methods

----
SMcli -autoSupportConfig deliveryMethod={HTTP|HTTPS}
 {direct|proxyConfigScript=<proxyConfigScript>| proxyServer
hostAddress:<address>portNumber=<portNumber> [userName=<userName>password=<password>]}
----

== Parameters for the HTTP/HTTPS Delivery Methods

The following table lists the parameters for the HTTP/HTTPS delivery methods.

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`deliveryMethod`
a|
Allows you to specify the delivery method of the AutoSupport messages. Valid choices are HTTPS and HTTP (see prior section for use of SMTP, which is also valid).

a|
`direct`
a|
Allows you to connect directly to the destination technical support systems using the HTTPS or HTTP protocols.

a|
`proxyConfigScript`
a|
Allows you to specify the location of a Proxy Auto-Configuration (PAC) script file.

a|
`proxyServer`
a|
Allows you to specify the HTTP(s) proxy server details required for establishing connection with the destination technical support system.

a|
`hostAddress`
a|
The host IP address of the proxyServer.

a|
`portNumber`
a|
The port number of the proxy server. This parameter is required when the proxyServer parameter is used.

a|
`userName`
a|
The user name. This parameter is required.

a|
`password`
a|
The authentication password. This parameter is required.

|===

== Minimum Firmware Level

8.25

== Examples

----
SMcli –autoSupportConfig deliveryMethod=SMTP
mailRelayServer:server.eng.netapp.com
senderEmail:user@netapp.com
----

----
SMcli -autoSupportConfig deliveryMethod=HTTPS
proxyServer hostAddress:10.117.12.112 portNumber=8080
userName=user password=0987654321
----

== Verification

Send a test message using the `SMcli -autoSupportConfig test` command to verify that your delivery methods are set up correctly.
