---
permalink: commands-a-z/smcli-autosupportlog.html
sidebar: sidebar
keywords: capture, view, autosupport, log
summary: "The SMcli -autoSupportLog command allows you to view an AutoSupport log file. This file provides information about status, history of transmission activity, and any errors encountered during delivery of the AutoSupport messages. The log is available for all AutoSupport-capable and AutoSupport-enabled storage arrays."
---
= Capture or view an AutoSupport log
:icons: font
:imagesdir: ./media/

[.lead]
The `SMcli -autoSupportLog` command allows you to view an AutoSupport log file. This file provides information about status, history of transmission activity, and any errors encountered during delivery of the AutoSupport messages. The log is available for all AutoSupport-capable and AutoSupport-enabled storage arrays.

== Supported Arrays

This command applies to all E2700 and E5600 storage arrays in the management domain at once. It does not apply to E4000, E2800, or E5700 storage arrays.

== Context

This command allows you to view two types of logs:

* Current log- View the log captured at this point in time.
* Archive log- View the log from an archived file.

[NOTE]
====
This command is an SMcli command, not a script command. You must run this command from a command line. You cannot run this command from the script editor in the storage management software.
====

== Syntax
[subs=+macros]
[source,cli]
----
SMcli -autoSupportLog pass:quotes[(all|-n "_storageArrayName_" | -w "_wwID_")]
pass:quotes[inputArchive=_n_] pass:quotes[outputLog=_filename_]
----

== Parameters

The following table lists the command parameters.

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`all`
a|
Use this parameter if you want to create a transmission log for all of the storage arrays in the management domain with AutoSupport capability that have been AutoSupport enabled.
a|
`_n_`
a|
The name for the storage array for which you want to view an AutoSupport log.

a|
`_w_`
a|
The World Wide Identifier (WWID) of the storage array for which you want to view an AutoSupport log.

a|
`inputArchive`
a|
Allows you to specify the archived AutoSupport log, where the archive file is `_n_`, an integer from 0 to 5.

[NOTE]
====
Omitting this parameter means you select the current AutoSupport log (captured at this point in time).
====

a|
`outputLog`
a|
Allows you to specify the output AutoSupport log filename.

[NOTE]
====
This parameter is required.
====

|===

== Minimum Firmware Level

8.25

== Example

----
SMcli -autosupportLog -n StorageArrayName inputArchive=0 outputLog=ASUPTransmissionLog
----

== Verification

View the AutoSupport log you requested, which is in the client directory where the storage management software was installed.
