---
permalink: commands-a-z/start-storagearray-autosupport-deliverytest.html
sidebar: sidebar
keywords: 
summary: 'The start storageArray autoSupport deliveryTest command sends a sample AutoSupport bundle collection message so you can test the connection to the destination technical support system using the specified delivery parameters.'
---
= Test AutoSupport delivery settings (for individual E2800 or E5700 arrays)
:icons: font
:imagesdir: ./media/

[.lead]
The `start storageArray autoSupport deliveryTest` command sends a sample AutoSupport bundle collection message so you can test the connection to the destination technical support system using the specified delivery parameters.

== Supported Arrays

This command applies to an individual E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax

----
start storageArray autoSupport deliveryTest [replyToEmail="address"]
----

== Parameters

|===
| Parameter| Description
a|
`replyToEmail`
a|
Allows the user to specify the reply-to email address for the AutoSupport test message. It is only used/required when delivery method is set to email.
|===

== Minimum Firmware Level

8.40

== Examples

----

SMcli -n Array1 -c "start storageArray autoSupport deliveryTest;"

SMcli -n Array1 -c "start storageArray autoSupport deliveryTest replyToEmail=\"user@company.com\";"

The sample AutoSupport message was successfully sent to the ASUP gateway server.

SMcli completed successfully.
----

== Minimum firmware level

8.40
