---
permalink: commands-a-z/start-controller-iscsihostport-dhcprefresh.html
sidebar: sidebar
keywords: start, iscsi, dhcp, refresh
summary: "The start controller iscsiHostPort dhcpRefresh command initiates a refresh of the DHCP parameters for the iSCSI interface."
---
= Start iSCSI DHCP refresh
:icons: font
:imagesdir: ./media/

[.lead]
The `start controller iscsiHostPort dhcpRefresh` command initiates a refresh of the DHCP parameters for the iSCSI interface.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the configuration method for the interface is not set to DHCP, the procedure returns an error.

== Syntax

----
start controller [(a|b)] iscsiHostPort [portLabel] dhcpRefresh
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`controller`
a|
The identifier letter of the controller that has the iSCSI host ports. Valid controller identifier values are `a` or `b` where `a` is the controller in slot A, and `b` is the controller in slot B.
a|
`iscsiHostPort`
a|
The host port label or the number of the iSCSI host port for which you want to refresh the DHCP parameters.

See the following for more information:

<<Identifying an iSCSI host port label,"Identifying an iSCSI host port label">>

|===

== Identifying an iSCSI host port label

You must specify a label for the host port. Follow these steps to specify the host port label:

.Steps

. If you do not know the port label for the iSCSI host port, run the `show controller` command.
. In the Host interface section of the results, locate the host port you want to select.
+
[NOTE]
====
The port label is the complete value returned for the `Port` field.
====

. Enclose the entire value of the port label in both quotes and square brackets: ["portLabel"]. For example, if the port label is `Ch 2`, specify the iSCSI host port as follows:
+
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
If you are using a Windows command line and the label contains a pipe (|), the character should be escaped (using {caret}); otherwise, it will be interpreted as a command. For example, if the port label is `e0b|0b`, specify the iSCSI host port as follows:
====
+
----
iscsiHostPort[\"e0b^|0b\"]
----

[NOTE]
====
For backward compatibility, the iscsiPortNumber, enclosed by braces [ ] rather than quotes and braces [" "] can still be used for E2700, E5600, or EF560 controllers (and other previous generations of E-Series or EF-Series controllers). For those controllers, valid values for iscsiPortNumber are as follows:

* For controllers with integrated host ports, the numbering is 3, 4, 5, or 6.
* For controllers with host ports on a host interface card only, the numbering is 1, 2, 3, or 4.

An example of the prior syntax is as follows:

----
iscsiHostPort[3]
----

====

== Notes

This operation ends the iSCSI connections for the portal and temporarily brings down the portal.

== Minimum firmware level

7.10

8.10 revises the numbering system for iSCSI host ports.

8.30 revises the identification method for iSCSI host ports in the E2800.
