---
permalink: commands-a-z/start-volumegroup-defragment.html
sidebar: sidebar
keywords: start, volume, group, defragment
summary: "The start volumeGroup defragment command starts a defragment operation on the specified volume group."
---
= Start volume group defragment
:icons: font
:imagesdir: ../media/

[.lead]
The `start volumeGroup defragment` command starts a defragment operation on the specified volume group.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
Defragmenting a volume group starts a long-running operation that you cannot stop.
====

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] defragment
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`volumeGroup`
a|
The name of the volume group that you want to defragment. Enclose the volume group name in square brackets ([ ]).
|===

== Notes

Host I/O errors might result in the volume groups with more than 32 volumes. This operation also might result in internal controller reboots because the timeout period ends before the volume group definition is set. If you experience this issue, quiesce the host I/O operations, and try the command again.

== Minimum firmware level

6.10
