---
permalink: commands-a-z/start-asyncmirrorgroup-synchronize.html
sidebar: sidebar
keywords: start, asynchronous, mirror, synchronization
summary: "The start asyncMirrorGroup synchronize command starts Asynchronous Mirroring synchronization."
---
= Start asynchronous mirroring synchronization
:icons: font
:imagesdir: ./media/

[.lead]
The `start asyncMirrorGroup synchronize` command starts Asynchronous Mirroring synchronization.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600, and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
start asyncMirrorGroup pass:quotes[["_asyncMirrorGroupName_"]] synchronize [deleteRecoveryPointIfNecessary]
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`asyncMirrorGroup`
a|
The name of the asynchronous mirror group for which you want to start synchronization. Enclose the asynchronous mirror group name in double quotation marks (" ") inside square brackets ([" "]).

a|
`deleteRecoveryPointIfNecessary`
a|
The parameter to delete the recovery point if the recoverable synchronization data has exceeded time threshold for recovery. Recovery point age is measured from the time the data was frozen on the primary storage array.

|===

== Minimum firmware level

7.84

8.10 adds the `deleteRecoveryPointIfNecessary` parameter.

11.80 adds EF600 and EF300 array support

