---
permalink: commands-a-z/start-storagearray-externalkeymanagement-test.html
sidebar: sidebar
keywords: test, external key, management, communication
summary: "The start storageArray externalKeyManagement test command uses the configured credentials (certificates, address of the KMIP server, and the KMIP port number) to verify that the storage array is able to communicate with the external KMIP server."
---
= Test external key management communication - SANtricity CLI
:icons: font
:imagesdir: ../media/

[.lead]
The `start storageArray externalKeyManagement test` command uses the configured credentials (certificates, address of the KMIP server, and the KMIP port number) to verify that the storage array is able to communicate with the external KMIP server.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700,EF600, or EF300 storage array, you must have the Security Admin role.

== Context

[NOTE]
====
This command applies only to external key management.
====

== Syntax
[source,cli]
----
start storageArray externalKeyManagement test
----

== Parameters

None.

== Notes

The following example shows the output of the command when the storage array is able to communicate with the external key management server. The output includes the status of the key management server, client certificate, and server certificate.

----
Key servers configured:
C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>SMcli.bat 10.115.XX.XXX -u admin -p infiniti -k -c "start storageArray externalKeyManagement test;"
Performing syntax check...

Syntax check complete.

Executing script...

SUMMARY:
   Key management server:
      Server address: ::
      Server port: 9003
      Local controller status: Connection failure
      Alternate controller status: Unknown
      Client certificate status: Ok
      Server certificate status: Ok

DETAILS:
Unable to communicate with the key management server. To correct the problem, perform the
following steps: 1) Check that the key management server address and port is correct. 2) If
the key management server's address is a domain name, check that both controller's DNS
servers are operational and reachable from the controller given your network configuration.
3) Check that the key management server operational and reachable from the controller given
your network configuration. 4) Once the problem has been found and corrected, re-perform the
communication test between the storage array and key management server to clear the needs
attention state on the array.


Script execution complete.

SMcli completed successfully.

C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>


No key servers configured:
C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>SMcli.bat 10.115.XX.XXX -u admin -p infiniti -k -c "start storageArray externalKeyManagement test;"
Performing syntax check...

Syntax check complete.

Executing script...

No key management servers configured.

Script execution complete.

SMcli completed successfully.

C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>
----

== Minimum firmware level

8.40


