---
permalink: commands-a-z/start-ssdcache-locate.html
sidebar: sidebar
keywords: start, ssd, cache, locate
summary: "The start ssdCache locate command identifies the Solid State Disks (SSDs) that are logically grouped together to form the SSD cache by blinking the indicator lights on the SSDs."
---
= Start SSD cache locate
:icons: font
:imagesdir: ./media/

[.lead]
The `start ssdCache locate` command identifies the Solid State Disks (SSDs) that are logically grouped together to form the SSD cache by blinking the indicator lights on the SSDs.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Context

Use the `stop ssdCache locate` command to turn off the indicator lights on the drives.

== Syntax
[subs=+macros]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*ssdCache*`
a|
The name of the SSD cache that you want to locate. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name contains special characters or consists only of numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
|===

== Minimum firmware level

7.84
