---
permalink: commands-a-z/start-syncmirror-primary-synchronize.html
sidebar: sidebar
keywords: start, synchronous, mirror, synchronization
summary: "The start syncMirror primary synchronize command starts synchronous mirroring synchronization."
---
= Start synchronous mirroring synchronization
:icons: font
:imagesdir: ../media/

[.lead]
The `start syncMirror primary synchronize` command starts synchronous mirroring synchronization.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, or E5700 storage array, you must have the Storage Admin role.

== Context

[NOTE]
====
In previous versions of this command the feature identifier was `remoteMirror`. This feature identifier is no longer valid and is replaced by `syncMirror`.
====

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[start syncMirror primary ["_volumeName_"]] synchronize
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`primary`
a|
The name of the primary volume for which you want to start synchronization. Enclose the primary volume name in double quotation marks (" ") inside of square brackets ([ ]).
|===

== Minimum firmware level

6.10
