---
permalink: /commands-a-z/start-secureerase-drive.html
sidebar: sidebar
keywords: 
summary: 'The start secureErase drive command erases all of the data from one or more full disk encryption \(FDE\) drives so that they can be reused as FDE drives.'
---
= Start FDE secure drive erase
:icons: font
:imagesdir: ./media/

[.lead]
The `start secureErase drive` command erases all of the data from one or more full disk encryption (FDE) drives so that they can be reused as FDE drives.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Security Admin role.

== Context

Run this command only when the FDE drives are no longer part of a secure volume group or disk pool, or when the security key is unknown.

[NOTE]
====
To erase a FIPS drive when the drive is locked and the security key to unlock it is unavailable, use the `set drive securityID` command.
====

== Syntax

----
start secureErase (drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
----

== Parameters

|===
| Parameter| Description
a|
`drive` or `drives`
a|
For high-capacity drive trays, specify the tray ID value, the drawer ID value, and the slot ID value for the drive. For low-capacity drive trays, specify the tray ID value and the slot ID value for the drive. Tray ID values are `0` to `99`. Drawer ID values are `1` to `5`.

All slot ID maximums are 24. Slot ID values either begin at 0 or 1, depending on the tray model. Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0. Drive trays compatible with E2700 and E5600 controllers have slot ID numbers starting at 1.

Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ]).

[NOTE]
====
The drives list cannot contain all of the drives in the storage array, or the command will be rejected. To secure erase all drives, run this command twice, specifying the drive list in two separate groups.
====

|===

== Notes

The controller firmware creates a lock that restricts access to the FDE drives. FDE drives have a state called Security Capable. When you create a security key, the state is set to Security Enabled, which restricts access to all FDE drives that exist within the storage array.

== Minimum firmware level

7.40
