---
permalink: commands-a-z/start-snmptrapdestination.html
sidebar: sidebar
keywords: test, snmp, trap, destination
summary: "The start snmpTrapDestination command tests the connection and identification of the trap receiver for a specific Simple Network Management Protocol (SNMP) community or user. This command tests the trap destination by sending a trap message to the trap receiver."
---
= Test SNMP trap destination
:icons: font
:imagesdir: ./media/

[.lead]
The `start snmpTrapDestination` command tests the connection and identification of the trap receiver for a specific Simple Network Management Protocol (SNMP) community or user. This command tests the trap destination by sending a trap message to the trap receiver.

== Supported Arrays

This command applies to an individual E4000, E2800, E5700, EF600 or EF300 storage array. It does not operate on E2700 or E5600 storage arrays.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin or Support Admin role.

== Syntax
[subs=+macros]
[source,cli]
----
start snmpTrapDestination trapReceiverIP=ipAddress
    pass:quotes[(communityName="_communityName_" | (userName="_userName_"] [engineId=(local | engineId)]))
----

== Parameters

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`trapReceiverIP`
a|
The IP address of the SNMP manager to which you want to send trap messages.
a|
`communityName`
a|
The name of the SNMP community for which you want to send trap messages.
a|
`userName`
a|
The name of the SNMP user for which you want to send trap messages.
a|
`engineId`
a|
The engine ID of the SNMP user for which you want to send trap messages. The engine ID is required if there is more than one USM user with the same user name. The value may be "[.code]``local``" to specify the local SNMP agent is the authoritative agent or a hexidecimal digit string to specify a remote SNMP agent engine ID.
|===

== Minimum firmware level

8.30
