---
permalink: commands-a-z/start-volumegroup-import.html
sidebar: sidebar
keywords: start, volume, group, import
summary: "The start volumeGroup import command moves a volume group into a Complete state to make a newly introduced volume group available to its new storage array."
---
= Start volume group import
:icons: font
:imagesdir: ./media/

[.lead]
The `start volumeGroup import` command moves a volume group into a Complete state to make a newly introduced volume group available to its new storage array.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

The volume group must be in an Exported state or a Forced state before you run this command. Upon successfully running the command, the volume group is operational.

[NOTE]
====
Within the volume group, you cannot move volumes that are associated with the features from one storage array to another storage array.
====

== Syntax
[subs=+macros]
[source,cli]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] import
----

== Parameter

[cols="2*",options="header"]
|===
| Parameter| Description
a|
`volumeGroup`
a|
The name of the volume group that you want to import. Enclose the volume group name in square brackets ([ ]).
|===

== Notes

Higher-level volumes that are specifically related to features (Synchronous Mirroring, Volume Copy, mapping, and persistent reservations) are removed as part of the import operation.

You must run the `show volumeGroup importDependencies` command before you run the `start volumeGroup import` command.

== Minimum firmware level

7.10
