---
permalink: commands-a-z/start-check-vol-parity-job.html
sidebar: sidebar
keywords: start, check, volume, parity, job
summary: "The start check volume parity job command starts a new check volume parity operation on a given volume."
---
= Start check volume parity job
:icons: font
:imagesdir: ./media/

[.lead]
The `start check volume parity job` command starts a new check volume parity operation on a given volume.

== Supported Arrays

This command applies to any individual storage array, including the EF600 and EF300 arrays; as long as all SMcli packages are installed.

== Roles

To execute this command on an EF600 and EF300 storage array, you must have the Storage Admin role.

== Syntax
[subs=+macros]
----
start check volume[<volume_label>] parity job 
(startingLba=<start_lba> endingLba=<end_lba> scanPriority=<scan_priority> repairParityErrors=<true | false>         
repairMediaErrors=<true | false>);
----

== Parameters
[options="header"]
|===
| Parameter| Description
a|
`startingLba`
a|
The volume logical block address where the parity scan will start. The default value is `0`.
a|
`endingLba`
a|
The volume logical block address where the parity scan will stop. The default value is `maximum volume lba`.

a|
`scanPriority`
a|
The parity scan priority. The default value is `medium`

a|
`repairParityErrors`
a|
Determines whether to automatically attempt to repair parity errors detected during the parity scan. Default value is `true`.

a|
`repairMediaErrors`
a|
Determines whether to automatically attempt to repair media errors detected during the parity scan. Default value is `true`.

|===

== Minimum firmware level

11.80
