---
permalink: commands-a-z/start-storagearray-isnsserverrefresh.html
sidebar: sidebar
keywords: start, storage, array, isns, server, refresh
summary: "The start storageArray isnsServerRefresh command initiates a refresh of the network address information for the iSNS server."
---
= Start storage array iSNS server refresh
:icons: font
:imagesdir: ../media/

[.lead]
The `start storageArray isnsServerRefresh` command initiates a refresh of the network address information for the iSNS server.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Context

If the DHCP server is marginal or unresponsive, the refresh operation can take from two to three minutes to complete.

[NOTE]
====
This command is for IPv4 only.

====

== Syntax
[source,cli]
----
start storageArray isnsServerRefresh
----

== Parameter

None.

== Notes

If you used the `set storageArray isnsIPv4ConfigurationMethod` command to set the configuration but did not set the configuration to DHCP, running the `start storageArray isnsServerRefresh` returns an error.

== Minimum firmware level

7.10
