---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html
sidebar: sidebar
keywords: stop, storage, array, drive, firmware, download
summary: "The stop storageArray driveFirmwareDownload command stops a firmware download to the drives in a storage array that was started with the download storageArray driveFirmware command."
---
= Stop storage array drive firmware download - SANtricity CLI
:icons: font
:imagesdir: ../media/

[.lead]
The `stop storageArray driveFirmwareDownload` command stops a firmware download to the drives in a storage array that was started with the `download storageArray driveFirmware` command.

== Supported Arrays

This command applies to any individual storage array, including the E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50, and EF80 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E4000, E2800, E5700, EF600, EF300, EF50, or EF80 storage array, you must have the Storage Admin role.

== Context

This command does not stop a firmware download that is already in progress to a drive. This command stops all firmware downloads to drives that are waiting for the download.

== Syntax
[source,cli]
----
stop storageArray driveFirmwareDownload
----

== Parameters

None.

== Minimum firmware level

6.10
