---
permalink: commands-a-z/stop-volumecopy-target-source.html
sidebar: sidebar
keywords: stop, volume, copy
summary: "The stop volumeCopy target source command stops a volume copy operation. This command is valid for snapshot volume copy pairs."
---
= Stop volume copy
:icons: font
:imagesdir: ./media/

[.lead]
The `stop volumeCopy target source` command stops a volume copy operation. This command is valid for snapshot volume copy pairs.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, E5700, EF600 and EF300 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800, E5700, EF600, or EF300 storage array, you must have the Storage Admin role.

== Syntax

----
stop volumeCopy target [targetName] source [sourceName]
----

== Parameters
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`*target*`
a|
The name of the target volume for which you want to stop a volume copy operation. Enclose the target volume name in square brackets ([ ]). If the target volume name has special characters or numbers, you must enclose the target volume name in double quotation marks (" ") inside square brackets.
a|
`*source*`
a|
The name of the source volume for which you want to stop a volume copy operation. Enclose the source volume name in square brackets ([ ]). If the source volume name has special characters or numbers, you must enclose the source volume name in double quotation marks (" ") inside square brackets.
|===
