---
permalink: commands-a-z/suspend-ssdcache.html
sidebar: sidebar
keywords: suspend, ssd cache
summary: "The suspend ssdCache command temporarily stops caching for all of the volumes that are using the SSD cache."
---
= Suspend SSD cache
:icons: font
:imagesdir: ./media/

[.lead]
The `suspend ssdCache` command temporarily stops caching for all of the volumes that are using the SSD cache.

== Supported Arrays

This command applies to any individual storage array, including the E2700, E5600, E2800, and E5700 arrays, as long as all SMcli packages are installed.

== Roles

To execute this command on an E2800 or E5700 storage array, you must have the Support Admin role.

== Context

While caching is stopped, host reads are serviced from the base volumes instead of from the SSD cache.

== Syntax
[subs=+macros]
----

pass:quotes[suspend ssdCache [_ssdCacheName_]]
----

== Parameter
[cols="2*",options="header"]
|===
| Parameter| Description
a|
`ssdCache`
a|
The name of the SSD cache that you want to suspend. Enclose the SSD cache name in square brackets ([ ]). If the SSD cache name has special characters or numbers, you must enclose the SSD cache name in double quotation marks (" ") inside square brackets.
|===

== Notes

To restart caching, use the `resume ssdCache` command.

== Minimum firmware level

7.84
